// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'inventoryTransferRemoveItems' GraphQL mutation.
/// </summary>
public sealed partial class InventoryTransferRemoveItemsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public InventoryTransferRemoveItemsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'inventoryTransferRemoveItems' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<InventoryTransferRemoveItemsData>> Execute(InventoryTransferRemoveItemsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation InventoryTransferRemoveItems($input: InventoryTransferRemoveItemsInput!) { inventoryTransferRemoveItems(input: $input) { inventoryTransfer { dateCreated destination { name snapshottedAt } hasTimelineComment id name note origin { name snapshottedAt } receivedQuantity referenceName status tags totalQuantity } removedQuantities { deltaQuantity inventoryItemId newQuantity } userErrors { code field message } } }";
        return _graphQlClient.Execute<InventoryTransferRemoveItemsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'inventoryTransferRemoveItems' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<InventoryTransferRemoveItemsPayload?> GetValue(InventoryTransferRemoveItemsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<InventoryTransferRemoveItemsData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.InventoryTransferRemoveItems;
    }
}
