// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'paymentTermsCreate' GraphQL operation.
/// </summary>
public sealed class PaymentTermsCreateVariables
{
    [JsonPropertyName("referenceId")]
    public string ReferenceId { get; init; } = null!;

    [JsonPropertyName("paymentTermsAttributes")]
    public PaymentTermsCreateInput PaymentTermsAttributes { get; init; } = null!;

}
