// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'marketCurrencySettingsUpdate' GraphQL mutation.
/// </summary>
public sealed partial class MarketCurrencySettingsUpdateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public MarketCurrencySettingsUpdateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'marketCurrencySettingsUpdate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<MarketCurrencySettingsUpdateData>> Execute(MarketCurrencySettingsUpdateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation MarketCurrencySettingsUpdate($marketId: ID!, $input: MarketCurrencySettingsUpdateInput!) { marketCurrencySettingsUpdate(marketId: $marketId, input: $input) { market { catalogsCount { count precision } conditions { conditionTypes } currencySettings { localCurrencies roundingEnabled } enabled handle id name priceInclusions { inclusiveDutiesPricingStrategy inclusiveTaxPricingStrategy } priceList { currency fixedPricesCount id name } primary status type webPresence { id subfolderSuffix } } userErrors { code field message } } }";
        return _graphQlClient.Execute<MarketCurrencySettingsUpdateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'marketCurrencySettingsUpdate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<MarketCurrencySettingsUpdatePayload?> GetValue(MarketCurrencySettingsUpdateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<MarketCurrencySettingsUpdateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.MarketCurrencySettingsUpdate;
    }
}
