// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'productVariantJoinSellingPlanGroups' GraphQL mutation.
/// </summary>
public sealed partial class ProductVariantJoinSellingPlanGroupsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ProductVariantJoinSellingPlanGroupsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'productVariantJoinSellingPlanGroups' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ProductVariantJoinSellingPlanGroupsData>> Execute(ProductVariantJoinSellingPlanGroupsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ProductVariantJoinSellingPlanGroups($id: ID!, $sellingPlanGroupIds: [ID!]!) { productVariantJoinSellingPlanGroups(id: $id, sellingPlanGroupIds: $sellingPlanGroupIds) { productVariant { availableForSale barcode compareAtPrice createdAt defaultCursor deliveryProfile { activeMethodDefinitionsCount default id legacyMode locationsWithoutRatesCount name originLocationCount version zoneCountryCount } displayName id inventoryItem { countryCodeOfOrigin createdAt duplicateSkuCount harmonizedSystemCode id inventoryHistoryUrl legacyResourceId provinceCodeOfOrigin requiresShipping sku tracked updatedAt } inventoryPolicy inventoryQuantity legacyResourceId position price product { bodyHtml combinedListingRole createdAt customProductType defaultCursor descriptionHtml descriptionPlainSummary giftCardTemplateSuffix handle hasOnlyDefaultVariant hasOutOfStockVariants hasVariantsThatRequiresComponents id isGiftCard legacyResourceId onlineStorePreviewUrl onlineStoreUrl productType publishedAt publishedOnCurrentChannel publishedOnCurrentPublication requiresSellingPlan sellingPlanGroupCount status storefrontId tags templateSuffix title totalInventory totalVariants tracksInventory updatedAt vendor } requiresComponents selectedOptions { name value } sellableOnlineQuantity sellingPlanGroupCount sellingPlanGroupsCount { count precision } showUnitPrice sku storefrontId taxCode taxable title unitPrice { amount currencyCode } unitPriceMeasurement { measuredType quantityUnit quantityValue referenceUnit referenceValue } updatedAt } userErrors { code field message } } }";
        return _graphQlClient.Execute<ProductVariantJoinSellingPlanGroupsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'productVariantJoinSellingPlanGroups' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ProductVariantJoinSellingPlanGroupsPayload?> GetValue(ProductVariantJoinSellingPlanGroupsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ProductVariantJoinSellingPlanGroupsData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.ProductVariantJoinSellingPlanGroups;
    }
}
