// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'inventoryMoveQuantities' GraphQL operation.
/// </summary>
public sealed class InventoryMoveQuantitiesVariables
{
    [JsonPropertyName("input")]
    public InventoryMoveQuantitiesInput Input { get; init; } = null!;

}
