// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'inventoryMoveQuantities' GraphQL mutation.
/// </summary>
public sealed partial class InventoryMoveQuantitiesRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public InventoryMoveQuantitiesRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'inventoryMoveQuantities' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<InventoryMoveQuantitiesData>> Execute(InventoryMoveQuantitiesVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation InventoryMoveQuantities($input: InventoryMoveQuantitiesInput!) { inventoryMoveQuantities(input: $input) { inventoryAdjustmentGroup { app { apiKey appStoreAppUrl appStoreDeveloperUrl description developerName developerType developerUrl embedded features handle id installUrl isPostPurchaseAppInUse launchUrl previouslyInstalled pricingDetails pricingDetailsSummary privacyPolicyUrl publicCategory published shopifyDeveloped title uninstallMessage uninstallUrl webhookApiVersion } createdAt id reason referenceDocumentUri staffMember { accountType active email exists firstName id initials isShopOwner lastName locale name phone } } userErrors { code field message } } }";
        return _graphQlClient.Execute<InventoryMoveQuantitiesData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'inventoryMoveQuantities' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<InventoryMoveQuantitiesPayload?> GetValue(InventoryMoveQuantitiesVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<InventoryMoveQuantitiesData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.InventoryMoveQuantities;
    }
}
