// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'companyLocationRemoveStaffMembers' GraphQL operation.
/// </summary>
public sealed class CompanyLocationRemoveStaffMembersVariables
{
    [JsonPropertyName("companyLocationStaffMemberAssignmentIds")]
    public List<string> CompanyLocationStaffMemberAssignmentIds { get; init; } = [];

}
