// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'companyLocationAssignAddress' GraphQL mutation.
/// </summary>
public sealed partial class CompanyLocationAssignAddressRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CompanyLocationAssignAddressRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'companyLocationAssignAddress' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CompanyLocationAssignAddressData>> Execute(CompanyLocationAssignAddressVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CompanyLocationAssignAddress($locationId: ID!, $address: CompanyAddressInput!, $addressTypes: [CompanyAddressType!]!) { companyLocationAssignAddress(locationId: $locationId, address: $address, addressTypes: $addressTypes) { addresses { address1 address2 city companyName country countryCode createdAt firstName formattedArea id lastName phone province recipient updatedAt zip zoneCode } userErrors { code field message } } }";
        return _graphQlClient.Execute<CompanyLocationAssignAddressData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'companyLocationAssignAddress' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<CompanyLocationAssignAddressPayload?> GetValue(CompanyLocationAssignAddressVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CompanyLocationAssignAddressData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.CompanyLocationAssignAddress;
    }
}
