// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'companyAssignCustomerAsContact' GraphQL operation.
/// </summary>
public sealed class CompanyAssignCustomerAsContactVariables
{
    [JsonPropertyName("companyId")]
    public string CompanyId { get; init; } = null!;

    [JsonPropertyName("customerId")]
    public string CustomerId { get; init; } = null!;

}
