// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'productUpdateMedia' GraphQL operation.
/// </summary>
public sealed class ProductUpdateMediaVariables
{
    [JsonPropertyName("productId")]
    public string ProductId { get; init; } = null!;

    [JsonPropertyName("media")]
    public List<UpdateMediaInput> Media { get; init; } = [];

}
