// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'sellingPlanGroupRemoveProducts' GraphQL mutation.
/// </summary>
public sealed partial class SellingPlanGroupRemoveProductsRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public SellingPlanGroupRemoveProductsRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'sellingPlanGroupRemoveProducts' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<SellingPlanGroupRemoveProductsData>> Execute(SellingPlanGroupRemoveProductsVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation SellingPlanGroupRemoveProducts($id: ID!, $productIds: [ID!]!) { sellingPlanGroupRemoveProducts(id: $id, productIds: $productIds) { removedProductIds userErrors { code field message } } }";
        return _graphQlClient.Execute<SellingPlanGroupRemoveProductsData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'sellingPlanGroupRemoveProducts' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<SellingPlanGroupRemoveProductsPayload?> GetValue(SellingPlanGroupRemoveProductsVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<SellingPlanGroupRemoveProductsData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.SellingPlanGroupRemoveProducts;
    }
}
