// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'productFullSync' GraphQL operation.
/// </summary>
public sealed partial class ProductFullSyncData
{
    /// <summary>
    /// Runs the full product sync for a given shop.
    /// </summary>
    [JsonPropertyName("productFullSync")]
    public ProductFullSyncPayload? ProductFullSync { get; init; }
}
