// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'productBundleCreate' GraphQL operation.
/// </summary>
public sealed class ProductBundleCreateVariables
{
    [JsonPropertyName("input")]
    public ProductBundleCreateInput Input { get; init; } = null!;

}
