// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'subscriptionBillingCycleUnskip' GraphQL operation.
/// </summary>
public sealed partial class SubscriptionBillingCycleUnskipData
{
    /// <summary>
    /// Unskips a Subscription Billing Cycle.
    /// </summary>
    [JsonPropertyName("subscriptionBillingCycleUnskip")]
    public SubscriptionBillingCycleUnskipPayload? SubscriptionBillingCycleUnskip { get; init; }
}
