// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'fulfillmentOrderReschedule' GraphQL operation.
/// </summary>
public sealed partial class FulfillmentOrderRescheduleData
{
    /// <summary>
    /// Reschedules a scheduled fulfillment order.
    /// 
    /// Updates the value of the `fulfillAt` field on a scheduled fulfillment order.
    /// 
    /// The fulfillment order will be marked as ready for fulfillment at this date and time.
    /// </summary>
    [JsonPropertyName("fulfillmentOrderReschedule")]
    public FulfillmentOrderReschedulePayload? FulfillmentOrderReschedule { get; init; }
}
