// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'stagedUploadTargetsGenerate' GraphQL operation.
/// </summary>
public sealed class StagedUploadTargetsGenerateVariables
{
    [JsonPropertyName("input")]
    public List<StageImageInput> Input { get; init; } = [];

}
