// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'discountAutomaticAppCreate' GraphQL mutation.
/// </summary>
public sealed partial class DiscountAutomaticAppCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DiscountAutomaticAppCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'discountAutomaticAppCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DiscountAutomaticAppCreateData>> Execute(DiscountAutomaticAppCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DiscountAutomaticAppCreate($automaticAppDiscount: DiscountAutomaticAppInput!) { discountAutomaticAppCreate(automaticAppDiscount: $automaticAppDiscount) { automaticAppDiscount { appDiscountType { appKey description discountClass discountClasses functionId targetType title } appliesOnOneTimePurchase appliesOnSubscription asyncUsageCount combinesWith { orderDiscounts productDiscounts shippingDiscounts } createdAt discountClass discountClasses discountId endsAt errorHistory { errorsFirstOccurredAt firstOccurredAt hasBeenSharedSinceLastError hasSharedRecentErrors } recurringCycleLimit startsAt status title updatedAt } userErrors { code extraInfo field message } } }";
        return _graphQlClient.Execute<DiscountAutomaticAppCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'discountAutomaticAppCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<DiscountAutomaticAppCreatePayload?> GetValue(DiscountAutomaticAppCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DiscountAutomaticAppCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.DiscountAutomaticAppCreate;
    }
}
