// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'subscriptionContractAtomicCreate' GraphQL operation.
/// </summary>
public sealed partial class SubscriptionContractAtomicCreateData
{
    /// <summary>
    /// Creates a Subscription Contract.
    /// </summary>
    [JsonPropertyName("subscriptionContractAtomicCreate")]
    public SubscriptionContractAtomicCreatePayload? SubscriptionContractAtomicCreate { get; init; }
}
