// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'companyRevokeMainContact' GraphQL operation.
/// </summary>
public sealed partial class CompanyRevokeMainContactData
{
    /// <summary>
    /// Revokes the main contact from the company.
    /// </summary>
    [JsonPropertyName("companyRevokeMainContact")]
    public CompanyRevokeMainContactPayload? CompanyRevokeMainContact { get; init; }
}
