// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'sellingPlanGroupAddProducts' GraphQL operation.
/// </summary>
public sealed partial class SellingPlanGroupAddProductsData
{
    /// <summary>
    /// Adds multiple products to a selling plan group.
    /// </summary>
    [JsonPropertyName("sellingPlanGroupAddProducts")]
    public SellingPlanGroupAddProductsPayload? SellingPlanGroupAddProducts { get; init; }
}
