// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'themeFilesUpsert' GraphQL mutation.
/// </summary>
public sealed partial class ThemeFilesUpsertRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ThemeFilesUpsertRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'themeFilesUpsert' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ThemeFilesUpsertData>> Execute(ThemeFilesUpsertVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ThemeFilesUpsert($themeId: ID!, $files: [OnlineStoreThemeFilesUpsertFileInput!]!) { themeFilesUpsert(themeId: $themeId, files: $files) { job { done id query { nodes } } upsertedThemeFiles { checksumMd5 createdAt filename size updatedAt } userErrors { code field filename message } } }";
        return _graphQlClient.Execute<ThemeFilesUpsertData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'themeFilesUpsert' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ThemeFilesUpsertPayload?> GetValue(ThemeFilesUpsertVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ThemeFilesUpsertData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.ThemeFilesUpsert;
    }
}
