// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The delivery method and artifacts associated with a reverse delivery.
/// </summary>
public interface ReverseDeliveryDeliverable
{
}
