// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A calculated return fee.
/// </summary>
public interface CalculatedReturnFee
{
    /// <summary>
    /// The calculated amount of the return fee, in shop and presentment currencies.
    /// </summary>
    MoneyBag AmountSet { get; }

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    string Id { get; }

}
