// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A customer account page.
/// </summary>
public interface CustomerAccountPage
{
    /// <summary>
    /// A default [cursor](https://shopify.dev/api/usage/pagination-graphql) that returns the single next record, sorted ascending by ID.
    /// </summary>
    string DefaultCursor { get; }

    /// <summary>
    /// A unique, human-friendly string for the customer account page.
    /// </summary>
    string Handle { get; }

    /// <summary>
    /// The unique ID for the customer account page.
    /// </summary>
    string Id { get; }

    /// <summary>
    /// The title of the customer account page.
    /// </summary>
    string Title { get; }

}
