// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Resources that metafield definitions can be applied to.
/// </summary>
public interface HasMetafieldDefinitions
{
    /// <summary>
    /// List of metafield definitions.
    /// </summary>
    MetafieldDefinitionConnection MetafieldDefinitions { get; }

}
