// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'customerSegmentMembersQueryCreate' GraphQL operation.
/// </summary>
public sealed partial class CustomerSegmentMembersQueryCreateData
{
    /// <summary>
    /// Creates a customer segment members query.
    /// </summary>
    [JsonPropertyName("customerSegmentMembersQueryCreate")]
    public CustomerSegmentMembersQueryCreatePayload? CustomerSegmentMembersQueryCreate { get; init; }
}
