// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'discountAutomatic' resource.
/// </summary>
public sealed partial class DiscountAutomaticBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DiscountAutomaticBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes grouped requests for the 'discountAutomaticApp' resource.</summary>
    public DiscountAutomaticAppBuilder App => new DiscountAutomaticAppBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes grouped requests for the 'discountAutomaticBasic' resource.</summary>
    public DiscountAutomaticBasicBuilder Basic => new DiscountAutomaticBasicBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes grouped requests for the 'discountAutomaticBxgy' resource.</summary>
    public DiscountAutomaticBxgyBuilder Bxgy => new DiscountAutomaticBxgyBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes grouped requests for the 'discountAutomaticFreeShipping' resource.</summary>
    public DiscountAutomaticFreeShippingBuilder FreeShipping => new DiscountAutomaticFreeShippingBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'discountAutomaticActivate' mutation.</summary>
    public DiscountAutomaticActivateRequestBuilder Activate => new DiscountAutomaticActivateRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'discountAutomaticBulkDelete' mutation.</summary>
    public DiscountAutomaticBulkDeleteRequestBuilder BulkDelete => new DiscountAutomaticBulkDeleteRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'discountAutomaticDeactivate' mutation.</summary>
    public DiscountAutomaticDeactivateRequestBuilder Deactivate => new DiscountAutomaticDeactivateRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'discountAutomaticDelete' mutation.</summary>
    public DiscountAutomaticDeleteRequestBuilder Delete => new DiscountAutomaticDeleteRequestBuilder(_graphQlClient);

}
