// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'customerAddTaxExemptions' GraphQL operation.
/// </summary>
public sealed class CustomerAddTaxExemptionsVariables
{
    [JsonPropertyName("customerId")]
    public string CustomerId { get; init; } = null!;

    [JsonPropertyName("taxExemptions")]
    public List<TaxExemption> TaxExemptions { get; init; } = [];

}
