// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'urlRedirectCreate' GraphQL mutation.
/// </summary>
public sealed partial class UrlRedirectCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public UrlRedirectCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'urlRedirectCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<UrlRedirectCreateData>> Execute(UrlRedirectCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation UrlRedirectCreate($urlRedirect: UrlRedirectInput!) { urlRedirectCreate(urlRedirect: $urlRedirect) { urlRedirect { id path target } userErrors { code field message } } }";
        return _graphQlClient.Execute<UrlRedirectCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'urlRedirectCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<UrlRedirectCreatePayload?> GetValue(UrlRedirectCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<UrlRedirectCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.UrlRedirectCreate;
    }
}
