// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'shopifyPaymentsPayoutAlternateCurrencyCreate' GraphQL mutation.
/// </summary>
public sealed partial class ShopifyPaymentsPayoutAlternateCurrencyCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ShopifyPaymentsPayoutAlternateCurrencyCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'shopifyPaymentsPayoutAlternateCurrencyCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ShopifyPaymentsPayoutAlternateCurrencyCreateData>> Execute(ShopifyPaymentsPayoutAlternateCurrencyCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ShopifyPaymentsPayoutAlternateCurrencyCreate($accountId: ID, $currency: CurrencyCode!) { shopifyPaymentsPayoutAlternateCurrencyCreate(accountId: $accountId, currency: $currency) { payout { amount { amount currencyCode } arrivalDate createdAt currency remoteId } success userErrors { code field message } } }";
        return _graphQlClient.Execute<ShopifyPaymentsPayoutAlternateCurrencyCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'shopifyPaymentsPayoutAlternateCurrencyCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ShopifyPaymentsPayoutAlternateCurrencyCreatePayload?> GetValue(ShopifyPaymentsPayoutAlternateCurrencyCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ShopifyPaymentsPayoutAlternateCurrencyCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.ShopifyPaymentsPayoutAlternateCurrencyCreate;
    }
}
