// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'marketWebPresenceUpdate' GraphQL mutation.
/// </summary>
public sealed partial class MarketWebPresenceUpdateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public MarketWebPresenceUpdateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'marketWebPresenceUpdate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<MarketWebPresenceUpdateData>> Execute(MarketWebPresenceUpdateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation MarketWebPresenceUpdate($webPresenceId: ID!, $webPresence: MarketWebPresenceUpdateInput!) { marketWebPresenceUpdate(webPresenceId: $webPresenceId, webPresence: $webPresence) { market { catalogsCount { count precision } conditions { conditionTypes } currencySettings { localCurrencies roundingEnabled } enabled handle id name priceInclusions { inclusiveDutiesPricingStrategy inclusiveTaxPricingStrategy } priceList { currency fixedPricesCount id name } primary status type webPresence { id subfolderSuffix } } userErrors { code field message } } }";
        return _graphQlClient.Execute<MarketWebPresenceUpdateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'marketWebPresenceUpdate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<MarketWebPresenceUpdatePayload?> GetValue(MarketWebPresenceUpdateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<MarketWebPresenceUpdateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.MarketWebPresenceUpdate;
    }
}
