// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'marketWebPresenceUpdate' GraphQL operation.
/// </summary>
public sealed class MarketWebPresenceUpdateVariables
{
    [JsonPropertyName("webPresenceId")]
    public string WebPresenceId { get; init; } = null!;

    [JsonPropertyName("webPresence")]
    public MarketWebPresenceUpdateInput WebPresence { get; init; } = null!;

}
