// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'validationCreate' GraphQL mutation.
/// </summary>
public sealed partial class ValidationCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ValidationCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'validationCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ValidationCreateData>> Execute(ValidationCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ValidationCreate($validation: ValidationCreateInput!) { validationCreate(validation: $validation) { userErrors { code field message } validation { blockOnFailure enabled errorHistory { errorsFirstOccurredAt firstOccurredAt hasBeenSharedSinceLastError hasSharedRecentErrors } id shopifyFunction { apiType apiVersion appKey description handle id inputQuery title useCreationUi } title } } }";
        return _graphQlClient.Execute<ValidationCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'validationCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ValidationCreatePayload?> GetValue(ValidationCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ValidationCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.ValidationCreate;
    }
}
