// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'orderInvoiceSend' GraphQL operation.
/// </summary>
public sealed class OrderInvoiceSendVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("email")]
    public EmailInput? Email { get; init; }

}
