// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'collectionUpdate' GraphQL operation.
/// </summary>
public sealed class CollectionUpdateVariables
{
    [JsonPropertyName("input")]
    public CollectionInput Input { get; init; } = null!;

}
