// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'discountCodeDeactivate' GraphQL mutation.
/// </summary>
public sealed partial class DiscountCodeDeactivateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DiscountCodeDeactivateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'discountCodeDeactivate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DiscountCodeDeactivateData>> Execute(DiscountCodeDeactivateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DiscountCodeDeactivate($id: ID!) { discountCodeDeactivate(id: $id) { codeDiscountNode { id } userErrors { code extraInfo field message } } }";
        return _graphQlClient.Execute<DiscountCodeDeactivateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'discountCodeDeactivate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<DiscountCodeDeactivatePayload?> GetValue(DiscountCodeDeactivateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DiscountCodeDeactivateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.DiscountCodeDeactivate;
    }
}
