// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'taxSummaryCreate' GraphQL operation.
/// </summary>
public sealed partial class TaxSummaryCreateData
{
    /// <summary>
    /// Creates a tax summary for a given order.
    /// If both an order ID and a start and end time are provided, the order ID will be used.
    /// </summary>
    [JsonPropertyName("taxSummaryCreate")]
    public TaxSummaryCreatePayload? TaxSummaryCreate { get; init; }
}
