// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'paymentCustomizationUpdate' GraphQL operation.
/// </summary>
public sealed class PaymentCustomizationUpdateVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("paymentCustomization")]
    public PaymentCustomizationInput PaymentCustomization { get; init; } = null!;

}
