// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'locationDeactivate' GraphQL mutation.
/// </summary>
public sealed partial class LocationDeactivateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public LocationDeactivateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'locationDeactivate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<LocationDeactivateData>> Execute(LocationDeactivateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation LocationDeactivate($locationId: ID!, $destinationLocationId: ID) { locationDeactivate(locationId: $locationId, destinationLocationId: $destinationLocationId) { location { activatable address { address1 address2 city country countryCode formatted latitude longitude phone province provinceCode zip } addressVerified createdAt deactivatable deactivatedAt deletable fulfillmentService { callbackUrl fulfillmentOrdersOptIn handle id inventoryManagement permitsSkuSharing requiresShippingMethod serviceName trackingSupport type } fulfillsOnlineOrders hasActiveInventory hasUnfulfilledOrders id isActive isFulfillmentService isPrimary legacyResourceId localPickupSettingsV2 { instructions pickupTime } name shipsInventory suggestedAddresses { address1 address2 city country countryCode formatted province provinceCode zip } updatedAt } locationDeactivateUserErrors { code field message } } }";
        return _graphQlClient.Execute<LocationDeactivateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'locationDeactivate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<LocationDeactivatePayload?> GetValue(LocationDeactivateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<LocationDeactivateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.LocationDeactivate;
    }
}
