// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'discountCodeFreeShippingUpdate' GraphQL operation.
/// </summary>
public sealed class DiscountCodeFreeShippingUpdateVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("freeShippingCodeDiscount")]
    public DiscountCodeFreeShippingInput FreeShippingCodeDiscount { get; init; } = null!;

}
