// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'abandonmentUpdateActivitiesDeliveryStatuses' GraphQL operation.
/// </summary>
public sealed partial class AbandonmentUpdateActivitiesDeliveryStatusesData
{
    /// <summary>
    /// Updates the marketing activities delivery statuses for an abandonment.
    /// </summary>
    [JsonPropertyName("abandonmentUpdateActivitiesDeliveryStatuses")]
    public AbandonmentUpdateActivitiesDeliveryStatusesPayload? AbandonmentUpdateActivitiesDeliveryStatuses { get; init; }
}
