// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'fileUpdate' GraphQL operation.
/// </summary>
public sealed class FileUpdateVariables
{
    [JsonPropertyName("files")]
    public List<FileUpdateInput> Files { get; init; } = [];

}
