// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'locationLocalPickupEnable' GraphQL mutation.
/// </summary>
public sealed partial class LocationLocalPickupEnableRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public LocationLocalPickupEnableRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'locationLocalPickupEnable' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<LocationLocalPickupEnableData>> Execute(LocationLocalPickupEnableVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation LocationLocalPickupEnable($localPickupSettings: DeliveryLocationLocalPickupEnableInput!) { locationLocalPickupEnable(localPickupSettings: $localPickupSettings) { localPickupSettings { instructions pickupTime } userErrors { code field message } } }";
        return _graphQlClient.Execute<LocationLocalPickupEnableData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'locationLocalPickupEnable' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<LocationLocalPickupEnablePayload?> GetValue(LocationLocalPickupEnableVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<LocationLocalPickupEnableData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.LocationLocalPickupEnable;
    }
}
