// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'fulfillmentOrderReleaseHold' GraphQL operation.
/// </summary>
public sealed class FulfillmentOrderReleaseHoldVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("holdIds")]
    public List<string>? HoldIds { get; init; }

    [JsonPropertyName("externalId")]
    public string? ExternalId { get; init; }

}
