// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'savedSearchDelete' GraphQL operation.
/// </summary>
public sealed class SavedSearchDeleteVariables
{
    [JsonPropertyName("input")]
    public SavedSearchDeleteInput Input { get; init; } = null!;

}
