// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'sellingPlanGroupAddProductVariants' GraphQL operation.
/// </summary>
public sealed partial class SellingPlanGroupAddProductVariantsData
{
    /// <summary>
    /// Adds multiple product variants to a selling plan group.
    /// </summary>
    [JsonPropertyName("sellingPlanGroupAddProductVariants")]
    public SellingPlanGroupAddProductVariantsPayload? SellingPlanGroupAddProductVariants { get; init; }
}
