// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'discountCodeBulkDelete' GraphQL operation.
/// </summary>
public sealed partial class DiscountCodeBulkDeleteData
{
    /// <summary>
    /// Deletes multiple [code-based discounts](https://help.shopify.com/manual/discounts/discount-types#discount-codes) asynchronously using one of the following:
    /// - A search query
    /// - A saved search ID
    /// - A list of discount code IDs
    /// 
    /// For example, you can delete discounts for all codes that match a search criteria, or delete a predefined set of discount codes.
    /// </summary>
    [JsonPropertyName("discountCodeBulkDelete")]
    public DiscountCodeBulkDeletePayload? DiscountCodeBulkDelete { get; init; }
}
