// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'companyContactAssignRole' GraphQL operation.
/// </summary>
public sealed partial class CompanyContactAssignRoleData
{
    /// <summary>
    /// Assigns a role to a contact for a location.
    /// </summary>
    [JsonPropertyName("companyContactAssignRole")]
    public CompanyContactAssignRolePayload? CompanyContactAssignRole { get; init; }
}
