// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'inventoryShipment' resource.
/// </summary>
public sealed partial class InventoryShipmentBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public InventoryShipmentBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentAddItems' mutation.</summary>
    public InventoryShipmentAddItemsRequestBuilder AddItems => new InventoryShipmentAddItemsRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentCreate' mutation.</summary>
    public InventoryShipmentCreateRequestBuilder Create => new InventoryShipmentCreateRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentCreateInTransit' mutation.</summary>
    public InventoryShipmentCreateInTransitRequestBuilder CreateInTransit => new InventoryShipmentCreateInTransitRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentDelete' mutation.</summary>
    public InventoryShipmentDeleteRequestBuilder Delete => new InventoryShipmentDeleteRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentMarkInTransit' mutation.</summary>
    public InventoryShipmentMarkInTransitRequestBuilder MarkInTransit => new InventoryShipmentMarkInTransitRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentReceive' mutation.</summary>
    public InventoryShipmentReceiveRequestBuilder Receive => new InventoryShipmentReceiveRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentRemoveItems' mutation.</summary>
    public InventoryShipmentRemoveItemsRequestBuilder RemoveItems => new InventoryShipmentRemoveItemsRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentSetTracking' mutation.</summary>
    public InventoryShipmentSetTrackingRequestBuilder SetTracking => new InventoryShipmentSetTrackingRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'inventoryShipmentUpdateItemQuantities' mutation.</summary>
    public InventoryShipmentUpdateItemQuantitiesRequestBuilder UpdateItemQuantities => new InventoryShipmentUpdateItemQuantitiesRequestBuilder(_graphQlClient);

}
