// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'metafields' resource.
/// </summary>
public sealed partial class MetafieldsBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public MetafieldsBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'metafieldsDelete' mutation.</summary>
    public MetafieldsDeleteRequestBuilder Delete => new MetafieldsDeleteRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'metafieldsSet' mutation.</summary>
    public MetafieldsSetRequestBuilder Set => new MetafieldsSetRequestBuilder(_graphQlClient);

}
