// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'companyContactRevokeRole' GraphQL operation.
/// </summary>
public sealed class CompanyContactRevokeRoleVariables
{
    [JsonPropertyName("companyContactId")]
    public string CompanyContactId { get; init; } = null!;

    [JsonPropertyName("companyContactRoleAssignmentId")]
    public string CompanyContactRoleAssignmentId { get; init; } = null!;

}
