// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'web' resource.
/// </summary>
public sealed partial class WebBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public WebBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes grouped requests for the 'webPixel' resource.</summary>
    public WebPixelBuilder Pixel => new WebPixelBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes grouped requests for the 'webPresence' resource.</summary>
    public WebPresenceBuilder Presence => new WebPresenceBuilder(_graphQlClient);

}
