// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'subscriptionDraftLineUpdate' GraphQL mutation.
/// </summary>
public sealed partial class SubscriptionDraftLineUpdateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public SubscriptionDraftLineUpdateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'subscriptionDraftLineUpdate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<SubscriptionDraftLineUpdateData>> Execute(SubscriptionDraftLineUpdateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation SubscriptionDraftLineUpdate($draftId: ID!, $lineId: ID!, $input: SubscriptionLineUpdateInput!) { subscriptionDraftLineUpdate(draftId: $draftId, lineId: $lineId, input: $input) { draft { billingCycle { billingAttemptExpectedDate cycleEndAt cycleIndex cycleStartAt edited skipped status } billingPolicy { interval intervalCount maxCycles minCycles } currencyCode customAttributes { key value } customer { canDelete createdAt dataSaleOptOut displayName email firstName hasTimelineComment id lastName legacyResourceId lifetimeDuration locale multipassIdentifier note numberOfOrders phone productSubscriberStatus state tags taxExempt taxExemptions unsubscribeUrl updatedAt validEmailAddress verifiedEmail } deliveryPolicy { interval intervalCount } deliveryPrice { amount currencyCode } id nextBillingDate note originalContract { appAdminUrl createdAt currencyCode id lastBillingAttemptErrorType lastPaymentStatus lineCount nextBillingDate note revisionId status updatedAt } status } lineUpdated { concatenatedOriginContract { appAdminUrl createdAt currencyCode id lastBillingAttemptErrorType lastPaymentStatus lineCount nextBillingDate note revisionId status updatedAt } currentPrice { amount currencyCode } customAttributes { key value } discountAllocations { id } id lineDiscountedPrice { amount currencyCode } pricingPolicy { id } productId quantity requiresShipping sellingPlanId sellingPlanName sku taxable title variantId variantImage { altText height id originalSrc src thumbhash width } variantTitle } userErrors { code field message } } }";
        return _graphQlClient.Execute<SubscriptionDraftLineUpdateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'subscriptionDraftLineUpdate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<SubscriptionDraftLineUpdatePayload?> GetValue(SubscriptionDraftLineUpdateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<SubscriptionDraftLineUpdateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.SubscriptionDraftLineUpdate;
    }
}
