// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'storeCreditAccountDebit' GraphQL mutation.
/// </summary>
public sealed partial class StoreCreditAccountDebitRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public StoreCreditAccountDebitRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'storeCreditAccountDebit' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<StoreCreditAccountDebitData>> Execute(StoreCreditAccountDebitVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation StoreCreditAccountDebit($id: ID!, $debitInput: StoreCreditAccountDebitInput!) { storeCreditAccountDebit(id: $id, debitInput: $debitInput) { storeCreditAccountTransaction { account { id } amount { amount currencyCode } balanceAfterTransaction { amount currencyCode } createdAt event id } userErrors { code field message } } }";
        return _graphQlClient.Execute<StoreCreditAccountDebitData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'storeCreditAccountDebit' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<StoreCreditAccountDebitPayload?> GetValue(StoreCreditAccountDebitVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<StoreCreditAccountDebitData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.StoreCreditAccountDebit;
    }
}
