// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'companyAssignMainContact' GraphQL operation.
/// </summary>
public sealed partial class CompanyAssignMainContactData
{
    /// <summary>
    /// Assigns the main contact for the company.
    /// </summary>
    [JsonPropertyName("companyAssignMainContact")]
    public CompanyAssignMainContactPayload? CompanyAssignMainContact { get; init; }
}
