// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'metafieldsSet' GraphQL operation.
/// </summary>
public sealed partial class MetafieldsSetData
{
    /// <summary>
    /// Sets metafield values. Metafield values will be set regardless if they were previously created or not.
    /// 
    /// Allows a maximum of 25 metafields to be set at a time, with a maximum total request payload size of 10MB.
    /// 
    /// This operation is atomic, meaning no changes are persisted if an error is encountered.
    /// 
    /// As of `2024-07`, this operation supports compare-and-set functionality to better handle concurrent requests.
    /// If `compareDigest` is set for any metafield, the mutation will only set that metafield if the persisted metafield value matches the digest used on `compareDigest`.
    /// If the metafield doesn't exist yet, but you want to guarantee that the operation will run in a safe manner, set `compareDigest` to `null`.
    /// The `compareDigest` value can be acquired by querying the metafield object and selecting `compareDigest` as a field.
    /// If the `compareDigest` value does not match the digest for the persisted value, the mutation will return an error.
    /// You can opt out of write guarantees by not sending `compareDigest` in the request.
    /// </summary>
    [JsonPropertyName("metafieldsSet")]
    public MetafieldsSetPayload? MetafieldsSet { get; init; }
}
