// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'shopPolicyUpdate' GraphQL operation.
/// </summary>
public sealed partial class ShopPolicyUpdateData
{
    /// <summary>
    /// Updates a shop policy.
    /// </summary>
    [JsonPropertyName("shopPolicyUpdate")]
    public ShopPolicyUpdatePayload? ShopPolicyUpdate { get; init; }
}
