// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'reverseDeliveryShippingUpdate' GraphQL mutation.
/// </summary>
public sealed partial class ReverseDeliveryShippingUpdateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ReverseDeliveryShippingUpdateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'reverseDeliveryShippingUpdate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ReverseDeliveryShippingUpdateData>> Execute(ReverseDeliveryShippingUpdateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ReverseDeliveryShippingUpdate($reverseDeliveryId: ID!, $trackingInput: ReverseDeliveryTrackingInput, $labelInput: ReverseDeliveryLabelInput, $notifyCustomer: Boolean) { reverseDeliveryShippingUpdate(reverseDeliveryId: $reverseDeliveryId, trackingInput: $trackingInput, labelInput: $labelInput, notifyCustomer: $notifyCustomer) { reverseDelivery { id reverseFulfillmentOrder { id status } } userErrors { code field message } } }";
        return _graphQlClient.Execute<ReverseDeliveryShippingUpdateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'reverseDeliveryShippingUpdate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ReverseDeliveryShippingUpdatePayload?> GetValue(ReverseDeliveryShippingUpdateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ReverseDeliveryShippingUpdateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.ReverseDeliveryShippingUpdate;
    }
}
