// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'customerGenerateAccountActivationUrl' GraphQL mutation.
/// </summary>
public sealed partial class CustomerGenerateAccountActivationUrlRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CustomerGenerateAccountActivationUrlRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'customerGenerateAccountActivationUrl' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CustomerGenerateAccountActivationUrlData>> Execute(CustomerGenerateAccountActivationUrlVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CustomerGenerateAccountActivationUrl($customerId: ID!) { customerGenerateAccountActivationUrl(customerId: $customerId) { accountActivationUrl userErrors { field message } } }";
        return _graphQlClient.Execute<CustomerGenerateAccountActivationUrlData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'customerGenerateAccountActivationUrl' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<CustomerGenerateAccountActivationUrlPayload?> GetValue(CustomerGenerateAccountActivationUrlVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CustomerGenerateAccountActivationUrlData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.CustomerGenerateAccountActivationUrl;
    }
}
