// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'shippingPackageDelete' GraphQL operation.
/// </summary>
public sealed partial class ShippingPackageDeleteData
{
    /// <summary>
    /// Deletes a shipping package.
    /// </summary>
    [JsonPropertyName("shippingPackageDelete")]
    public ShippingPackageDeletePayload? ShippingPackageDelete { get; init; }
}
