// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'subscriptionBillingAttemptCreate' GraphQL mutation.
/// </summary>
public sealed partial class SubscriptionBillingAttemptCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public SubscriptionBillingAttemptCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'subscriptionBillingAttemptCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<SubscriptionBillingAttemptCreateData>> Execute(SubscriptionBillingAttemptCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation SubscriptionBillingAttemptCreate($subscriptionContractId: ID!, $subscriptionBillingAttemptInput: SubscriptionBillingAttemptInput!) { subscriptionBillingAttemptCreate(subscriptionContractId: $subscriptionContractId, subscriptionBillingAttemptInput: $subscriptionBillingAttemptInput) { subscriptionBillingAttempt { completedAt createdAt errorCode errorMessage id idempotencyKey nextActionUrl order { billingAddressMatchesShippingAddress canMarkAsPaid canNotifyCustomer cancelReason cancelledAt capturable cartDiscountAmount clientIp closed closedAt confirmationNumber confirmed createdAt currencyCode currentSubtotalLineItemsQuantity currentTotalWeight customerAcceptsMarketing customerLocale discountCode discountCodes displayFinancialStatus displayFulfillmentStatus dutiesIncluded edited email estimatedTaxes fulfillable fullyPaid hasTimelineComment id landingPageDisplayText landingPageUrl legacyResourceId merchantEditable merchantEditableErrors name netPayment note number paymentGatewayNames phone poNumber presentmentCurrencyCode processedAt productNetwork referralCode referrerDisplayText referrerUrl refundable registeredSourceUrl requiresShipping restockable returnStatus riskLevel sourceIdentifier sourceName subtotalLineItemsQuantity subtotalPrice tags taxExempt taxesIncluded test totalCapturable totalDiscounts totalPrice totalReceived totalRefunded totalShippingPrice totalTax totalWeight unpaid updatedAt } originTime paymentGroupId paymentSessionId processingError { code message } ready respectInventoryPolicy subscriptionContract { appAdminUrl createdAt currencyCode id lastBillingAttemptErrorType lastPaymentStatus lineCount nextBillingDate note revisionId status updatedAt } } userErrors { code field message } } }";
        return _graphQlClient.Execute<SubscriptionBillingAttemptCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'subscriptionBillingAttemptCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<SubscriptionBillingAttemptCreatePayload?> GetValue(SubscriptionBillingAttemptCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<SubscriptionBillingAttemptCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.SubscriptionBillingAttemptCreate;
    }
}
