// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'subscriptionContractAtomicCreate' GraphQL operation.
/// </summary>
public sealed class SubscriptionContractAtomicCreateVariables
{
    [JsonPropertyName("input")]
    public SubscriptionContractAtomicCreateInput Input { get; init; } = null!;

}
