// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'themeCreate' GraphQL mutation.
/// </summary>
public sealed partial class ThemeCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ThemeCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'themeCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<ThemeCreateData>> Execute(ThemeCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation ThemeCreate($source: URL!, $name: String, $role: ThemeRole) { themeCreate(source: $source, name: $name, role: $role) { theme { createdAt id name prefix processing processingFailed role themeStoreId updatedAt } userErrors { code field message } } }";
        return _graphQlClient.Execute<ThemeCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'themeCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<ThemeCreatePayload?> GetValue(ThemeCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<ThemeCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.ThemeCreate;
    }
}
