// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'quantityPricingByVariantUpdate' GraphQL operation.
/// </summary>
public sealed class QuantityPricingByVariantUpdateVariables
{
    [JsonPropertyName("priceListId")]
    public string PriceListId { get; init; } = null!;

    [JsonPropertyName("input")]
    public QuantityPricingByVariantUpdateInput Input { get; init; } = null!;

}
