// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'serverPixel' resource.
/// </summary>
public sealed partial class ServerPixelBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ServerPixelBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'serverPixelCreate' mutation.</summary>
    public ServerPixelCreateRequestBuilder Create => new ServerPixelCreateRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'serverPixelDelete' mutation.</summary>
    public ServerPixelDeleteRequestBuilder Delete => new ServerPixelDeleteRequestBuilder(_graphQlClient);

}
