// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'inventoryAdjustQuantities' GraphQL mutation.
/// </summary>
public sealed partial class InventoryAdjustQuantitiesRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public InventoryAdjustQuantitiesRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'inventoryAdjustQuantities' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<InventoryAdjustQuantitiesData>> Execute(InventoryAdjustQuantitiesVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation InventoryAdjustQuantities($input: InventoryAdjustQuantitiesInput!) { inventoryAdjustQuantities(input: $input) { inventoryAdjustmentGroup { app { apiKey appStoreAppUrl appStoreDeveloperUrl description developerName developerType developerUrl embedded features handle id installUrl isPostPurchaseAppInUse launchUrl previouslyInstalled pricingDetails pricingDetailsSummary privacyPolicyUrl publicCategory published shopifyDeveloped title uninstallMessage uninstallUrl webhookApiVersion } createdAt id reason referenceDocumentUri staffMember { accountType active email exists firstName id initials isShopOwner lastName locale name phone } } userErrors { code field message } } }";
        return _graphQlClient.Execute<InventoryAdjustQuantitiesData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'inventoryAdjustQuantities' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<InventoryAdjustQuantitiesPayload?> GetValue(InventoryAdjustQuantitiesVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<InventoryAdjustQuantitiesData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.InventoryAdjustQuantities;
    }
}
