// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'orderEditAddLineItemDiscount' GraphQL operation.
/// </summary>
public sealed class OrderEditAddLineItemDiscountVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("lineItemId")]
    public string LineItemId { get; init; } = null!;

    [JsonPropertyName("discount")]
    public OrderEditAppliedDiscountInput Discount { get; init; } = null!;

}
