// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'orderCapture' GraphQL operation.
/// </summary>
public sealed partial class OrderCaptureData
{
    /// <summary>
    /// Captures payment for an authorized transaction on an order. Use this mutation to claim the money that was previously
    /// reserved by an authorization transaction.
    /// 
    /// The `orderCapture` mutation can be used in the following scenarios:
    /// 
    /// - To capture the full amount of an authorized transaction
    /// - To capture a partial payment by specifying an amount less than the total order amount
    /// - To perform multiple captures on the same order, as long as the order transaction is
    /// [multi-capturable](https://shopify.dev/docs/api/admin-graphql/latest/objects/ordertransaction#field-OrderTransaction.fields.multiCapturable)
    /// 
    /// &gt; Note:
    /// &gt; Multi-capture functionality is only available to stores on a
    /// [Shopify Plus plan](https://help.shopify.com/manual/intro-to-shopify/pricing-plans/plans-features/shopify-plus-plan).
    /// For multi-currency orders, the [`currency`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/orderCapture#arguments-input.fields.currency)
    /// field is required and should match the presentment currency from the order.
    /// 
    /// After capturing a payment, you can:
    /// 
    /// - View the transaction details including status, amount, and processing information.
    /// - Track the captured amount in both shop and presentment currencies.
    /// - Monitor the transaction's settlement status.
    /// 
    /// Learn more about [order transactions](https://shopify.dev/docs/api/admin-graphql/latest/objects/OrderTransaction).
    /// </summary>
    [JsonPropertyName("orderCapture")]
    public OrderCapturePayload? OrderCapture { get; init; }
}
