// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'inventoryBulkToggleActivation' GraphQL mutation.
/// </summary>
public sealed partial class InventoryBulkToggleActivationRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public InventoryBulkToggleActivationRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'inventoryBulkToggleActivation' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<InventoryBulkToggleActivationData>> Execute(InventoryBulkToggleActivationVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation InventoryBulkToggleActivation($inventoryItemId: ID!, $inventoryItemUpdates: [InventoryBulkToggleActivationInput!]!) { inventoryBulkToggleActivation(inventoryItemId: $inventoryItemId, inventoryItemUpdates: $inventoryItemUpdates) { inventoryItem { countryCodeOfOrigin createdAt duplicateSkuCount harmonizedSystemCode id inventoryHistoryUrl legacyResourceId locationsCount { count precision } measurement { id } provinceCodeOfOrigin requiresShipping sku tracked trackedEditable { locked reason } unitCost { amount currencyCode } updatedAt variant { availableForSale barcode compareAtPrice createdAt defaultCursor displayName id inventoryPolicy inventoryQuantity legacyResourceId position price requiresComponents sellableOnlineQuantity sellingPlanGroupCount showUnitPrice sku storefrontId taxCode taxable title updatedAt } } inventoryLevels { canDeactivate createdAt deactivationAlert id item { countryCodeOfOrigin createdAt duplicateSkuCount harmonizedSystemCode id inventoryHistoryUrl legacyResourceId provinceCodeOfOrigin requiresShipping sku tracked updatedAt } location { activatable addressVerified createdAt deactivatable deactivatedAt deletable fulfillsOnlineOrders hasActiveInventory hasUnfulfilledOrders id isActive isFulfillmentService isPrimary legacyResourceId name shipsInventory updatedAt } updatedAt } userErrors { code field message } } }";
        return _graphQlClient.Execute<InventoryBulkToggleActivationData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'inventoryBulkToggleActivation' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<InventoryBulkToggleActivationPayload?> GetValue(InventoryBulkToggleActivationVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<InventoryBulkToggleActivationData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.InventoryBulkToggleActivation;
    }
}
