// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'productDeleteMedia' GraphQL operation.
/// </summary>
public sealed partial class ProductDeleteMediaData
{
    /// <summary>
    /// Deletes media from a [`Product`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Product), such as images, videos, and 3D models.
    /// 
    /// When you delete media images, the mutation also removes any corresponding product images. The mutation returns the IDs of both the deleted media and any product images that the deletion removed.
    /// 
    /// &gt; Caution:
    /// &gt; This action is irreversible. You can't recover deleted media.
    /// </summary>
    [JsonPropertyName("productDeleteMedia")]
    public ProductDeleteMediaPayload? ProductDeleteMedia { get; init; }
}
