// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'blogCreate' GraphQL operation.
/// </summary>
public sealed partial class BlogCreateData
{
    /// <summary>
    /// Creates a new blog within a shop, establishing a container for organizing articles.
    /// 
    /// For example, a fitness equipment retailer launching a wellness blog would use this mutation to create the blog, enabling them to publish workout guides and nutrition tips.
    /// 
    /// Use the `blogCreate` mutation to:
    /// - Launch new content marketing initiatives
    /// - Create separate blogs for different content themes
    /// - Establish spaces for article organization
    /// 
    /// The mutation validates blog settings and establishes the structure for article publishing.
    /// </summary>
    [JsonPropertyName("blogCreate")]
    public BlogCreatePayload? BlogCreate { get; init; }
}
