// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'productVariantDetachMedia' GraphQL operation.
/// </summary>
public sealed class ProductVariantDetachMediaVariables
{
    [JsonPropertyName("productId")]
    public string ProductId { get; init; } = null!;

    [JsonPropertyName("variantMedia")]
    public List<ProductVariantDetachMediaInput> VariantMedia { get; init; } = [];

}
