// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Tracks a [customer](https://shopify.dev/docs/api/admin-graphql/latest/objects/Customer)'s incomplete shopping journey, whether they abandoned while browsing [products](https://shopify.dev/docs/api/admin-graphql/latest/objects/Product), adding items to cart, or during checkout. Provides data about the customer's behavior and products they interacted with.
/// 
/// The abandonment includes fields that indicate whether the customer has completed any [orders](https://shopify.dev/docs/api/admin-graphql/latest/objects/Order) or [draft orders](https://shopify.dev/docs/api/admin-graphql/latest/objects/DraftOrder) after the abandonment occurred. It also tracks when emails were sent and how long since the customer's last activity across different abandonment types.
/// </summary>
public sealed partial class Abandonment : Node
{
    /// <summary>
    /// The abandonment payload for the abandoned checkout.
    /// </summary>
    [JsonPropertyName("abandonedCheckoutPayload")]
    public AbandonedCheckout? AbandonedCheckoutPayload { get; init; }

    /// <summary>
    /// The abandonment type.
    /// </summary>
    [JsonPropertyName("abandonmentType")]
    public AbandonmentAbandonmentType AbandonmentType { get; init; }

    /// <summary>
    /// The app associated with an abandoned checkout.
    /// </summary>
    [JsonPropertyName("app")]
    public App App { get; init; } = null!;

    /// <summary>
    /// Permalink to the cart page.
    /// </summary>
    [JsonPropertyName("cartUrl")]
    public Uri? CartUrl { get; init; }

    /// <summary>
    /// The date and time when the abandonment was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// The customer who abandoned this event.
    /// </summary>
    [JsonPropertyName("customer")]
    public Customer Customer { get; init; } = null!;

    /// <summary>
    /// Whether the customer has a draft order since this abandonment has been abandoned.
    /// </summary>
    [JsonPropertyName("customerHasNoDraftOrderSinceAbandonment")]
    public bool CustomerHasNoDraftOrderSinceAbandonment { get; init; }

    /// <summary>
    /// Whether the customer has completed an order since this checkout has been abandoned.
    /// </summary>
    [JsonPropertyName("customerHasNoOrderSinceAbandonment")]
    public bool CustomerHasNoOrderSinceAbandonment { get; init; }

    /// <summary>
    /// The number of days since the last abandonment email was sent to the customer.
    /// </summary>
    [JsonPropertyName("daysSinceLastAbandonmentEmail")]
    public int DaysSinceLastAbandonmentEmail { get; init; }

    /// <summary>
    /// When the email was sent, if that's the case.
    /// </summary>
    [JsonPropertyName("emailSentAt")]
    public DateTimeOffset? EmailSentAt { get; init; }

    /// <summary>
    /// The email state (e.g., sent or not sent).
    /// </summary>
    [JsonPropertyName("emailState")]
    public AbandonmentEmailState? EmailState { get; init; }

    /// <summary>
    /// The number of hours since the customer has last abandoned a checkout.
    /// </summary>
    [JsonPropertyName("hoursSinceLastAbandonedCheckout")]
    public double? HoursSinceLastAbandonedCheckout { get; init; }

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Whether the products in abandonment are available.
    /// </summary>
    [JsonPropertyName("inventoryAvailable")]
    public bool InventoryAvailable { get; init; }

    /// <summary>
    /// Whether the abandonment event comes from a custom storefront channel.
    /// </summary>
    [JsonPropertyName("isFromCustomStorefront")]
    public bool IsFromCustomStorefront { get; init; }

    /// <summary>
    /// Whether the abandonment event comes from the Online Store sales channel.
    /// </summary>
    [JsonPropertyName("isFromOnlineStore")]
    public bool IsFromOnlineStore { get; init; }

    /// <summary>
    /// Whether the abandonment event comes from the Shop app sales channel.
    /// </summary>
    [JsonPropertyName("isFromShopApp")]
    public bool IsFromShopApp { get; init; }

    /// <summary>
    /// Whether the abandonment event comes from Shop Pay.
    /// </summary>
    [JsonPropertyName("isFromShopPay")]
    public bool IsFromShopPay { get; init; }

    /// <summary>
    /// Whether the customer didn't complete another most significant step since this abandonment.
    /// </summary>
    [JsonPropertyName("isMostSignificantAbandonment")]
    public bool IsMostSignificantAbandonment { get; init; }

    /// <summary>
    /// The date for the latest browse abandonment.
    /// </summary>
    [JsonPropertyName("lastBrowseAbandonmentDate")]
    public DateTimeOffset LastBrowseAbandonmentDate { get; init; }

    /// <summary>
    /// The date for the latest cart abandonment.
    /// </summary>
    [JsonPropertyName("lastCartAbandonmentDate")]
    public DateTimeOffset LastCartAbandonmentDate { get; init; }

    /// <summary>
    /// The date for the latest checkout abandonment.
    /// </summary>
    [JsonPropertyName("lastCheckoutAbandonmentDate")]
    public DateTimeOffset LastCheckoutAbandonmentDate { get; init; }

    /// <summary>
    /// The most recent step type.
    /// </summary>
    [JsonPropertyName("mostRecentStep")]
    public AbandonmentAbandonmentType MostRecentStep { get; init; }

    /// <summary>
    /// The products added to the cart during the customer abandoned visit.
    /// </summary>
    [JsonPropertyName("productsAddedToCart")]
    public CustomerVisitProductInfoConnection ProductsAddedToCart { get; init; } = null!;

    /// <summary>
    /// The products viewed during the customer abandoned visit.
    /// </summary>
    [JsonPropertyName("productsViewed")]
    public CustomerVisitProductInfoConnection ProductsViewed { get; init; } = null!;

    /// <summary>
    /// The date and time when the visit started.
    /// </summary>
    [JsonPropertyName("visitStartedAt")]
    public DateTimeOffset? VisitStartedAt { get; init; }

}
