// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// An incomplete checkout where the customer added items and provided contact information but didn't complete the purchase. Tracks the customer's cart contents, pricing details, addresses, and timestamps to enable recovery campaigns and abandonment analytics.
/// 
/// The checkout includes a recovery URL that merchants can send to customers to resume their purchase. [`AbandonedCheckoutLineItem`](https://shopify.dev/docs/api/admin-graphql/latest/objects/AbandonedCheckoutLineItem) objects preserve the original [`Product`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Product) selections, quantities, and pricing at the time of abandonment.
/// </summary>
public sealed partial class AbandonedCheckout : Navigable, Node
{
    /// <summary>
    /// The URL for the buyer to recover their checkout.
    /// </summary>
    [JsonPropertyName("abandonedCheckoutUrl")]
    public Uri AbandonedCheckoutUrl { get; init; } = null!;

    /// <summary>
    /// The billing address provided by the buyer.
    /// Null if the user did not provide a billing address.
    /// </summary>
    [JsonPropertyName("billingAddress")]
    public MailingAddress? BillingAddress { get; init; }

    /// <summary>
    /// The date and time when the buyer completed the checkout.
    /// Null if the checkout has not been completed.
    /// </summary>
    [JsonPropertyName("completedAt")]
    public DateTimeOffset? CompletedAt { get; init; }

    /// <summary>
    /// The date and time when the checkout was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// A list of extra information that has been added to the checkout.
    /// </summary>
    [JsonPropertyName("customAttributes")]
    public List<Attribute> CustomAttributes { get; init; } = [];

    /// <summary>
    /// The customer who created this checkout.
    /// May be null if the checkout was created from a draft order or via an app.
    /// </summary>
    [JsonPropertyName("customer")]
    public Customer? Customer { get; init; }

    /// <summary>
    /// A default [cursor](https://shopify.dev/api/usage/pagination-graphql) that returns the single next record, sorted ascending by ID.
    /// </summary>
    [JsonPropertyName("defaultCursor")]
    public string DefaultCursor { get; init; } = null!;

    /// <summary>
    /// The discount codes entered by the buyer at checkout.
    /// </summary>
    [JsonPropertyName("discountCodes")]
    public List<string> DiscountCodes { get; init; } = [];

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// A list of the line items in this checkout.
    /// </summary>
    [JsonPropertyName("lineItems")]
    public AbandonedCheckoutLineItemConnection LineItems { get; init; } = null!;

    /// <summary>
    /// The number of products in the checkout.
    /// </summary>
    [JsonPropertyName("lineItemsQuantity")]
    public int LineItemsQuantity { get; init; }

    /// <summary>
    /// Unique merchant-facing identifier for the checkout.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// A merchant-facing note added to the checkout. Not visible to the buyer.
    /// </summary>
    [JsonPropertyName("note")]
    public string Note { get; init; } = null!;

    /// <summary>
    /// The shipping address to where the line items will be shipped.
    /// Null if the user did not provide a shipping address.
    /// </summary>
    [JsonPropertyName("shippingAddress")]
    public MailingAddress? ShippingAddress { get; init; }

    /// <summary>
    /// The sum of all items in the checkout, including discounts but excluding shipping, taxes and tips.
    /// </summary>
    [JsonPropertyName("subtotalPriceSet")]
    public MoneyBag SubtotalPriceSet { get; init; } = null!;

    /// <summary>
    /// Individual taxes charged on the checkout.
    /// </summary>
    [JsonPropertyName("taxLines")]
    public List<TaxLine> TaxLines { get; init; } = [];

    /// <summary>
    /// Whether taxes are included in line item and shipping line prices.
    /// </summary>
    [JsonPropertyName("taxesIncluded")]
    public bool TaxesIncluded { get; init; }

    /// <summary>
    /// The total amount of discounts to be applied.
    /// </summary>
    [JsonPropertyName("totalDiscountSet")]
    public MoneyBag TotalDiscountSet { get; init; } = null!;

    /// <summary>
    /// The total duties applied to the checkout.
    /// </summary>
    [JsonPropertyName("totalDutiesSet")]
    public MoneyBag? TotalDutiesSet { get; init; }

    /// <summary>
    /// The sum of the prices of all line items in the checkout.
    /// </summary>
    [JsonPropertyName("totalLineItemsPriceSet")]
    public MoneyBag TotalLineItemsPriceSet { get; init; } = null!;

    /// <summary>
    /// The sum of all items in the checkout, including discounts, shipping, taxes, and tips.
    /// </summary>
    [JsonPropertyName("totalPriceSet")]
    public MoneyBag TotalPriceSet { get; init; } = null!;

    /// <summary>
    /// The total tax applied to the checkout.
    /// </summary>
    [JsonPropertyName("totalTaxSet")]
    public MoneyBag? TotalTaxSet { get; init; }

    /// <summary>
    /// The date and time when the checkout was most recently updated.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateTimeOffset UpdatedAt { get; init; }

}
