// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A Shopify application that extends store functionality. Apps integrate with Shopify through APIs to add features, automate workflows, or connect external services.
/// 
/// Provides metadata about the app including its developer information and listing details in the Shopify App Store. Use the [`installation`](https://shopify.dev/docs/api/admin-graphql/latest/objects/App#field-App.fields.installation) field to determine if the app is currently installed on the shop and access installation-specific details like granted [`AccessScope`](https://shopify.dev/docs/api/admin-graphql/latest/objects/AccessScope) objects. Check [`failedRequirements`](https://shopify.dev/docs/api/admin-graphql/latest/objects/App#field-App.fields.failedRequirements) before installation to identify any prerequisites that must be met.
/// </summary>
public sealed partial class App : Node
{
    /// <summary>
    /// A unique application API identifier.
    /// </summary>
    [JsonPropertyName("apiKey")]
    public string ApiKey { get; init; } = null!;

    /// <summary>
    /// App store page URL of the app.
    /// </summary>
    [JsonPropertyName("appStoreAppUrl")]
    public Uri? AppStoreAppUrl { get; init; }

    /// <summary>
    /// App store page URL of the developer who created the app.
    /// </summary>
    [JsonPropertyName("appStoreDeveloperUrl")]
    public Uri? AppStoreDeveloperUrl { get; init; }

    /// <summary>
    /// All requestable access scopes available to the app.
    /// </summary>
    [JsonPropertyName("availableAccessScopes")]
    public List<AccessScope> AvailableAccessScopes { get; init; } = [];

    /// <summary>
    /// Banner image for the app.
    /// </summary>
    [JsonPropertyName("banner")]
    public Image Banner { get; init; } = null!;

    /// <summary>
    /// Description of the app.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// The name of the app developer.
    /// </summary>
    [JsonPropertyName("developerName")]
    public string? DeveloperName { get; init; }

    /// <summary>
    /// The type of app developer.
    /// </summary>
    [JsonPropertyName("developerType")]
    public AppDeveloperType DeveloperType { get; init; }

    /// <summary>
    /// Website of the developer who created the app.
    /// </summary>
    [JsonPropertyName("developerUrl")]
    public Uri DeveloperUrl { get; init; } = null!;

    /// <summary>
    /// Whether the app uses the Embedded App SDK.
    /// </summary>
    [JsonPropertyName("embedded")]
    public bool Embedded { get; init; }

    /// <summary>
    /// Requirements that must be met before the app can be installed.
    /// </summary>
    [JsonPropertyName("failedRequirements")]
    public List<FailedRequirement> FailedRequirements { get; init; } = [];

    /// <summary>
    /// A list of app features that are shown in the Shopify App Store listing.
    /// </summary>
    [JsonPropertyName("features")]
    public List<string> Features { get; init; } = [];

    /// <summary>
    /// Feedback from this app about the store.
    /// </summary>
    [JsonPropertyName("feedback")]
    public AppFeedback? Feedback { get; init; }

    /// <summary>
    /// Handle of the app.
    /// </summary>
    [JsonPropertyName("handle")]
    public string? Handle { get; init; }

    /// <summary>
    /// Icon that represents the app.
    /// </summary>
    [JsonPropertyName("icon")]
    public Image Icon { get; init; } = null!;

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Webpage where you can install the app, if app requires explicit user permission.
    /// </summary>
    [JsonPropertyName("installUrl")]
    public Uri? InstallUrl { get; init; }

    /// <summary>
    /// Corresponding AppInstallation for this shop and App.
    /// Returns null if the App is not installed.
    /// </summary>
    [JsonPropertyName("installation")]
    public AppInstallation? Installation { get; init; }

    /// <summary>
    /// Whether the app is the [post purchase](https://shopify.dev/apps/checkout/post-purchase) app in use.
    /// </summary>
    [JsonPropertyName("isPostPurchaseAppInUse")]
    public bool IsPostPurchaseAppInUse { get; init; }

    /// <summary>
    /// Webpage that the app starts in.
    /// </summary>
    [JsonPropertyName("launchUrl")]
    public Uri LaunchUrl { get; init; } = null!;

    /// <summary>
    /// Menu items for the app, which also appear as submenu items in left navigation sidebar in the Shopify admin.
    /// </summary>
    [JsonPropertyName("navigationItems")]
    public List<NavigationItem> NavigationItems { get; init; } = [];

    /// <summary>
    /// The optional scopes requested by the app. Lists the optional access scopes the app has declared in its configuration. These scopes are optionally requested by the app after installation.
    /// </summary>
    [JsonPropertyName("optionalAccessScopes")]
    public List<AccessScope> OptionalAccessScopes { get; init; } = [];

    /// <summary>
    /// Whether the app was previously installed on the current shop.
    /// </summary>
    [JsonPropertyName("previouslyInstalled")]
    public bool PreviouslyInstalled { get; init; }

    /// <summary>
    /// Detailed information about the app pricing.
    /// </summary>
    [JsonPropertyName("pricingDetails")]
    public string? PricingDetails { get; init; }

    /// <summary>
    /// Summary of the app pricing details.
    /// </summary>
    [JsonPropertyName("pricingDetailsSummary")]
    public string PricingDetailsSummary { get; init; } = null!;

    /// <summary>
    /// Link to app privacy policy.
    /// </summary>
    [JsonPropertyName("privacyPolicyUrl")]
    public Uri? PrivacyPolicyUrl { get; init; }

    /// <summary>
    /// The public category for the app.
    /// </summary>
    [JsonPropertyName("publicCategory")]
    public AppPublicCategory PublicCategory { get; init; }

    /// <summary>
    /// Whether the app is published to the Shopify App Store.
    /// </summary>
    [JsonPropertyName("published")]
    public bool Published { get; init; }

    /// <summary>
    /// The access scopes requested by the app. Lists the access scopes the app has declared in its configuration. Merchant must grant approval to these scopes for the app to be installed.
    /// </summary>
    [JsonPropertyName("requestedAccessScopes")]
    public List<AccessScope> RequestedAccessScopes { get; init; } = [];

    /// <summary>
    /// Screenshots of the app.
    /// </summary>
    [JsonPropertyName("screenshots")]
    public List<Image> Screenshots { get; init; } = [];

    /// <summary>
    /// Whether the app was developed by Shopify.
    /// </summary>
    [JsonPropertyName("shopifyDeveloped")]
    public bool ShopifyDeveloped { get; init; }

    /// <summary>
    /// Name of the app.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = null!;

    /// <summary>
    /// Message that appears when the app is uninstalled. For example:
    /// By removing this app, you will no longer be able to publish products to MySocialSite or view this app in your Shopify admin. You can re-enable this channel at any time.
    /// </summary>
    [JsonPropertyName("uninstallMessage")]
    public string UninstallMessage { get; init; } = null!;

    /// <summary>
    /// Webpage where you can uninstall the app.
    /// </summary>
    [JsonPropertyName("uninstallUrl")]
    public Uri? UninstallUrl { get; init; }

    /// <summary>
    /// The webhook API version for the app.
    /// </summary>
    [JsonPropertyName("webhookApiVersion")]
    public string WebhookApiVersion { get; init; } = null!;

}
