// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `bulkOperationRunMutation` mutation.
/// </summary>
public sealed partial class BulkOperationRunMutationPayload
{
    /// <summary>
    /// The newly created bulk operation.
    /// </summary>
    [JsonPropertyName("bulkOperation")]
    public BulkOperation? BulkOperation { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<BulkMutationUserError> UserErrors { get; init; } = [];

}
