// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A calculated return.
/// </summary>
public sealed partial class CalculatedReturn
{
    /// <summary>
    /// A list of calculated exchange line items.
    /// </summary>
    [JsonPropertyName("exchangeLineItems")]
    public List<CalculatedExchangeLineItem> ExchangeLineItems { get; init; } = [];

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// A list of calculated return line items.
    /// </summary>
    [JsonPropertyName("returnLineItems")]
    public List<CalculatedReturnLineItem> ReturnLineItems { get; init; } = [];

    /// <summary>
    /// The calculated return shipping fee.
    /// </summary>
    [JsonPropertyName("returnShippingFee")]
    public CalculatedReturnShippingFee? ReturnShippingFee { get; init; }

}
