// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// An authenticated link to an external platform that supports syndication and optionally order ingestion, such as Facebook, Pinterest, an online store, or Point of Sale (POS).
/// 
/// Each channel provides access to its underlying [`App`](https://shopify.dev/docs/api/admin-graphql/latest/objects/App), published products and collections, and [`Publication`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Publication) settings, as well as what features of the platform it supports such as [scheduled publishing](https://shopify.dev/docs/apps/build/sales-channels/scheduled-product-publishing). Use channels to manage where catalog items appear, track publication status across platforms, and control [`Product`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Product) visibility for different customer touchpoints.
/// </summary>
public sealed partial class Channel : Node
{
    /// <summary>
    /// The underlying app used by the channel.
    /// </summary>
    [JsonPropertyName("app")]
    public App App { get; init; } = null!;

    /// <summary>
    /// The list of collection publications. Each record represents information about the publication of a collection.
    /// </summary>
    [JsonPropertyName("collectionPublicationsV3")]
    public ResourcePublicationConnection CollectionPublicationsV3 { get; init; } = null!;

    /// <summary>
    /// The list of collections published to the channel.
    /// </summary>
    [JsonPropertyName("collections")]
    public CollectionConnection Collections { get; init; } = null!;

    /// <summary>
    /// The unique identifier for the channel.
    /// </summary>
    [JsonPropertyName("handle")]
    public string Handle { get; init; } = null!;

    /// <summary>
    /// Whether the collection is available to the channel.
    /// </summary>
    [JsonPropertyName("hasCollection")]
    public bool HasCollection { get; init; }

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The name of the channel.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The menu items for the channel, which also appear as submenu items in the left navigation sidebar in the Shopify admin.
    /// </summary>
    [JsonPropertyName("navigationItems")]
    public List<NavigationItem> NavigationItems { get; init; } = [];

    /// <summary>
    /// Home page for the channel.
    /// </summary>
    [JsonPropertyName("overviewPath")]
    public Uri? OverviewPath { get; init; }

    /// <summary>
    /// The product publications for the products published to the channel.
    /// </summary>
    [JsonPropertyName("productPublications")]
    public ProductPublicationConnection ProductPublications { get; init; } = null!;

    /// <summary>
    /// The list of product publication records for products published to this channel.
    /// </summary>
    [JsonPropertyName("productPublicationsV3")]
    public ResourcePublicationConnection ProductPublicationsV3 { get; init; } = null!;

    /// <summary>
    /// The list of products published to the channel.
    /// </summary>
    [JsonPropertyName("products")]
    public ProductConnection Products { get; init; } = null!;

    /// <summary>
    /// Retrieves the total count of [`products`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Product) published to a specific sales channel. Limited to a maximum of 10000 by default.
    /// </summary>
    [JsonPropertyName("productsCount")]
    public Count? ProductsCount { get; init; }

    /// <summary>
    /// Whether the channel supports future publishing.
    /// </summary>
    [JsonPropertyName("supportsFuturePublishing")]
    public bool SupportsFuturePublishing { get; init; }

}
