// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The design system allows you to set values that represent specific attributes
/// of your brand like color and font. These attributes are used throughout the user
/// interface. This brings consistency and allows you to easily make broad design changes.
/// </summary>
public sealed partial class CheckoutBrandingDesignSystem
{
    /// <summary>
    /// The color settings for global colors and color schemes.
    /// </summary>
    [JsonPropertyName("colors")]
    public CheckoutBrandingColors? Colors { get; init; }

    /// <summary>
    /// The corner radius variables.
    /// </summary>
    [JsonPropertyName("cornerRadius")]
    public CheckoutBrandingCornerRadiusVariables? CornerRadius { get; init; }

    /// <summary>
    /// The typography.
    /// </summary>
    [JsonPropertyName("typography")]
    public CheckoutBrandingTypography? Typography { get; init; }

}
