// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The customizations that apply to specific components or areas of the user interface.
/// </summary>
public sealed partial class CheckoutBrandingCustomizations
{
    /// <summary>
    /// The customizations for the breadcrumbs that represent a buyer's journey to the checkout.
    /// </summary>
    [JsonPropertyName("buyerJourney")]
    public CheckoutBrandingBuyerJourney? BuyerJourney { get; init; }

    /// <summary>
    /// The checkout cart link customizations. For example, by setting the visibility field to `HIDDEN`, you can hide the cart icon in the header for one-page checkout, and the cart link in breadcrumbs in three-page checkout.
    /// </summary>
    [JsonPropertyName("cartLink")]
    public CheckoutBrandingCartLink? CartLink { get; init; }

    /// <summary>
    /// The checkboxes customizations.
    /// </summary>
    [JsonPropertyName("checkbox")]
    public CheckoutBrandingCheckbox? Checkbox { get; init; }

    /// <summary>
    /// The choice list customizations.
    /// </summary>
    [JsonPropertyName("choiceList")]
    public CheckoutBrandingChoiceList? ChoiceList { get; init; }

    /// <summary>
    /// The content container customizations.
    /// </summary>
    [JsonPropertyName("content")]
    public CheckoutBrandingContent? Content { get; init; }

    /// <summary>
    /// The form controls customizations.
    /// </summary>
    [JsonPropertyName("control")]
    public CheckoutBrandingControl? Control { get; init; }

    /// <summary>
    /// The customizations for the page, content, main, and order summary dividers. For example, by setting the borderStyle to `DOTTED`, you can make these dividers render as dotted lines.
    /// </summary>
    [JsonPropertyName("divider")]
    public CheckoutBrandingDividerStyle? Divider { get; init; }

    /// <summary>
    /// The express checkout customizations.
    /// </summary>
    [JsonPropertyName("expressCheckout")]
    public CheckoutBrandingExpressCheckout? ExpressCheckout { get; init; }

    /// <summary>
    /// The favicon image.
    /// </summary>
    [JsonPropertyName("favicon")]
    public CheckoutBrandingImage? Favicon { get; init; }

    /// <summary>
    /// The footer customizations.
    /// </summary>
    [JsonPropertyName("footer")]
    public CheckoutBrandingFooter? Footer { get; init; }

    /// <summary>
    /// The global customizations.
    /// </summary>
    [JsonPropertyName("global")]
    public CheckoutBrandingGlobal? Global { get; init; }

    /// <summary>
    /// The header customizations.
    /// </summary>
    [JsonPropertyName("header")]
    public CheckoutBrandingHeader? Header { get; init; }

    /// <summary>
    /// The Heading Level 1 customizations.
    /// </summary>
    [JsonPropertyName("headingLevel1")]
    public CheckoutBrandingHeadingLevel? HeadingLevel1 { get; init; }

    /// <summary>
    /// The Heading Level 2 customizations.
    /// </summary>
    [JsonPropertyName("headingLevel2")]
    public CheckoutBrandingHeadingLevel? HeadingLevel2 { get; init; }

    /// <summary>
    /// The Heading Level 3 customizations.
    /// </summary>
    [JsonPropertyName("headingLevel3")]
    public CheckoutBrandingHeadingLevel? HeadingLevel3 { get; init; }

    /// <summary>
    /// The main area customizations.
    /// </summary>
    [JsonPropertyName("main")]
    public CheckoutBrandingMain? Main { get; init; }

    /// <summary>
    /// The merchandise thumbnails customizations.
    /// </summary>
    [JsonPropertyName("merchandiseThumbnail")]
    public CheckoutBrandingMerchandiseThumbnail? MerchandiseThumbnail { get; init; }

    /// <summary>
    /// The order summary customizations.
    /// </summary>
    [JsonPropertyName("orderSummary")]
    public CheckoutBrandingOrderSummary? OrderSummary { get; init; }

    /// <summary>
    /// The primary buttons customizations.
    /// </summary>
    [JsonPropertyName("primaryButton")]
    public CheckoutBrandingButton? PrimaryButton { get; init; }

    /// <summary>
    /// The secondary buttons customizations.
    /// </summary>
    [JsonPropertyName("secondaryButton")]
    public CheckoutBrandingButton? SecondaryButton { get; init; }

    /// <summary>
    /// The selects customizations.
    /// </summary>
    [JsonPropertyName("select")]
    public CheckoutBrandingSelect? Select { get; init; }

    /// <summary>
    /// The text fields customizations.
    /// </summary>
    [JsonPropertyName("textField")]
    public CheckoutBrandingTextField? TextField { get; init; }

}
