// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The order summary sections customizations.
/// </summary>
public sealed partial class CheckoutBrandingOrderSummarySection
{
    /// <summary>
    /// The background style of the order summary sections.
    /// </summary>
    [JsonPropertyName("background")]
    public CheckoutBrandingBackground? Background { get; init; }

    /// <summary>
    /// The border for the order summary sections.
    /// </summary>
    [JsonPropertyName("border")]
    public CheckoutBrandingSimpleBorder? Border { get; init; }

    /// <summary>
    /// The border style of the order summary sections.
    /// </summary>
    [JsonPropertyName("borderStyle")]
    public CheckoutBrandingBorderStyle? BorderStyle { get; init; }

    /// <summary>
    /// The border width of the order summary sections.
    /// </summary>
    [JsonPropertyName("borderWidth")]
    public CheckoutBrandingBorderWidth? BorderWidth { get; init; }

    /// <summary>
    /// The selected color scheme of the order summary sections.
    /// </summary>
    [JsonPropertyName("colorScheme")]
    public CheckoutBrandingColorSchemeSelection? ColorScheme { get; init; }

    /// <summary>
    /// The corner radius of the order summary sections.
    /// </summary>
    [JsonPropertyName("cornerRadius")]
    public CheckoutBrandingCornerRadius? CornerRadius { get; init; }

    /// <summary>
    /// The padding of the order summary sections.
    /// </summary>
    [JsonPropertyName("padding")]
    public CheckoutBrandingSpacingKeyword? Padding { get; init; }

    /// <summary>
    /// The shadow of the order summary sections.
    /// </summary>
    [JsonPropertyName("shadow")]
    public CheckoutBrandingShadow? Shadow { get; init; }

}
