// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Defines the color palette specifically for button elements within checkout branding, including hover states. These color roles ensure buttons maintain proper contrast and visual hierarchy throughout the checkout experience.
/// 
/// For example, a sports brand might configure bright accent colors for primary action buttons, with darker hover states and contrasting text colors that maintain accessibility standards.
/// 
/// Use the `ButtonColorRoles` object to:
/// - Define button color schemes for different states
/// - Ensure proper contrast for accessibility compliance
/// - Coordinate button colors with overall brand palette
/// 
/// Button color roles include background, border, text, icon, accent (for focused states), and decorative elements, plus specific hover state colors that provide clear interactive feedback to customers.
/// </summary>
public sealed partial class CheckoutBrandingButtonColorRoles
{
    /// <summary>
    /// The color of accented objects (links and focused state).
    /// </summary>
    [JsonPropertyName("accent")]
    public string? Accent { get; init; }

    /// <summary>
    /// The color of the background.
    /// </summary>
    [JsonPropertyName("background")]
    public string? Background { get; init; }

    /// <summary>
    /// The color of borders.
    /// </summary>
    [JsonPropertyName("border")]
    public string? Border { get; init; }

    /// <summary>
    /// The decorative color for highlighting specific parts of the user interface.
    /// </summary>
    [JsonPropertyName("decorative")]
    public string? Decorative { get; init; }

    /// <summary>
    /// The colors of the button on hover.
    /// </summary>
    [JsonPropertyName("hover")]
    public CheckoutBrandingColorRoles? Hover { get; init; }

    /// <summary>
    /// The color of icons.
    /// </summary>
    [JsonPropertyName("icon")]
    public string? Icon { get; init; }

    /// <summary>
    /// The color of text.
    /// </summary>
    [JsonPropertyName("text")]
    public string? Text { get; init; }

}
