// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents at rule that's used to assign products to a collection.
/// </summary>
public sealed partial class CollectionRule
{
    /// <summary>
    /// The attribute that the rule focuses on. For example, `title` or `product_type`.
    /// </summary>
    [JsonPropertyName("column")]
    public CollectionRuleColumn Column { get; init; }

    /// <summary>
    /// The value that the operator is applied to. For example, `Hats`.
    /// </summary>
    [JsonPropertyName("condition")]
    public string Condition { get; init; } = null!;

    /// <summary>
    /// The value that the operator is applied to.
    /// </summary>
    [JsonPropertyName("conditionObject")]
    public CollectionRuleConditionObject? ConditionObject { get; init; }

    /// <summary>
    /// The type of operator that the rule is based on. For example, `equals`, `contains`, or `not_equals`.
    /// </summary>
    [JsonPropertyName("relation")]
    public CollectionRuleRelation Relation { get; init; }

}
