// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Specifies the taxonomy category to used for the condition.
/// </summary>
public sealed partial class CollectionRuleCategoryCondition
{
    /// <summary>
    /// The taxonomy category used as condition.
    /// </summary>
    [JsonPropertyName("value")]
    public TaxonomyCategory Value { get; init; } = null!;

}
