// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `collectionPublish` mutation.
/// </summary>
public sealed partial class CollectionPublishPayload
{
    /// <summary>
    /// The published collection.
    /// </summary>
    [JsonPropertyName("collection")]
    public Collection? Collection { get; init; }

    /// <summary>
    /// The channels where the collection has been published.
    /// </summary>
    [JsonPropertyName("collectionPublications")]
    public List<CollectionPublication>? CollectionPublications { get; init; }

    /// <summary>
    /// The shop associated with the collection.
    /// </summary>
    [JsonPropertyName("shop")]
    public Shop Shop { get; init; } = null!;

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
