// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `collectionDelete` mutation.
/// </summary>
public sealed partial class CollectionDeletePayload
{
    /// <summary>
    /// The ID of the collection that was deleted. Returns `null` if the collection doesn't exist.
    /// </summary>
    [JsonPropertyName("deletedCollectionId")]
    public string? DeletedCollectionId { get; init; }

    /// <summary>
    /// The shop associated with the collection.
    /// </summary>
    [JsonPropertyName("shop")]
    public Shop Shop { get; init; } = null!;

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
