// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A child of a combined listing.
/// </summary>
public sealed partial class CombinedListingChild
{
    /// <summary>
    /// The parent variant.
    /// </summary>
    [JsonPropertyName("parentVariant")]
    public ProductVariant ParentVariant { get; init; } = null!;

    /// <summary>
    /// The child product.
    /// </summary>
    [JsonPropertyName("product")]
    public Product Product { get; init; } = null!;

}
