// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `combinedListingUpdate` mutation.
/// </summary>
public sealed partial class CombinedListingUpdatePayload
{
    /// <summary>
    /// The parent product.
    /// </summary>
    [JsonPropertyName("product")]
    public Product? Product { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<CombinedListingUpdateUserError> UserErrors { get; init; } = [];

}
