// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A comment that staff members add to the timeline of [`Order`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Order), [`DraftOrder`](https://shopify.dev/docs/api/admin-graphql/latest/objects/DraftOrder), [`Customer`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Customer), [`InventoryTransfer`](https://shopify.dev/docs/api/admin-graphql/latest/objects/InventoryTransfer), [`Company`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Company), [`CompanyLocation`](https://shopify.dev/docs/api/admin-graphql/latest/objects/CompanyLocation), or [`PriceRule`](https://shopify.dev/docs/api/admin-graphql/latest/objects/PriceRule) objects. Staff use comments to document internal notes, communicate with team members, and track important information about these types.
/// 
/// The comment includes information like the [`StaffMember`](https://shopify.dev/docs/api/admin-graphql/latest/objects/StaffMember) who authored it, when it was created, and whether it's editable or deletable. Comments can have file attachments and reference related objects like [`Product`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Product) or [`ProductVariant`](https://shopify.dev/docs/api/admin-graphql/latest/objects/ProductVariant) objects through embeds.
/// </summary>
public sealed partial class CommentEvent : Event, Node
{
    /// <summary>
    /// The action that occured.
    /// </summary>
    [JsonPropertyName("action")]
    public string Action { get; init; } = null!;

    /// <summary>
    /// The name of the app that created the event.
    /// </summary>
    [JsonPropertyName("appTitle")]
    public string? AppTitle { get; init; }

    /// <summary>
    /// The attachments associated with the comment event.
    /// </summary>
    [JsonPropertyName("attachments")]
    public List<CommentEventAttachment> Attachments { get; init; } = [];

    /// <summary>
    /// Whether the event was created by an app.
    /// </summary>
    [JsonPropertyName("attributeToApp")]
    public bool AttributeToApp { get; init; }

    /// <summary>
    /// Whether the event was caused by an admin user.
    /// </summary>
    [JsonPropertyName("attributeToUser")]
    public bool AttributeToUser { get; init; }

    /// <summary>
    /// The name of the user that authored the comment event.
    /// </summary>
    [JsonPropertyName("author")]
    public StaffMember Author { get; init; } = null!;

    /// <summary>
    /// Whether the comment event can be deleted. If true, then the comment event can be deleted.
    /// </summary>
    [JsonPropertyName("canDelete")]
    public bool CanDelete { get; init; }

    /// <summary>
    /// Whether the comment event can be edited. If true, then the comment event can be edited.
    /// </summary>
    [JsonPropertyName("canEdit")]
    public bool CanEdit { get; init; }

    /// <summary>
    /// The date and time when the event was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// Whether the event is critical.
    /// </summary>
    [JsonPropertyName("criticalAlert")]
    public bool CriticalAlert { get; init; }

    /// <summary>
    /// Whether the comment event has been edited. If true, then the comment event has been edited.
    /// </summary>
    [JsonPropertyName("edited")]
    public bool Edited { get; init; }

    /// <summary>
    /// The object reference associated with the comment event. For example, a product or discount).
    /// </summary>
    [JsonPropertyName("embed")]
    public CommentEventEmbed? Embed { get; init; }

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Human readable text that describes the event.
    /// </summary>
    [JsonPropertyName("message")]
    public string Message { get; init; } = null!;

    /// <summary>
    /// The raw body of the comment event.
    /// </summary>
    [JsonPropertyName("rawMessage")]
    public string RawMessage { get; init; } = null!;

    /// <summary>
    /// The parent subject to which the comment event belongs.
    /// </summary>
    [JsonPropertyName("subject")]
    public CommentEventSubject? Subject { get; init; }

}
