// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `companyLocationTaxSettingsUpdate` mutation.
/// </summary>
public sealed partial class CompanyLocationTaxSettingsUpdatePayload
{
    /// <summary>
    /// The company location with the updated tax settings.
    /// </summary>
    [JsonPropertyName("companyLocation")]
    public CompanyLocation? CompanyLocation { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<BusinessCustomerUserError> UserErrors { get; init; } = [];

}
