// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A business entity that purchases from the shop as part of B2B commerce. Companies organize multiple locations and contacts who can place orders on behalf of the organization. [`CompanyLocation`](https://shopify.dev/docs/api/admin-graphql/latest/objects/CompanyLocation) objects can have custom pricing through [`Catalog`](https://shopify.dev/docs/api/admin-graphql/latest/interfaces/Catalog) and [`PriceList`](https://shopify.dev/docs/api/admin-graphql/latest/objects/PriceList) configurations.
/// </summary>
public sealed partial class Company : CommentEventSubject, HasEvents, HasMetafieldDefinitions, HasMetafields, Navigable, Node
{
    /// <summary>
    /// The number of contacts that belong to the company.
    /// </summary>
    [JsonPropertyName("contactCount")]
    public int ContactCount { get; init; }

    /// <summary>
    /// The list of roles for the company contacts.
    /// </summary>
    [JsonPropertyName("contactRoles")]
    public CompanyContactRoleConnection ContactRoles { get; init; } = null!;

    /// <summary>
    /// The list of contacts in the company.
    /// </summary>
    [JsonPropertyName("contacts")]
    public CompanyContactConnection Contacts { get; init; } = null!;

    /// <summary>
    /// The number of contacts that belong to the company.
    /// </summary>
    [JsonPropertyName("contactsCount")]
    public Count? ContactsCount { get; init; }

    /// <summary>
    /// The date and time ([ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601)) at which the company was created in Shopify.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// The date and time ([ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601)) at which the company became the customer.
    /// </summary>
    [JsonPropertyName("customerSince")]
    public DateTimeOffset CustomerSince { get; init; }

    /// <summary>
    /// A default [cursor](https://shopify.dev/api/usage/pagination-graphql) that returns the single next record, sorted ascending by ID.
    /// </summary>
    [JsonPropertyName("defaultCursor")]
    public string DefaultCursor { get; init; } = null!;

    /// <summary>
    /// The role proposed by default for a contact at the company.
    /// </summary>
    [JsonPropertyName("defaultRole")]
    public CompanyContactRole? DefaultRole { get; init; }

    /// <summary>
    /// The list of the company's draft orders.
    /// </summary>
    [JsonPropertyName("draftOrders")]
    public DraftOrderConnection DraftOrders { get; init; } = null!;

    /// <summary>
    /// The paginated list of events associated with the host subject.
    /// </summary>
    [JsonPropertyName("events")]
    public EventConnection Events { get; init; } = null!;

    /// <summary>
    /// A unique externally-supplied ID for the company.
    /// </summary>
    [JsonPropertyName("externalId")]
    public string? ExternalId { get; init; }

    /// <summary>
    /// Whether the merchant added a timeline comment to the company.
    /// </summary>
    [JsonPropertyName("hasTimelineComment")]
    public bool HasTimelineComment { get; init; }

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The lifetime duration of the company, since it became a customer of the shop. Examples: `2 days`, `3 months`, `1 year`.
    /// </summary>
    [JsonPropertyName("lifetimeDuration")]
    public string LifetimeDuration { get; init; } = null!;

    /// <summary>
    /// The list of locations in the company.
    /// </summary>
    [JsonPropertyName("locations")]
    public CompanyLocationConnection Locations { get; init; } = null!;

    /// <summary>
    /// The number of locations that belong to the company.
    /// </summary>
    [JsonPropertyName("locationsCount")]
    public Count? LocationsCount { get; init; }

    /// <summary>
    /// The main contact for the company.
    /// </summary>
    [JsonPropertyName("mainContact")]
    public CompanyContact? MainContact { get; init; }

    /// <summary>
    /// A [custom field](https://shopify.dev/docs/apps/build/custom-data),
    /// including its `namespace` and `key`, that's associated with a Shopify resource
    /// for the purposes of adding and storing additional information.
    /// </summary>
    [JsonPropertyName("metafield")]
    public Metafield? Metafield { get; init; }

    /// <summary>
    /// List of metafield definitions.
    /// </summary>
    [JsonPropertyName("metafieldDefinitions")]
    public MetafieldDefinitionConnection MetafieldDefinitions { get; init; } = null!;

    /// <summary>
    /// A list of [custom fields](https://shopify.dev/docs/apps/build/custom-data)
    /// that a merchant associates with a Shopify resource.
    /// </summary>
    [JsonPropertyName("metafields")]
    public MetafieldConnection Metafields { get; init; } = null!;

    /// <summary>
    /// The name of the company.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// A note about the company.
    /// </summary>
    [JsonPropertyName("note")]
    public string? Note { get; init; }

    /// <summary>
    /// The list of the company's orders.
    /// </summary>
    [JsonPropertyName("orders")]
    public OrderConnection Orders { get; init; } = null!;

    /// <summary>
    /// The total number of orders placed for this company, across all its locations.
    /// </summary>
    [JsonPropertyName("ordersCount")]
    public Count? OrdersCount { get; init; }

    /// <summary>
    /// The total amount spent by this company, across all its locations.
    /// </summary>
    [JsonPropertyName("totalSpent")]
    public MoneyV2 TotalSpent { get; init; } = null!;

    /// <summary>
    /// The date and time ([ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601)) at which the company was last modified.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateTimeOffset UpdatedAt { get; init; }

}
