// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `companyContactRemoveFromCompany` mutation.
/// </summary>
public sealed partial class CompanyContactRemoveFromCompanyPayload
{
    /// <summary>
    /// The ID of the removed company contact.
    /// </summary>
    [JsonPropertyName("removedCompanyContactId")]
    public string? RemovedCompanyContactId { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<BusinessCustomerUserError> UserErrors { get; init; } = [];

}
