// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// An option selection for a bundle consolidated option.
/// </summary>
public sealed partial class ComponentizedProductsBundleConsolidatedOptionSelection
{
    /// <summary>
    /// The component values that are included in the consolidated option selection.
    /// </summary>
    [JsonPropertyName("components")]
    public List<ComponentizedProductsBundleConsolidatedOptionSelectionComponent> Components { get; init; } = [];

    /// <summary>
    /// The value of the consolidated option on the bundle parent.
    /// </summary>
    [JsonPropertyName("value")]
    public string Value { get; init; } = null!;

}
