// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A person who acts on behalf of a [`Company`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Company) to make B2B purchases. Company contacts are associated with [`Customer`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Customer) accounts and can place orders on behalf of their company.
/// 
/// Each contact can be assigned to one or more [`CompanyLocation`](https://shopify.dev/docs/api/admin-graphql/latest/objects/CompanyLocation) objects with specific roles that determine their permissions and access to catalogs, pricing, and payment terms configured for those locations.
/// </summary>
public sealed partial class CompanyContact : Node
{
    /// <summary>
    /// The company to which the contact belongs.
    /// </summary>
    [JsonPropertyName("company")]
    public Company Company { get; init; } = null!;

    /// <summary>
    /// The date and time ([ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601)) at which the company contact was created at Shopify.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// The customer associated to this contact.
    /// </summary>
    [JsonPropertyName("customer")]
    public Customer Customer { get; init; } = null!;

    /// <summary>
    /// The list of draft orders for the company contact.
    /// </summary>
    [JsonPropertyName("draftOrders")]
    public DraftOrderConnection DraftOrders { get; init; } = null!;

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Whether the contact is the main contact of the company.
    /// </summary>
    [JsonPropertyName("isMainContact")]
    public bool IsMainContact { get; init; }

    /// <summary>
    /// The lifetime duration of the company contact, since its creation date on Shopify. Examples: `1 year`, `2 months`, `3 days`.
    /// </summary>
    [JsonPropertyName("lifetimeDuration")]
    public string LifetimeDuration { get; init; } = null!;

    /// <summary>
    /// The company contact's locale (language).
    /// </summary>
    [JsonPropertyName("locale")]
    public string? Locale { get; init; }

    /// <summary>
    /// The list of orders for the company contact.
    /// </summary>
    [JsonPropertyName("orders")]
    public OrderConnection Orders { get; init; } = null!;

    /// <summary>
    /// The list of roles assigned to this company contact.
    /// </summary>
    [JsonPropertyName("roleAssignments")]
    public CompanyContactRoleAssignmentConnection RoleAssignments { get; init; } = null!;

    /// <summary>
    /// The company contact's job title.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The date and time ([ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601)) at which the company contact was last updated.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateTimeOffset UpdatedAt { get; init; }

}
