// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The fields that will be kept as part of a customer merge preview.
/// </summary>
public sealed partial class CustomerMergePreviewDefaultFields
{
    /// <summary>
    /// The merged addresses resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("addresses")]
    public MailingAddressConnection Addresses { get; init; } = null!;

    /// <summary>
    /// The default address resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("defaultAddress")]
    public MailingAddress? DefaultAddress { get; init; }

    /// <summary>
    /// The total number of customer-specific discounts resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("discountNodeCount")]
    public ulong DiscountNodeCount { get; init; }

    /// <summary>
    /// The merged customer-specific discounts resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("discountNodes")]
    public DiscountNodeConnection DiscountNodes { get; init; } = null!;

    /// <summary>
    /// The full name of the customer, based on the values for `first_name` and `last_name`. If `first_name` and `last_name` aren't available, then this field falls back to the customer's email address. If the customer's email isn't available, then this field falls back to the customer's phone number.
    /// </summary>
    [JsonPropertyName("displayName")]
    public string DisplayName { get; init; } = null!;

    /// <summary>
    /// The total number of merged draft orders.
    /// </summary>
    [JsonPropertyName("draftOrderCount")]
    public ulong DraftOrderCount { get; init; }

    /// <summary>
    /// The merged draft orders resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("draftOrders")]
    public DraftOrderConnection DraftOrders { get; init; } = null!;

    /// <summary>
    /// The email state of a customer.
    /// </summary>
    [JsonPropertyName("email")]
    public CustomerEmailAddress? Email { get; init; }

    /// <summary>
    /// The first name resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("firstName")]
    public string? FirstName { get; init; }

    /// <summary>
    /// The total number of merged gift cards.
    /// </summary>
    [JsonPropertyName("giftCardCount")]
    public ulong GiftCardCount { get; init; }

    /// <summary>
    /// The merged gift cards resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("giftCards")]
    public GiftCardConnection GiftCards { get; init; } = null!;

    /// <summary>
    /// The last name resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("lastName")]
    public string? LastName { get; init; }

    /// <summary>
    /// The total number of merged metafields.
    /// </summary>
    [JsonPropertyName("metafieldCount")]
    public ulong MetafieldCount { get; init; }

    /// <summary>
    /// The merged note resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("note")]
    public string? Note { get; init; }

    /// <summary>
    /// The total number of merged orders.
    /// </summary>
    [JsonPropertyName("orderCount")]
    public ulong OrderCount { get; init; }

    /// <summary>
    /// The merged orders resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("orders")]
    public OrderConnection Orders { get; init; } = null!;

    /// <summary>
    /// The phone number state of a customer.
    /// </summary>
    [JsonPropertyName("phoneNumber")]
    public CustomerPhoneNumber? PhoneNumber { get; init; }

    /// <summary>
    /// The merged tags resulting from a customer merge.
    /// </summary>
    [JsonPropertyName("tags")]
    public List<string> Tags { get; init; } = [];

}
