// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents a PayPal instrument for customer payment method.
/// </summary>
public sealed partial class CustomerPaypalBillingAgreement
{
    /// <summary>
    /// The billing address of this payment method.
    /// </summary>
    [JsonPropertyName("billingAddress")]
    public CustomerPaymentInstrumentBillingAddress? BillingAddress { get; init; }

    /// <summary>
    /// Whether the PayPal billing agreement is inactive.
    /// </summary>
    [JsonPropertyName("inactive")]
    public bool Inactive { get; init; }

    /// <summary>
    /// Whether the payment method can be revoked.The payment method can be revoked if there are no active subscription contracts.
    /// </summary>
    [JsonPropertyName("isRevocable")]
    public bool IsRevocable { get; init; }

    /// <summary>
    /// The customers's PayPal account email address.
    /// </summary>
    [JsonPropertyName("paypalAccountEmail")]
    public string? PaypalAccountEmail { get; init; }

}
