// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A native page for the customer account navigation menu.
/// </summary>
public sealed partial class CustomerAccountNativePage : CustomerAccountPage, Navigable, Node
{
    /// <summary>
    /// A default [cursor](https://shopify.dev/api/usage/pagination-graphql) that returns the single next record, sorted ascending by ID.
    /// </summary>
    [JsonPropertyName("defaultCursor")]
    public string DefaultCursor { get; init; } = null!;

    /// <summary>
    /// A unique, human-friendly string for the customer account page.
    /// </summary>
    [JsonPropertyName("handle")]
    public string Handle { get; init; } = null!;

    /// <summary>
    /// The unique ID for the customer account page.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The type of customer account native page.
    /// </summary>
    [JsonPropertyName("pageType")]
    public CustomerAccountNativePagePageType PageType { get; init; }

    /// <summary>
    /// The title of the customer account page.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = null!;

}
