// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `delegateAccessTokenCreate` mutation.
/// </summary>
public sealed partial class DelegateAccessTokenCreatePayload
{
    /// <summary>
    /// The delegate access token.
    /// </summary>
    [JsonPropertyName("delegateAccessToken")]
    public DelegateAccessToken? DelegateAccessToken { get; init; }

    /// <summary>
    /// The user's shop.
    /// </summary>
    [JsonPropertyName("shop")]
    public Shop Shop { get; init; } = null!;

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<DelegateAccessTokenCreateUserError> UserErrors { get; init; } = [];

}
