// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A location group is a collection of locations. They share zones and delivery methods across delivery
/// profiles.
/// </summary>
public sealed partial class DeliveryLocationGroup : Node
{
    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// A list of all locations that are part of this location group.
    /// </summary>
    [JsonPropertyName("locations")]
    public LocationConnection Locations { get; init; } = null!;

    /// <summary>
    /// A count of all locations that are part of this location group.
    /// </summary>
    [JsonPropertyName("locationsCount")]
    public Count? LocationsCount { get; init; }

}
