// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `deliveryCustomizationCreate` mutation.
/// </summary>
public sealed partial class DeliveryCustomizationCreatePayload
{
    /// <summary>
    /// Returns the created delivery customization.
    /// </summary>
    [JsonPropertyName("deliveryCustomization")]
    public DeliveryCustomization? DeliveryCustomization { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<DeliveryCustomizationError> UserErrors { get; init; } = [];

}
