// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Creates percentage-based discounts that reduce item prices by a specified percentage amount. This gives merchants a flexible way to offer proportional savings that automatically scale with order value.
/// 
/// For example, a "20% off all winter clothing" promotion would use this object to apply consistent percentage savings across different price points.
/// 
/// Learn more about [discount types](https://help.shopify.com/manual/discounts/).
/// </summary>
public sealed partial class DiscountPercentage
{
    /// <summary>
    /// The percentage value of the discount.
    /// </summary>
    [JsonPropertyName("percentage")]
    public double Percentage { get; init; }

}
