// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The minimum subtotal required for the discount to apply.
/// </summary>
public sealed partial class DiscountMinimumSubtotal
{
    /// <summary>
    /// The minimum subtotal that's required for the discount to be applied.
    /// </summary>
    [JsonPropertyName("greaterThanOrEqualToSubtotal")]
    public MoneyV2 GreaterThanOrEqualToSubtotal { get; init; } = null!;

}
