// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `discountAutomaticActivate` mutation.
/// </summary>
public sealed partial class DiscountAutomaticActivatePayload
{
    /// <summary>
    /// The activated automatic discount.
    /// </summary>
    [JsonPropertyName("automaticDiscountNode")]
    public DiscountAutomaticNode? AutomaticDiscountNode { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<DiscountUserError> UserErrors { get; init; } = [];

}
