// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `discountCodeBasicCreate` mutation.
/// </summary>
public sealed partial class DiscountCodeBasicCreatePayload
{
    /// <summary>
    /// The discount code that was created.
    /// </summary>
    [JsonPropertyName("codeDiscountNode")]
    public DiscountCodeNode? CodeDiscountNode { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<DiscountUserError> UserErrors { get; init; } = [];

}
