// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The available delivery options for a draft order.
/// </summary>
public sealed partial class DraftOrderAvailableDeliveryOptions
{
    /// <summary>
    /// The available local delivery rates for the draft order. Requires a customer with a valid shipping address and at least one line item.
    /// </summary>
    [JsonPropertyName("availableLocalDeliveryRates")]
    public List<DraftOrderShippingRate> AvailableLocalDeliveryRates { get; init; } = [];

    /// <summary>
    /// The available local pickup options for the draft order. Requires at least one line item.
    /// </summary>
    [JsonPropertyName("availableLocalPickupOptions")]
    public List<PickupInStoreLocation> AvailableLocalPickupOptions { get; init; } = [];

    /// <summary>
    /// The available shipping rates for the draft order. Requires a customer with a valid shipping address and at least one line item.
    /// </summary>
    [JsonPropertyName("availableShippingRates")]
    public List<DraftOrderShippingRate> AvailableShippingRates { get; init; } = [];

    /// <summary>
    /// Returns information about pagination of local pickup options.
    /// </summary>
    [JsonPropertyName("pageInfo")]
    public PageInfo PageInfo { get; init; } = null!;

}
