// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// New items associated to the exchange.
/// </summary>
public sealed partial class ExchangeV2Additions
{
    /// <summary>
    /// The list of new items for the exchange.
    /// </summary>
    [JsonPropertyName("lineItems")]
    public List<ExchangeV2LineItem> LineItems { get; init; } = [];

    /// <summary>
    /// The subtotal of the items being added, including discounts.
    /// </summary>
    [JsonPropertyName("subtotalPriceSet")]
    public MoneyBag SubtotalPriceSet { get; init; } = null!;

    /// <summary>
    /// The summary of all taxes of the items being added.
    /// </summary>
    [JsonPropertyName("taxLines")]
    public List<TaxLine> TaxLines { get; init; } = [];

    /// <summary>
    /// The total price of the items being added, including discounts and taxes.
    /// </summary>
    [JsonPropertyName("totalPriceSet")]
    public MoneyBag TotalPriceSet { get; init; } = null!;

}
