// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A shipment of one or more items from an [`Order`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Order). Tracks which [`LineItem`](https://shopify.dev/docs/api/admin-graphql/latest/objects/LineItem) objects ship, their quantities, and the shipment's tracking information.
/// 
/// Includes tracking details such as the carrier, tracking numbers, and URLs. The fulfillment connects to both the original order and any associated [`FulfillmentOrder`](https://shopify.dev/docs/api/admin-graphql/latest/objects/FulfillmentOrder) objects. [`FulfillmentEvent`](https://shopify.dev/docs/api/admin-graphql/latest/objects/FulfillmentEvent) objects record milestones throughout the shipment lifecycle, from creation through delivery.
/// 
/// Multiple fulfillments can exist for a single order when items either ship separately or from different locations.
/// </summary>
public sealed partial class Fulfillment : LegacyInteroperability, Node
{
    /// <summary>
    /// The date and time when the fulfillment was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// The date that this fulfillment was delivered.
    /// </summary>
    [JsonPropertyName("deliveredAt")]
    public DateTimeOffset? DeliveredAt { get; init; }

    /// <summary>
    /// Human readable display status for this fulfillment.
    /// </summary>
    [JsonPropertyName("displayStatus")]
    public FulfillmentDisplayStatus? DisplayStatus { get; init; }

    /// <summary>
    /// The estimated date that this fulfillment will arrive.
    /// </summary>
    [JsonPropertyName("estimatedDeliveryAt")]
    public DateTimeOffset? EstimatedDeliveryAt { get; init; }

    /// <summary>
    /// The history of events associated with this fulfillment.
    /// </summary>
    [JsonPropertyName("events")]
    public FulfillmentEventConnection Events { get; init; } = null!;

    /// <summary>
    /// List of the fulfillment's line items.
    /// </summary>
    [JsonPropertyName("fulfillmentLineItems")]
    public FulfillmentLineItemConnection FulfillmentLineItems { get; init; } = null!;

    /// <summary>
    /// A paginated list of fulfillment orders for the fulfillment.
    /// </summary>
    [JsonPropertyName("fulfillmentOrders")]
    public FulfillmentOrderConnection FulfillmentOrders { get; init; } = null!;

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The date and time when the fulfillment went into transit.
    /// </summary>
    [JsonPropertyName("inTransitAt")]
    public DateTimeOffset? InTransitAt { get; init; }

    /// <summary>
    /// The ID of the corresponding resource in the REST Admin API.
    /// </summary>
    [JsonPropertyName("legacyResourceId")]
    public ulong LegacyResourceId { get; init; }

    /// <summary>
    /// The location that the fulfillment was processed at.
    /// </summary>
    [JsonPropertyName("location")]
    public Location? Location { get; init; }

    /// <summary>
    /// Human readable reference identifier for this fulfillment.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The order for which the fulfillment was created.
    /// </summary>
    [JsonPropertyName("order")]
    public Order Order { get; init; } = null!;

    /// <summary>
    /// The address at which the fulfillment occurred. This field is intended for tax purposes, as a full address is required for tax providers to accurately calculate taxes. Typically this is the address of the warehouse or fulfillment center. To retrieve a fulfillment location's address, use the `assignedLocation` field on the [`FulfillmentOrder`](/docs/api/admin-graphql/latest/objects/FulfillmentOrder) object instead.
    /// </summary>
    [JsonPropertyName("originAddress")]
    public FulfillmentOriginAddress? OriginAddress { get; init; }

    /// <summary>
    /// Whether any of the line items in the fulfillment require shipping.
    /// </summary>
    [JsonPropertyName("requiresShipping")]
    public bool RequiresShipping { get; init; }

    /// <summary>
    /// Fulfillment service associated with the fulfillment.
    /// </summary>
    [JsonPropertyName("service")]
    public FulfillmentService? Service { get; init; }

    /// <summary>
    /// The status of the fulfillment.
    /// </summary>
    [JsonPropertyName("status")]
    public FulfillmentStatus Status { get; init; }

    /// <summary>
    /// Sum of all line item quantities for the fulfillment.
    /// </summary>
    [JsonPropertyName("totalQuantity")]
    public int TotalQuantity { get; init; }

    /// <summary>
    /// Tracking information associated with the fulfillment,
    /// such as the tracking company, tracking number, and tracking URL.
    /// </summary>
    [JsonPropertyName("trackingInfo")]
    public List<FulfillmentTrackingInfo> TrackingInfo { get; init; } = [];

    /// <summary>
    /// The date and time when the fulfillment was last modified.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateTimeOffset UpdatedAt { get; init; }

}
