// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `fulfillmentOrderSplit` mutation.
/// </summary>
public sealed partial class FulfillmentOrderSplitPayload
{
    /// <summary>
    /// The result of the fulfillment order splits.
    /// </summary>
    [JsonPropertyName("fulfillmentOrderSplits")]
    public List<FulfillmentOrderSplitResult>? FulfillmentOrderSplits { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<FulfillmentOrderSplitUserError> UserErrors { get; init; } = [];

}
