// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `fulfillmentServiceUpdate` mutation.
/// </summary>
public sealed partial class FulfillmentServiceUpdatePayload
{
    /// <summary>
    /// The updated fulfillment service.
    /// </summary>
    [JsonPropertyName("fulfillmentService")]
    public FulfillmentService? FulfillmentService { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
