// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Associates an order line item with the quantities that require fulfillment as part of a fulfillment order. Each Fulfillment Order Line Item object tracks the total quantity to fulfill and the remaining quantity yet to be fulfilled, along with details about the line item being fulfilled and pricing information.
/// 
/// The line item provides additional fulfillment data including whether the item requires shipping. Financial summaries show pricing details with discounts applied, while warning messages alert merchants to any issues that might affect fulfillment.
/// </summary>
public sealed partial class FulfillmentOrderLineItem : Node
{
    /// <summary>
    /// The financial summary for the Fulfillment Order's Line Items.
    /// </summary>
    [JsonPropertyName("financialSummaries")]
    public List<FulfillmentOrderLineItemFinancialSummary> FinancialSummaries { get; init; } = [];

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The image associated to the line item's variant.
    /// </summary>
    [JsonPropertyName("image")]
    public Image? Image { get; init; }

    /// <summary>
    /// The ID of the inventory item.
    /// </summary>
    [JsonPropertyName("inventoryItemId")]
    public string? InventoryItemId { get; init; }

    /// <summary>
    /// The associated order line item.
    /// </summary>
    [JsonPropertyName("lineItem")]
    public LineItem LineItem { get; init; } = null!;

    /// <summary>
    /// The variant unit price without discounts applied, in shop and presentment currencies.
    /// </summary>
    [JsonPropertyName("originalUnitPriceSet")]
    public MoneyBag OriginalUnitPriceSet { get; init; } = null!;

    /// <summary>
    /// The title of the product.
    /// </summary>
    [JsonPropertyName("productTitle")]
    public string ProductTitle { get; init; } = null!;

    /// <summary>
    /// The number of units remaining to be fulfilled.
    /// </summary>
    [JsonPropertyName("remainingQuantity")]
    public int RemainingQuantity { get; init; }

    /// <summary>
    /// Whether physical shipping is required for the variant.
    /// </summary>
    [JsonPropertyName("requiresShipping")]
    public bool RequiresShipping { get; init; }

    /// <summary>
    /// The variant SKU number.
    /// </summary>
    [JsonPropertyName("sku")]
    public string? Sku { get; init; }

    /// <summary>
    /// The total number of units to be fulfilled.
    /// </summary>
    [JsonPropertyName("totalQuantity")]
    public int TotalQuantity { get; init; }

    /// <summary>
    /// The product variant associated to the fulfillment order line item.
    /// </summary>
    [JsonPropertyName("variant")]
    public ProductVariant? Variant { get; init; }

    /// <summary>
    /// The name of the variant.
    /// </summary>
    [JsonPropertyName("variantTitle")]
    public string? VariantTitle { get; init; }

    /// <summary>
    /// The name of the vendor who made the variant.
    /// </summary>
    [JsonPropertyName("vendor")]
    public string? Vendor { get; init; }

    /// <summary>
    /// Warning messages for a fulfillment order line item.
    /// </summary>
    [JsonPropertyName("warnings")]
    public List<FulfillmentOrderLineItemWarning> Warnings { get; init; } = [];

    /// <summary>
    /// The weight of a line item unit.
    /// </summary>
    [JsonPropertyName("weight")]
    public Weight? Weight { get; init; }

}
