// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `fulfillmentOrderOpen` mutation.
/// </summary>
public sealed partial class FulfillmentOrderOpenPayload
{
    /// <summary>
    /// The fulfillment order that was transitioned to open and is fulfillable.
    /// </summary>
    [JsonPropertyName("fulfillmentOrder")]
    public FulfillmentOrder? FulfillmentOrder { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
