// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// An auto-generated type which holds one FulfillmentOrderLineItem and a cursor during pagination.
/// </summary>
public sealed partial class FulfillmentOrderLineItemEdge
{
    /// <summary>
    /// The position of each node in an array, used in [pagination](https://shopify.dev/api/usage/pagination-graphql).
    /// </summary>
    [JsonPropertyName("cursor")]
    public string Cursor { get; init; } = null!;

    /// <summary>
    /// The item at the end of FulfillmentOrderLineItemEdge.
    /// </summary>
    [JsonPropertyName("node")]
    public FulfillmentOrderLineItem Node { get; init; } = null!;

}
