// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `giftCardCredit` mutation.
/// </summary>
public sealed partial class GiftCardCreditPayload
{
    /// <summary>
    /// The gift card credit transaction that was created.
    /// </summary>
    [JsonPropertyName("giftCardCreditTransaction")]
    public GiftCardCreditTransaction? GiftCardCreditTransaction { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<GiftCardTransactionUserError> UserErrors { get; init; } = [];

}
