// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `inventoryShipmentMarkInTransit` mutation.
/// </summary>
public sealed partial class InventoryShipmentMarkInTransitPayload
{
    /// <summary>
    /// The marked in transit inventory shipment.
    /// </summary>
    [JsonPropertyName("inventoryShipment")]
    public InventoryShipment? InventoryShipment { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<InventoryShipmentMarkInTransitUserError> UserErrors { get; init; } = [];

}
