// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `inventoryShipmentCreateInTransit` mutation.
/// </summary>
public sealed partial class InventoryShipmentCreateInTransitPayload
{
    /// <summary>
    /// The created inventory shipment.
    /// </summary>
    [JsonPropertyName("inventoryShipment")]
    public InventoryShipment? InventoryShipment { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<InventoryShipmentCreateInTransitUserError> UserErrors { get; init; } = [];

}
