// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `inventoryShipmentUpdateItemQuantities` mutation.
/// </summary>
public sealed partial class InventoryShipmentUpdateItemQuantitiesPayload
{
    /// <summary>
    /// The inventory shipment with updated item quantities.
    /// </summary>
    [JsonPropertyName("shipment")]
    public InventoryShipment? Shipment { get; init; }

    /// <summary>
    /// The updated item quantities.
    /// </summary>
    [JsonPropertyName("updatedLineItems")]
    public List<InventoryShipmentLineItem>? UpdatedLineItems { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<InventoryShipmentUpdateItemQuantitiesUserError> UserErrors { get; init; } = [];

}
