// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `marketingActivityUpdateExternal` mutation.
/// </summary>
public sealed partial class MarketingActivityUpdateExternalPayload
{
    /// <summary>
    /// The updated marketing activity.
    /// </summary>
    [JsonPropertyName("marketingActivity")]
    public MarketingActivity? MarketingActivity { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<MarketingActivityUserError> UserErrors { get; init; } = [];

}
