// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The entitlements for B2B markets.
/// </summary>
public sealed partial class MarketsB2BEntitlement
{
    /// <summary>
    /// The entitlements for B2B market catalogs.
    /// </summary>
    [JsonPropertyName("catalogs")]
    public MarketsCatalogsEntitlement Catalogs { get; init; } = null!;

    /// <summary>
    /// Whether B2B markets are enabled.
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

}
