// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `marketingActivitiesDeleteAllExternal` mutation.
/// </summary>
public sealed partial class MarketingActivitiesDeleteAllExternalPayload
{
    /// <summary>
    /// The asynchronous job that performs the deletion. The status of the job may be used to determine when it's safe again to create new activities.
    /// </summary>
    [JsonPropertyName("job")]
    public Job? Job { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<MarketingActivityUserError> UserErrors { get; init; } = [];

}
