// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `menuDelete` mutation.
/// </summary>
public sealed partial class MenuDeletePayload
{
    /// <summary>
    /// The ID of the deleted menu.
    /// </summary>
    [JsonPropertyName("deletedMenuId")]
    public string? DeletedMenuId { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<MenuDeleteUserError> UserErrors { get; init; } = [];

}
