// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Defines a relation between two resources via a reference metafield.
/// The referencer owns the joining field with a given namespace and key,
/// while the target is referenced by the field.
/// </summary>
public sealed partial class MetafieldRelation
{
    /// <summary>
    /// The key of the field making the reference.
    /// </summary>
    [JsonPropertyName("key")]
    public string Key { get; init; } = null!;

    /// <summary>
    /// The name of the field making the reference.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The namespace of the metafield making the reference, or type of the metaobject.
    /// </summary>
    [JsonPropertyName("namespace")]
    public string @Namespace { get; init; } = null!;

    /// <summary>
    /// The resource making the reference.
    /// </summary>
    [JsonPropertyName("referencer")]
    public MetafieldReferencer Referencer { get; init; } = null!;

    /// <summary>
    /// The referenced resource.
    /// </summary>
    [JsonPropertyName("target")]
    public MetafieldReference Target { get; init; } = null!;

}
