// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Access permissions for the definition's metafields.
/// </summary>
public sealed partial class MetafieldAccess
{
    /// <summary>
    /// The access permitted on the Admin API.
    /// </summary>
    [JsonPropertyName("admin")]
    public MetafieldAdminAccess? Admin { get; init; }

    /// <summary>
    /// The access permitted on the Customer Account API.
    /// </summary>
    [JsonPropertyName("customerAccount")]
    public MetafieldCustomerAccountAccess CustomerAccount { get; init; }

    /// <summary>
    /// The access permitted on the Storefront API.
    /// </summary>
    [JsonPropertyName("storefront")]
    public MetafieldStorefrontAccess? Storefront { get; init; }

}
