// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `metaobjectCreate` mutation.
/// </summary>
public sealed partial class MetaobjectCreatePayload
{
    /// <summary>
    /// The created metaobject.
    /// </summary>
    [JsonPropertyName("metaobject")]
    public Metaobject? Metaobject { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<MetaobjectUserError> UserErrors { get; init; } = [];

}
