// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Identifies a metafield by its owner resource, namespace, and key.
/// </summary>
public sealed partial class MetafieldIdentifier
{
    /// <summary>
    /// The key of the metafield.
    /// </summary>
    [JsonPropertyName("key")]
    public string Key { get; init; } = null!;

    /// <summary>
    /// The namespace of the metafield.
    /// </summary>
    [JsonPropertyName("namespace")]
    public string @Namespace { get; init; } = null!;

    /// <summary>
    /// GID of the owner resource that the metafield belongs to.
    /// </summary>
    [JsonPropertyName("ownerId")]
    public string OwnerId { get; init; } = null!;

}
