// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The publishable capability for the parent metaobject.
/// </summary>
public sealed partial class MetaobjectCapabilityDataPublishable
{
    /// <summary>
    /// The visibility status of this metaobject across all channels.
    /// </summary>
    [JsonPropertyName("status")]
    public MetaobjectStatus Status { get; init; }

}
