// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A signed upload parameter for uploading an asset to Shopify.
/// 
/// Deprecated in favor of
/// [StagedUploadParameter](https://shopify.dev/api/admin-graphql/latest/objects/StagedUploadParameter),
/// which is used in
/// [StagedMediaUploadTarget](https://shopify.dev/api/admin-graphql/latest/objects/StagedMediaUploadTarget)
/// and returned by the
/// [stagedUploadsCreate mutation](https://shopify.dev/api/admin-graphql/latest/mutations/stagedUploadsCreate).
/// </summary>
public sealed partial class MutationsStagedUploadTargetGenerateUploadParameter
{
    /// <summary>
    /// The upload parameter name.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The upload parameter value.
    /// </summary>
    [JsonPropertyName("value")]
    public string Value { get; init; } = null!;

}
