// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents a theme file.
/// </summary>
public sealed partial class OnlineStoreThemeFile
{
    /// <summary>
    /// The body of the theme file.
    /// </summary>
    [JsonPropertyName("body")]
    public OnlineStoreThemeFileBody Body { get; init; } = null!;

    /// <summary>
    /// The md5 digest of the theme file for data integrity.
    /// </summary>
    [JsonPropertyName("checksumMd5")]
    public string? ChecksumMd5 { get; init; }

    /// <summary>
    /// The content type of the theme file.
    /// </summary>
    [JsonPropertyName("contentType")]
    public string ContentType { get; init; } = null!;

    /// <summary>
    /// The date and time when the theme file was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// The unique identifier of the theme file.
    /// </summary>
    [JsonPropertyName("filename")]
    public string Filename { get; init; } = null!;

    /// <summary>
    /// The size of the theme file in bytes.
    /// </summary>
    [JsonPropertyName("size")]
    public ulong Size { get; init; }

    /// <summary>
    /// The date and time when the theme file was last updated.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateTimeOffset UpdatedAt { get; init; }

}
