// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents the body of a theme file.
/// </summary>
public sealed partial class OnlineStoreThemeFileBodyText
{
    /// <summary>
    /// The body of the theme file.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; init; } = null!;

}
