// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `orderCustomerRemove` mutation.
/// </summary>
public sealed partial class OrderCustomerRemovePayload
{
    /// <summary>
    /// The order that had its customer removed.
    /// </summary>
    [JsonPropertyName("order")]
    public Order? Order { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<OrderCustomerRemoveUserError> UserErrors { get; init; } = [];

}
