// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The status of a customer's payment for an order.
/// </summary>
public sealed partial class OrderPaymentStatus
{
    /// <summary>
    /// A message describing an error during the asynchronous processing of a payment.
    /// </summary>
    [JsonPropertyName("errorMessage")]
    public string? ErrorMessage { get; init; }

    /// <summary>
    /// The ID of the payment, initially returned by an `orderCreateMandatePayment` or `orderCreatePayment` mutation.
    /// </summary>
    [JsonPropertyName("paymentReferenceId")]
    public string PaymentReferenceId { get; init; } = null!;

    /// <summary>
    /// The status of the payment.
    /// </summary>
    [JsonPropertyName("status")]
    public OrderPaymentStatusResult Status { get; init; }

    /// <summary>
    /// The transaction associated with the payment.
    /// </summary>
    [JsonPropertyName("transactions")]
    public List<OrderTransaction> Transactions { get; init; } = [];

    /// <summary>
    /// A translated message describing an error during the asynchronous processing of a payment.
    /// </summary>
    [JsonPropertyName("translatedErrorMessage")]
    public string? TranslatedErrorMessage { get; init; }

}
