// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The payment collection details for an order that requires additional payment following an edit to the order.
/// </summary>
public sealed partial class OrderPaymentCollectionDetails
{
    /// <summary>
    /// The URL to use for collecting an additional payment on the order.
    /// </summary>
    [JsonPropertyName("additionalPaymentCollectionUrl")]
    public Uri? AdditionalPaymentCollectionUrl { get; init; }

    /// <summary>
    /// The list of vaulted payment methods for the order with their permissions.
    /// </summary>
    [JsonPropertyName("vaultedPaymentMethods")]
    public List<PaymentMandate>? VaultedPaymentMethods { get; init; }

}
