// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `orderUpdate` mutation.
/// </summary>
public sealed partial class OrderUpdatePayload
{
    /// <summary>
    /// The updated order.
    /// </summary>
    [JsonPropertyName("order")]
    public Order? Order { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
