// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// An removal of items from an existing line item on the order.
/// </summary>
public sealed partial class OrderStagedChangeDecrementItem
{
    /// <summary>
    /// The number of items removed.
    /// </summary>
    [JsonPropertyName("delta")]
    public int Delta { get; init; }

    /// <summary>
    /// The original line item.
    /// </summary>
    [JsonPropertyName("lineItem")]
    public LineItem LineItem { get; init; } = null!;

    /// <summary>
    /// The intention to restock the removed items.
    /// </summary>
    [JsonPropertyName("restock")]
    public bool Restock { get; init; }

}
