// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `orderEditAddVariant` mutation.
/// </summary>
public sealed partial class OrderEditAddVariantPayload
{
    /// <summary>
    /// The [calculated line item](https://shopify.dev/api/admin-graphql/latest/objects/calculatedlineitem)
    /// that's added during this order edit.
    /// </summary>
    [JsonPropertyName("calculatedLineItem")]
    public CalculatedLineItem? CalculatedLineItem { get; init; }

    /// <summary>
    /// The [calculated order](https://shopify.dev/api/admin-graphql/latest/objects/calculatedorder)
    /// with the edits applied but not saved.
    /// </summary>
    [JsonPropertyName("calculatedOrder")]
    public CalculatedOrder? CalculatedOrder { get; init; }

    /// <summary>
    /// The order edit session with the edits applied but not saved.
    /// </summary>
    [JsonPropertyName("orderEditSession")]
    public OrderEditSession? OrderEditSession { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
