// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A payment instrument and the permission
/// the owner of the instrument gives to the merchant to debit it.
/// </summary>
public sealed partial class PaymentMandate : Node
{
    /// <summary>
    /// The unique ID of a payment mandate.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The outputs details of the payment instrument.
    /// </summary>
    [JsonPropertyName("paymentInstrument")]
    public PaymentInstrument PaymentInstrument { get; init; } = null!;

}
