// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents relative adjustments from one price list to other prices.
///   You can use a `PriceListParent` to specify an adjusted relative price using a percentage-based
///   adjustment. Adjusted prices work in conjunction with exchange rules and rounding.
/// 
///   [Adjustment types](https://shopify.dev/api/admin-graphql/latest/enums/pricelistadjustmenttype)
///   support both percentage increases and decreases.
/// </summary>
public sealed partial class PriceListParent
{
    /// <summary>
    /// A price list adjustment.
    /// </summary>
    [JsonPropertyName("adjustment")]
    public PriceListAdjustment Adjustment { get; init; } = null!;

    /// <summary>
    /// A price list's settings for adjustment.
    /// </summary>
    [JsonPropertyName("settings")]
    public PriceListAdjustmentSettings Settings { get; init; } = null!;

}
