// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A money range within which the price rule is applicable.
/// </summary>
public sealed partial class PriceRuleMoneyRange
{
    /// <summary>
    /// The lower bound of the money range.
    /// </summary>
    [JsonPropertyName("greaterThan")]
    public string? GreaterThan { get; init; }

    /// <summary>
    /// The lower bound or equal of the money range.
    /// </summary>
    [JsonPropertyName("greaterThanOrEqualTo")]
    public string? GreaterThanOrEqualTo { get; init; }

    /// <summary>
    /// The upper bound of the money range.
    /// </summary>
    [JsonPropertyName("lessThan")]
    public string? LessThan { get; init; }

    /// <summary>
    /// The upper bound or equal of the money range.
    /// </summary>
    [JsonPropertyName("lessThanOrEqualTo")]
    public string? LessThanOrEqualTo { get; init; }

}
