// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Quantity of prerequisite items required for the price rule to be applicable, compared to quantity of entitled items.
/// </summary>
public sealed partial class PriceRuleEntitlementToPrerequisiteQuantityRatio
{
    /// <summary>
    /// The quantity of entitled items in the ratio.
    /// </summary>
    [JsonPropertyName("entitlementQuantity")]
    public int EntitlementQuantity { get; init; }

    /// <summary>
    /// The quantity of prerequisite items in the ratio.
    /// </summary>
    [JsonPropertyName("prerequisiteQuantity")]
    public int PrerequisiteQuantity { get; init; }

}
