// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A time period during which a price rule is applicable.
/// </summary>
public sealed partial class PriceRuleValidityPeriod
{
    /// <summary>
    /// The time after which the price rule becomes invalid.
    /// </summary>
    [JsonPropertyName("end")]
    public DateTimeOffset? End { get; init; }

    /// <summary>
    /// The time after which the price rule is valid.
    /// </summary>
    [JsonPropertyName("start")]
    public DateTimeOffset Start { get; init; }

}
