// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents a [Shopify product taxonomy](https://shopify.github.io/product-taxonomy/releases/unstable/?categoryId=sg-4-17-2-17) node.
/// </summary>
public sealed partial class ProductTaxonomyNode : Node
{
    /// <summary>
    /// The full name of the product taxonomy node. For example,  Animals &amp; Pet Supplies &gt; Pet Supplies &gt; Dog Supplies &gt; Dog Beds.
    /// </summary>
    [JsonPropertyName("fullName")]
    public string FullName { get; init; } = null!;

    /// <summary>
    /// The ID of the product taxonomy node.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Whether the node is a leaf node.
    /// </summary>
    [JsonPropertyName("isLeaf")]
    public bool IsLeaf { get; init; }

    /// <summary>
    /// Whether the node is a root node.
    /// </summary>
    [JsonPropertyName("isRoot")]
    public bool IsRoot { get; init; }

    /// <summary>
    /// The name of the product taxonomy node. For example, Dog Beds.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

}
