// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `productDeleteMedia` mutation.
/// </summary>
public sealed partial class ProductDeleteMediaPayload
{
    /// <summary>
    /// List of media IDs which were deleted.
    /// </summary>
    [JsonPropertyName("deletedMediaIds")]
    public List<string>? DeletedMediaIds { get; init; }

    /// <summary>
    /// List of product image IDs which were deleted.
    /// </summary>
    [JsonPropertyName("deletedProductImageIds")]
    public List<string>? DeletedProductImageIds { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("mediaUserErrors")]
    public List<MediaUserError> MediaUserErrors { get; init; } = [];

    /// <summary>
    /// The product associated with the deleted media.
    /// </summary>
    [JsonPropertyName("product")]
    public Product? Product { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
