// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The product's component information.
/// </summary>
public sealed partial class ProductBundleComponent
{
    /// <summary>
    /// The product that's related as a component.
    /// </summary>
    [JsonPropertyName("componentProduct")]
    public Product ComponentProduct { get; init; } = null!;

    /// <summary>
    /// The list of products' variants that are components.
    /// </summary>
    [JsonPropertyName("componentVariants")]
    public ProductVariantConnection ComponentVariants { get; init; } = null!;

    /// <summary>
    /// The number of component variants for the product component.
    /// </summary>
    [JsonPropertyName("componentVariantsCount")]
    public Count? ComponentVariantsCount { get; init; }

    /// <summary>
    /// The options in the parent and the component options they're connected to, along with the chosen option values
    /// that appear in the bundle.
    /// </summary>
    [JsonPropertyName("optionSelections")]
    public List<ProductBundleComponentOptionSelection> OptionSelections { get; init; } = [];

    /// <summary>
    /// The quantity of the component product set for this bundle line.
    /// It will be null if there's a quantityOption present.
    /// </summary>
    [JsonPropertyName("quantity")]
    public int? Quantity { get; init; }

    /// <summary>
    /// The quantity as option of the component product. It will be null if there's a quantity set.
    /// </summary>
    [JsonPropertyName("quantityOption")]
    public ProductBundleComponentQuantityOption? QuantityOption { get; init; }

}
