// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `productVariantsBulkUpdate` mutation.
/// </summary>
public sealed partial class ProductVariantsBulkUpdatePayload
{
    /// <summary>
    /// The updated product object.
    /// </summary>
    [JsonPropertyName("product")]
    public Product? Product { get; init; }

    /// <summary>
    /// The updated variants.
    /// </summary>
    [JsonPropertyName("productVariants")]
    public List<ProductVariant>? ProductVariants { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<ProductVariantsBulkUpdateUserError> UserErrors { get; init; } = [];

}
