// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `pubSubWebhookSubscriptionCreate` mutation.
/// </summary>
public sealed partial class PubSubWebhookSubscriptionCreatePayload
{
    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<PubSubWebhookSubscriptionCreateUserError> UserErrors { get; init; } = [];

    /// <summary>
    /// The webhook subscription that was created.
    /// </summary>
    [JsonPropertyName("webhookSubscription")]
    public WebhookSubscription? WebhookSubscription { get; init; }

}
