// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `pubSubServerPixelUpdate` mutation.
/// </summary>
public sealed partial class PubSubServerPixelUpdatePayload
{
    /// <summary>
    /// The server pixel as configured by the mutation.
    /// </summary>
    [JsonPropertyName("serverPixel")]
    public ServerPixel? ServerPixel { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<ErrorsServerPixelUserError> UserErrors { get; init; } = [];

}
