// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The tax allocated to a sale from a single tax line.
/// </summary>
public sealed partial class SaleTax
{
    /// <summary>
    /// The portion of the total tax amount on the related sale that comes from the associated tax line.
    /// </summary>
    [JsonPropertyName("amount")]
    public MoneyBag Amount { get; init; } = null!;

    /// <summary>
    /// The unique ID for the sale tax.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The tax line associated with the sale.
    /// </summary>
    [JsonPropertyName("taxLine")]
    public TaxLine TaxLine { get; init; } = null!;

}
