// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// &lt;div class="note"&gt;&lt;h4&gt;Theme app extensions&lt;/h4&gt;
///   &lt;p&gt;If your app integrates with a Shopify theme and you plan to submit it to the Shopify App Store, you must use theme app extensions instead of Script tags. Script tags can only be used with vintage themes. &lt;a href="/apps/online-store#what-integration-method-should-i-use" target="_blank"&gt;Learn more&lt;/a&gt;.&lt;/p&gt;&lt;/div&gt;
/// 
/// &lt;div class="note"&gt;&lt;h4&gt;Script tag deprecation&lt;/h4&gt;
///   &lt;p&gt;Script tags will be sunset for the &lt;b&gt;Order status&lt;/b&gt; page on August 28, 2025. &lt;a href="https://www.shopify.com/plus/upgrading-to-checkout-extensibility"&gt;Upgrade to Checkout Extensibility&lt;/a&gt; before this date. &lt;a href="/docs/api/liquid/objects#script"&gt;Shopify Scripts&lt;/a&gt; will continue to work alongside Checkout Extensibility until August 28, 2025.&lt;/p&gt;&lt;/div&gt;
/// 
/// 
/// A script tag represents remote JavaScript code that is loaded into the pages of a shop's storefront or the **Order status** page of checkout.
/// </summary>
public sealed partial class ScriptTag : LegacyInteroperability, Node
{
    /// <summary>
    /// Whether the Shopify CDN can cache and serve the script tag.
    /// If `true`, then the script will be cached and served by the CDN.
    /// The cache expires 15 minutes after the script tag is successfully returned.
    /// If `false`, then the script will be served as is.
    /// </summary>
    [JsonPropertyName("cache")]
    public bool Cache { get; init; }

    /// <summary>
    /// The date and time when the script tag was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// The page or pages on the online store that the script should be included.
    /// </summary>
    [JsonPropertyName("displayScope")]
    public ScriptTagDisplayScope DisplayScope { get; init; }

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The ID of the corresponding resource in the REST Admin API.
    /// </summary>
    [JsonPropertyName("legacyResourceId")]
    public ulong LegacyResourceId { get; init; }

    /// <summary>
    /// The URL to the remote script.
    /// </summary>
    [JsonPropertyName("src")]
    public Uri Src { get; init; } = null!;

    /// <summary>
    /// The date and time when the script tag was last updated.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public DateTimeOffset UpdatedAt { get; init; }

}
