// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `scriptTagUpdate` mutation.
/// </summary>
public sealed partial class ScriptTagUpdatePayload
{
    /// <summary>
    /// The script tag that was updated.
    /// </summary>
    [JsonPropertyName("scriptTag")]
    public ScriptTag? ScriptTag { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
