// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A filter in a search query represented by a key value pair.
/// </summary>
public sealed partial class SearchFilter
{
    /// <summary>
    /// The key of the search filter.
    /// </summary>
    [JsonPropertyName("key")]
    public string Key { get; init; } = null!;

    /// <summary>
    /// The value of the search filter.
    /// </summary>
    [JsonPropertyName("value")]
    public string Value { get; init; } = null!;

}
