// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The statistics of a given segment.
/// </summary>
public sealed partial class SegmentStatistics
{
    /// <summary>
    /// The statistics of a given attribute.
    /// </summary>
    [JsonPropertyName("attributeStatistics")]
    public SegmentAttributeStatistics AttributeStatistics { get; init; } = null!;

}
