// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A shipping option associated with order delivery that includes pricing and service information.
/// </summary>
public sealed partial class ShippingRate
{
    /// <summary>
    /// Human-readable unique identifier for this shipping rate.
    /// </summary>
    [JsonPropertyName("handle")]
    public string Handle { get; init; } = null!;

    /// <summary>
    /// The cost associated with the shipping rate.
    /// </summary>
    [JsonPropertyName("price")]
    public MoneyV2 Price { get; init; } = null!;

    /// <summary>
    /// The name of the shipping rate.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = null!;

}
