// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `shippingPackageDelete` mutation.
/// </summary>
public sealed partial class ShippingPackageDeletePayload
{
    /// <summary>
    /// The ID of the deleted shipping package.
    /// </summary>
    [JsonPropertyName("deletedId")]
    public string? DeletedId { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
