// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents an image for a Shop Pay payment request line item.
/// </summary>
public sealed partial class ShopPayPaymentRequestImage
{
    /// <summary>
    /// The alt text of the image.
    /// </summary>
    [JsonPropertyName("alt")]
    public string? Alt { get; init; }

    /// <summary>
    /// The source URL of the image.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; init; } = null!;

}
