// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A dispute occurs when a buyer questions the legitimacy of a charge with their financial institution.
/// </summary>
public sealed partial class ShopifyPaymentsDispute : LegacyInteroperability, Node
{
    /// <summary>
    /// The total amount disputed by the cardholder.
    /// </summary>
    [JsonPropertyName("amount")]
    public MoneyV2 Amount { get; init; } = null!;

    /// <summary>
    /// The evidence associated with the dispute.
    /// </summary>
    [JsonPropertyName("disputeEvidence")]
    public ShopifyPaymentsDisputeEvidence DisputeEvidence { get; init; } = null!;

    /// <summary>
    /// The deadline for evidence submission.
    /// </summary>
    [JsonPropertyName("evidenceDueBy")]
    public DateOnly? EvidenceDueBy { get; init; }

    /// <summary>
    /// The date when evidence was sent. Returns null if evidence hasn't yet been sent.
    /// </summary>
    [JsonPropertyName("evidenceSentOn")]
    public DateOnly? EvidenceSentOn { get; init; }

    /// <summary>
    /// The date when this dispute was resolved. Returns null if the dispute isn't yet resolved.
    /// </summary>
    [JsonPropertyName("finalizedOn")]
    public DateOnly? FinalizedOn { get; init; }

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The date when this dispute was initiated.
    /// </summary>
    [JsonPropertyName("initiatedAt")]
    public DateTimeOffset InitiatedAt { get; init; }

    /// <summary>
    /// The ID of the corresponding resource in the REST Admin API.
    /// </summary>
    [JsonPropertyName("legacyResourceId")]
    public ulong LegacyResourceId { get; init; }

    /// <summary>
    /// The order that contains the charge that's under dispute.
    /// </summary>
    [JsonPropertyName("order")]
    public Order? Order { get; init; }

    /// <summary>
    /// The reason of the dispute.
    /// </summary>
    [JsonPropertyName("reasonDetails")]
    public ShopifyPaymentsDisputeReasonDetails ReasonDetails { get; init; } = null!;

    /// <summary>
    /// The current state of the dispute.
    /// </summary>
    [JsonPropertyName("status")]
    public DisputeStatus Status { get; init; }

    /// <summary>
    /// Indicates if this dispute is still in the inquiry phase or has turned into a chargeback.
    /// </summary>
    [JsonPropertyName("type")]
    public DisputeType Type { get; init; }

}
