// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents a contact field for a Shop Pay payment request.
/// </summary>
public sealed partial class ShopPayPaymentRequestContactField
{
    /// <summary>
    /// The first address line of the contact field.
    /// </summary>
    [JsonPropertyName("address1")]
    public string Address1 { get; init; } = null!;

    /// <summary>
    /// The second address line of the contact field.
    /// </summary>
    [JsonPropertyName("address2")]
    public string? Address2 { get; init; }

    /// <summary>
    /// The city of the contact field.
    /// </summary>
    [JsonPropertyName("city")]
    public string City { get; init; } = null!;

    /// <summary>
    /// The company name of the contact field.
    /// </summary>
    [JsonPropertyName("companyName")]
    public string? CompanyName { get; init; }

    /// <summary>
    /// The country of the contact field.
    /// </summary>
    [JsonPropertyName("countryCode")]
    public string CountryCode { get; init; } = null!;

    /// <summary>
    /// The email of the contact field.
    /// </summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>
    /// The first name of the contact field.
    /// </summary>
    [JsonPropertyName("firstName")]
    public string FirstName { get; init; } = null!;

    /// <summary>
    /// The last name of the contact field.
    /// </summary>
    [JsonPropertyName("lastName")]
    public string LastName { get; init; } = null!;

    /// <summary>
    /// The phone number of the contact field.
    /// </summary>
    [JsonPropertyName("phone")]
    public string? Phone { get; init; }

    /// <summary>
    /// The postal code of the contact field.
    /// </summary>
    [JsonPropertyName("postalCode")]
    public string? PostalCode { get; init; }

    /// <summary>
    /// The province of the contact field.
    /// </summary>
    [JsonPropertyName("provinceCode")]
    public string? ProvinceCode { get; init; }

}
