// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `storefrontAccessTokenCreate` mutation.
/// </summary>
public sealed partial class StorefrontAccessTokenCreatePayload
{
    /// <summary>
    /// The user's shop.
    /// </summary>
    [JsonPropertyName("shop")]
    public Shop Shop { get; init; } = null!;

    /// <summary>
    /// The storefront access token.
    /// </summary>
    [JsonPropertyName("storefrontAccessToken")]
    public StorefrontAccessToken? StorefrontAccessToken { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<UserError> UserErrors { get; init; } = [];

}
