// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A subscription delivery method for local delivery.
/// The other subscription delivery methods can be found in the `SubscriptionDeliveryMethod` union type.
/// </summary>
public sealed partial class SubscriptionDeliveryMethodLocalDelivery
{
    /// <summary>
    /// The address to deliver to.
    /// </summary>
    [JsonPropertyName("address")]
    public MailingAddress Address { get; init; } = null!;

    /// <summary>
    /// The details of the local delivery method to use.
    /// </summary>
    [JsonPropertyName("localDeliveryOption")]
    public SubscriptionDeliveryMethodLocalDeliveryOption LocalDeliveryOption { get; init; } = null!;

}
