// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `subscriptionDraftLineRemove` mutation.
/// </summary>
public sealed partial class SubscriptionDraftLineRemovePayload
{
    /// <summary>
    /// The list of updated subscription discounts impacted by the removed line.
    /// </summary>
    [JsonPropertyName("discountsUpdated")]
    public List<SubscriptionManualDiscount>? DiscountsUpdated { get; init; }

    /// <summary>
    /// The Subscription Contract draft object.
    /// </summary>
    [JsonPropertyName("draft")]
    public SubscriptionDraft? Draft { get; init; }

    /// <summary>
    /// The removed Subscription Line.
    /// </summary>
    [JsonPropertyName("lineRemoved")]
    public SubscriptionLine? LineRemoved { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<SubscriptionDraftUserError> UserErrors { get; init; } = [];

}
