// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A failure to find the available delivery options for a subscription contract.
/// </summary>
public sealed partial class SubscriptionDeliveryOptionResultFailure
{
    /// <summary>
    /// The reason for the failure.
    /// </summary>
    [JsonPropertyName("message")]
    public string? Message { get; init; }

}
