// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents what a particular discount reduces from a line price.
/// </summary>
public sealed partial class SubscriptionDiscountAllocation
{
    /// <summary>
    /// Allocation amount.
    /// </summary>
    [JsonPropertyName("amount")]
    public MoneyV2 Amount { get; init; } = null!;

    /// <summary>
    /// Discount that created the allocation.
    /// </summary>
    [JsonPropertyName("discount")]
    public SubscriptionDiscount Discount { get; init; } = null!;

}
