// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents a Subscription Line Pricing Cycle Adjustment.
/// </summary>
public sealed partial class SubscriptionCyclePriceAdjustment
{
    /// <summary>
    /// Price adjustment type.
    /// </summary>
    [JsonPropertyName("adjustmentType")]
    public SellingPlanPricingPolicyAdjustmentType AdjustmentType { get; init; }

    /// <summary>
    /// Price adjustment value.
    /// </summary>
    [JsonPropertyName("adjustmentValue")]
    public SellingPlanPricingPolicyAdjustmentValue AdjustmentValue { get; init; } = null!;

    /// <summary>
    /// The number of cycles required before this pricing policy applies.
    /// </summary>
    [JsonPropertyName("afterCycle")]
    public int AfterCycle { get; init; }

    /// <summary>
    /// The computed price after the adjustments applied.
    /// </summary>
    [JsonPropertyName("computedPrice")]
    public MoneyV2 ComputedPrice { get; init; } = null!;

}
