// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The delivery option for a subscription contract.
/// </summary>
public sealed partial class SubscriptionDeliveryOptionResultSuccess
{
    /// <summary>
    /// The available delivery options.
    /// </summary>
    [JsonPropertyName("deliveryOptions")]
    public List<SubscriptionDeliveryOption> DeliveryOptions { get; init; } = [];

}
