// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `subscriptionBillingCycleUnskip` mutation.
/// </summary>
public sealed partial class SubscriptionBillingCycleUnskipPayload
{
    /// <summary>
    /// The updated billing cycle.
    /// </summary>
    [JsonPropertyName("billingCycle")]
    public SubscriptionBillingCycle? BillingCycle { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<SubscriptionBillingCycleUnskipUserError> UserErrors { get; init; } = [];

}
