// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents a return refund suggested by Shopify based on the items being reimbursed. You can then use the suggested refund object to generate an actual refund for the return.
/// </summary>
public sealed partial class SuggestedReturnRefund
{
    /// <summary>
    /// The total monetary value to be refunded in shop and presentment currencies.
    /// </summary>
    [JsonPropertyName("amount")]
    public MoneyBag Amount { get; init; } = null!;

    /// <summary>
    /// The sum of all the discounted prices of the line items being refunded.
    /// </summary>
    [JsonPropertyName("discountedSubtotal")]
    public MoneyBag DiscountedSubtotal { get; init; } = null!;

    /// <summary>
    /// The total monetary value available to refund in shop and presentment currencies.
    /// </summary>
    [JsonPropertyName("maximumRefundable")]
    public MoneyBag MaximumRefundable { get; init; } = null!;

    /// <summary>
    /// A list of duties to be refunded from the order.
    /// </summary>
    [JsonPropertyName("refundDuties")]
    public List<RefundDuty> RefundDuties { get; init; } = [];

    /// <summary>
    /// The shipping costs to be refunded from the order.
    /// </summary>
    [JsonPropertyName("shipping")]
    public ShippingRefund Shipping { get; init; } = null!;

    /// <summary>
    /// The sum of all the prices of the line items being refunded in shop and presentment currencies.
    /// </summary>
    [JsonPropertyName("subtotal")]
    public MoneyBag Subtotal { get; init; } = null!;

    /// <summary>
    /// A list of suggested order transactions.
    /// </summary>
    [JsonPropertyName("suggestedTransactions")]
    public List<SuggestedOrderTransaction> SuggestedTransactions { get; init; } = [];

    /// <summary>
    /// The total cart discount amount that was applied to all line items in this refund.
    /// </summary>
    [JsonPropertyName("totalCartDiscountAmount")]
    public MoneyBag TotalCartDiscountAmount { get; init; } = null!;

    /// <summary>
    /// The sum of all the duties being refunded from the order in shop and presentment currencies. The value must be positive.
    /// </summary>
    [JsonPropertyName("totalDuties")]
    public MoneyBag TotalDuties { get; init; } = null!;

    /// <summary>
    /// The sum of the taxes being refunded in shop and presentment currencies. The value must be positive.
    /// </summary>
    [JsonPropertyName("totalTax")]
    public MoneyBag TotalTax { get; init; } = null!;

}
