// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents a Shopify product taxonomy value.
/// </summary>
public sealed partial class TaxonomyValue : Node
{
    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The name of the product taxonomy value. For example, Red.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

}
