// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// A TenderTransaction represents a transaction with financial impact on a shop's balance sheet. A tender transaction always
/// represents actual money movement between a buyer and a shop. TenderTransactions can be used instead of OrderTransactions
/// for reconciling a shop's cash flow. A TenderTransaction is immutable once created.
/// </summary>
public sealed partial class TenderTransaction : Node
{
    /// <summary>
    /// The amount and currency of the tender transaction.
    /// </summary>
    [JsonPropertyName("amount")]
    public MoneyV2 Amount { get; init; } = null!;

    /// <summary>
    /// A globally-unique ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The order that's related to the tender transaction. This value is null if the order has been deleted.
    /// </summary>
    [JsonPropertyName("order")]
    public Order? Order { get; init; }

    /// <summary>
    /// Information about the payment method used for the transaction.
    /// </summary>
    [JsonPropertyName("paymentMethod")]
    public string? PaymentMethod { get; init; }

    /// <summary>
    /// Date and time when the transaction was processed.
    /// </summary>
    [JsonPropertyName("processedAt")]
    public DateTimeOffset? ProcessedAt { get; init; }

    /// <summary>
    /// The remote gateway reference associated with the tender transaction.
    /// </summary>
    [JsonPropertyName("remoteReference")]
    public string? RemoteReference { get; init; }

    /// <summary>
    /// Whether the transaction is a test transaction.
    /// </summary>
    [JsonPropertyName("test")]
    public bool Test { get; init; }

    /// <summary>
    /// Information about the payment instrument used for the transaction.
    /// </summary>
    [JsonPropertyName("transactionDetails")]
    public TenderTransactionDetails? TransactionDetails { get; init; }

    /// <summary>
    /// The staff member who performed the transaction.
    /// </summary>
    [JsonPropertyName("user")]
    public StaffMember? User { get; init; }

}
