// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `themeDelete` mutation.
/// </summary>
public sealed partial class ThemeDeletePayload
{
    /// <summary>
    /// The ID of the deleted theme.
    /// </summary>
    [JsonPropertyName("deletedThemeId")]
    public string? DeletedThemeId { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<ThemeDeleteUserError> UserErrors { get; init; } = [];

}
