// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Return type for `translationsRemove` mutation.
/// </summary>
public sealed partial class TranslationsRemovePayload
{
    /// <summary>
    /// The translations that were deleted.
    /// </summary>
    [JsonPropertyName("translations")]
    public List<Translation>? Translations { get; init; }

    /// <summary>
    /// The list of errors that occurred from executing the mutation.
    /// </summary>
    [JsonPropertyName("userErrors")]
    public List<TranslationUserError> UserErrors { get; init; } = [];

}
