// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// This is represents new sale types that have been added in future API versions. You may update to a more recent API version to receive additional details about this sale.
/// </summary>
public sealed partial class UnknownSale : Sale
{
    /// <summary>
    /// The type of order action that the sale represents.
    /// </summary>
    [JsonPropertyName("actionType")]
    public SaleActionType ActionType { get; init; }

    /// <summary>
    /// The unique ID for the sale.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The line type assocated with the sale.
    /// </summary>
    [JsonPropertyName("lineType")]
    public SaleLineType LineType { get; init; }

    /// <summary>
    /// The number of units either ordered or intended to be returned.
    /// </summary>
    [JsonPropertyName("quantity")]
    public int? Quantity { get; init; }

    /// <summary>
    /// All individual taxes associated with the sale.
    /// </summary>
    [JsonPropertyName("taxes")]
    public List<SaleTax> Taxes { get; init; } = [];

    /// <summary>
    /// The total sale amount after taxes and discounts.
    /// </summary>
    [JsonPropertyName("totalAmount")]
    public MoneyBag TotalAmount { get; init; } = null!;

    /// <summary>
    /// The total discounts allocated to the sale after taxes.
    /// </summary>
    [JsonPropertyName("totalDiscountAmountAfterTaxes")]
    public MoneyBag TotalDiscountAmountAfterTaxes { get; init; } = null!;

    /// <summary>
    /// The total discounts allocated to the sale before taxes.
    /// </summary>
    [JsonPropertyName("totalDiscountAmountBeforeTaxes")]
    public MoneyBag TotalDiscountAmountBeforeTaxes { get; init; } = null!;

    /// <summary>
    /// The total amount of taxes for the sale.
    /// </summary>
    [JsonPropertyName("totalTaxAmount")]
    public MoneyBag TotalTaxAmount { get; init; } = null!;

}
