// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'subscriptionContractFail' GraphQL operation.
/// </summary>
public sealed partial class SubscriptionContractFailData
{
    /// <summary>
    /// Fails a Subscription Contract.
    /// </summary>
    [JsonPropertyName("subscriptionContractFail")]
    public SubscriptionContractFailPayload? SubscriptionContractFail { get; init; }
}
