// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'fulfillmentCreate' GraphQL operation.
/// </summary>
public sealed class FulfillmentCreateVariables
{
    [JsonPropertyName("fulfillment")]
    public FulfillmentInput Fulfillment { get; init; } = null!;

    [JsonPropertyName("message")]
    public string? Message { get; init; }

}
