// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'mobilePlatformApplicationUpdate' GraphQL operation.
/// </summary>
public sealed partial class MobilePlatformApplicationUpdateData
{
    /// <summary>
    /// Update a mobile platform application.
    /// </summary>
    [JsonPropertyName("mobilePlatformApplicationUpdate")]
    public MobilePlatformApplicationUpdatePayload? MobilePlatformApplicationUpdate { get; init; }
}
