// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'productBundleUpdate' GraphQL operation.
/// </summary>
public sealed class ProductBundleUpdateVariables
{
    [JsonPropertyName("input")]
    public ProductBundleUpdateInput Input { get; init; } = null!;

}
