// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'quantityRulesAdd' GraphQL mutation.
/// </summary>
public sealed partial class QuantityRulesAddRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public QuantityRulesAddRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'quantityRulesAdd' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<QuantityRulesAddData>> Execute(QuantityRulesAddVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation QuantityRulesAdd($priceListId: ID!, $quantityRules: [QuantityRuleInput!]!) { quantityRulesAdd(priceListId: $priceListId, quantityRules: $quantityRules) { quantityRules { increment isDefault maximum minimum originType productVariant { availableForSale barcode compareAtPrice createdAt defaultCursor displayName id inventoryPolicy inventoryQuantity legacyResourceId position price requiresComponents sellableOnlineQuantity sellingPlanGroupCount showUnitPrice sku storefrontId taxCode taxable title updatedAt } } userErrors { code field message } } }";
        return _graphQlClient.Execute<QuantityRulesAddData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'quantityRulesAdd' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<QuantityRulesAddPayload?> GetValue(QuantityRulesAddVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<QuantityRulesAddData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.QuantityRulesAdd;
    }
}
