// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'subscriptionBillingCycleContractEdit' GraphQL mutation.
/// </summary>
public sealed partial class SubscriptionBillingCycleContractEditRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public SubscriptionBillingCycleContractEditRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'subscriptionBillingCycleContractEdit' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<SubscriptionBillingCycleContractEditData>> Execute(SubscriptionBillingCycleContractEditVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation SubscriptionBillingCycleContractEdit($billingCycleInput: SubscriptionBillingCycleInput!) { subscriptionBillingCycleContractEdit(billingCycleInput: $billingCycleInput) { draft { billingCycle { billingAttemptExpectedDate cycleEndAt cycleIndex cycleStartAt edited skipped status } billingPolicy { interval intervalCount maxCycles minCycles } currencyCode customAttributes { key value } customer { canDelete createdAt dataSaleOptOut displayName email firstName hasTimelineComment id lastName legacyResourceId lifetimeDuration locale multipassIdentifier note numberOfOrders phone productSubscriberStatus state tags taxExempt taxExemptions unsubscribeUrl updatedAt validEmailAddress verifiedEmail } deliveryPolicy { interval intervalCount } deliveryPrice { amount currencyCode } id nextBillingDate note originalContract { appAdminUrl createdAt currencyCode id lastBillingAttemptErrorType lastPaymentStatus lineCount nextBillingDate note revisionId status updatedAt } status } userErrors { code field message } } }";
        return _graphQlClient.Execute<SubscriptionBillingCycleContractEditData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'subscriptionBillingCycleContractEdit' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<SubscriptionBillingCycleContractEditPayload?> GetValue(SubscriptionBillingCycleContractEditVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<SubscriptionBillingCycleContractEditData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.SubscriptionBillingCycleContractEdit;
    }
}
