// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'publicationCreate' GraphQL operation.
/// </summary>
public sealed class PublicationCreateVariables
{
    [JsonPropertyName("input")]
    public PublicationCreateInput Input { get; init; } = null!;

}
