// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'productDuplicate' GraphQL operation.
/// </summary>
public sealed partial class ProductDuplicateData
{
    /// <summary>
    /// Duplicates a product.
    /// 
    /// If you need to duplicate a large product, such as one that has many
    /// [variants](https://shopify.dev/api/admin-graphql/latest/input-objects/ProductVariantInput)
    /// that are active at several
    /// [locations](https://shopify.dev/api/admin-graphql/latest/input-objects/InventoryLevelInput),
    /// you might encounter timeout errors.
    /// 
    /// To avoid these timeout errors, include the `synchronous: false` argument in this mutation to perform
    /// the duplication asynchronously.
    /// 
    /// Metafield values are not duplicated if the unique values capability is enabled.
    /// </summary>
    [JsonPropertyName("productDuplicate")]
    public ProductDuplicatePayload? ProductDuplicate { get; init; }
}
