// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'fulfillmentConstraintRuleCreate' GraphQL operation.
/// </summary>
public sealed class FulfillmentConstraintRuleCreateVariables
{
    [JsonPropertyName("functionId")]
    public string? FunctionId { get; init; }

    [JsonPropertyName("functionHandle")]
    public string? FunctionHandle { get; init; }

    [JsonPropertyName("deliveryMethodTypes")]
    public List<DeliveryMethodType> DeliveryMethodTypes { get; init; } = [];

    [JsonPropertyName("metafields")]
    public List<MetafieldInput>? Metafields { get; init; }

}
