// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'inventoryShipmentCreate' GraphQL mutation.
/// </summary>
public sealed partial class InventoryShipmentCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public InventoryShipmentCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'inventoryShipmentCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<InventoryShipmentCreateData>> Execute(InventoryShipmentCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation InventoryShipmentCreate($input: InventoryShipmentCreateInput!) { inventoryShipmentCreate(input: $input) { inventoryShipment { dateCreated dateReceived dateShipped id lineItemTotalQuantity name status totalAcceptedQuantity totalReceivedQuantity totalRejectedQuantity tracking { arrivesAt company trackingNumber trackingUrl } } userErrors { code field message } } }";
        return _graphQlClient.Execute<InventoryShipmentCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'inventoryShipmentCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<InventoryShipmentCreatePayload?> GetValue(InventoryShipmentCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<InventoryShipmentCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.InventoryShipmentCreate;
    }
}
