// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'orderInvoiceSend' GraphQL operation.
/// </summary>
public sealed partial class OrderInvoiceSendData
{
    /// <summary>
    /// Sends an email invoice for an [`Order`](https://shopify.dev/docs/api/admin-graphql/latest/objects/Order).
    /// 
    /// You can customize the email recipient, sender, and subject line using the [`email`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/orderInvoiceSend#arguments-email) argument.
    /// 
    /// &gt; Note:
    /// &gt; Use store or staff account email addresses for the [`from`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/orderInvoiceSend#arguments-email.fields.from) and [`bcc`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/orderInvoiceSend#arguments-email.fields.bcc) input fields.
    /// </summary>
    [JsonPropertyName("orderInvoiceSend")]
    public OrderInvoiceSendPayload? OrderInvoiceSend { get; init; }
}
