// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'scriptTagCreate' GraphQL operation.
/// </summary>
public sealed class ScriptTagCreateVariables
{
    [JsonPropertyName("input")]
    public ScriptTagInput Input { get; init; } = null!;

}
