// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'quantityRulesDelete' GraphQL operation.
/// </summary>
public sealed partial class QuantityRulesDeleteData
{
    /// <summary>
    /// Deletes specific quantity rules from a price list using a product variant ID.
    /// You can use the `quantityRulesDelete` mutation to delete a set of quantity rules from a price list.
    /// </summary>
    [JsonPropertyName("quantityRulesDelete")]
    public QuantityRulesDeletePayload? QuantityRulesDelete { get; init; }
}
