// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'deliveryCustomizationDelete' GraphQL operation.
/// </summary>
public sealed partial class DeliveryCustomizationDeleteData
{
    /// <summary>
    /// Creates a delivery customization.
    /// </summary>
    [JsonPropertyName("deliveryCustomizationDelete")]
    public DeliveryCustomizationDeletePayload? DeliveryCustomizationDelete { get; init; }
}
