// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'customerReplaceTaxExemptions' GraphQL operation.
/// </summary>
public sealed partial class CustomerReplaceTaxExemptionsData
{
    /// <summary>
    /// Replace tax exemptions for a customer.
    /// </summary>
    [JsonPropertyName("customerReplaceTaxExemptions")]
    public CustomerReplaceTaxExemptionsPayload? CustomerReplaceTaxExemptions { get; init; }
}
