// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'paymentCustomizationDelete' GraphQL operation.
/// </summary>
public sealed partial class PaymentCustomizationDeleteData
{
    /// <summary>
    /// Permanently deletes a payment customization. Once deleted, the customization will no longer affect which payment methods appear at checkout.
    /// </summary>
    [JsonPropertyName("paymentCustomizationDelete")]
    public PaymentCustomizationDeletePayload? PaymentCustomizationDelete { get; init; }
}
