// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields to issue arbitrary charges for app usage associated with a subscription.
/// </summary>
public sealed partial class AppUsagePricingInput
{
    /// <summary>
    /// The maximum amount of usage charges that can be incurred within a subscription billing interval.
    /// </summary>
    [JsonPropertyName("cappedAmount")]
    public MoneyInput CappedAmount { get; init; } = null!;

    /// <summary>
    /// The terms and conditions for app usage. These terms stipulate the pricing model for the charges that an app creates.
    /// </summary>
    [JsonPropertyName("terms")]
    public string Terms { get; init; } = null!;

}
