// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for heading level customizations.
/// </summary>
public sealed partial class CheckoutBrandingHeadingLevelInput
{
    /// <summary>
    /// The typography customizations used for headings.
    /// </summary>
    [JsonPropertyName("typography")]
    public CheckoutBrandingTypographyStyleInput? Typography { get; init; }

}
