// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields used to update the global customizations.
/// </summary>
public sealed partial class CheckoutBrandingGlobalInput
{
    /// <summary>
    /// Select a global corner radius setting that overrides all other [corner radii](https://shopify.dev/docs/api/admin-graphql/latest/enums/CheckoutBrandingCornerRadius)
    /// customizations.
    /// </summary>
    [JsonPropertyName("cornerRadius")]
    public CheckoutBrandingGlobalCornerRadius? CornerRadius { get; init; }

    /// <summary>
    /// The global typography customizations.
    /// </summary>
    [JsonPropertyName("typography")]
    public CheckoutBrandingTypographyStyleGlobalInput? Typography { get; init; }

}
