// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields used to update the typography customizations.
/// </summary>
public sealed partial class CheckoutBrandingTypographyStyleInput
{
    /// <summary>
    /// The font.
    /// </summary>
    [JsonPropertyName("font")]
    public CheckoutBrandingTypographyFont? Font { get; init; }

    /// <summary>
    /// The font size.
    /// </summary>
    [JsonPropertyName("size")]
    public CheckoutBrandingTypographySize? Size { get; init; }

    /// <summary>
    /// The font weight.
    /// </summary>
    [JsonPropertyName("weight")]
    public CheckoutBrandingTypographyWeight? Weight { get; init; }

    /// <summary>
    /// The letter case.
    /// </summary>
    [JsonPropertyName("letterCase")]
    public CheckoutBrandingTypographyLetterCase? LetterCase { get; init; }

    /// <summary>
    /// The kerning.
    /// </summary>
    [JsonPropertyName("kerning")]
    public CheckoutBrandingTypographyKerning? Kerning { get; init; }

}
