// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to update a custom font group.
/// </summary>
public sealed partial class CheckoutBrandingCustomFontGroupInput
{
    /// <summary>
    /// The base font.
    /// </summary>
    [JsonPropertyName("base")]
    public CheckoutBrandingCustomFontInput @Base { get; init; } = null!;

    /// <summary>
    /// The bold font.
    /// </summary>
    [JsonPropertyName("bold")]
    public CheckoutBrandingCustomFontInput Bold { get; init; } = null!;

    /// <summary>
    /// The font loading strategy.
    /// </summary>
    [JsonPropertyName("loadingStrategy")]
    public CheckoutBrandingFontLoadingStrategy? LoadingStrategy { get; init; }

}
