// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for the color schemes.
/// </summary>
public sealed partial class CheckoutBrandingColorSchemesInput
{
    /// <summary>
    /// The primary scheme. By default, it’s used for the main area of the interface.
    /// </summary>
    [JsonPropertyName("scheme1")]
    public CheckoutBrandingColorSchemeInput? Scheme1 { get; init; }

    /// <summary>
    /// The secondary scheme. By default, it’s used for secondary areas, like Checkout’s Order Summary.
    /// </summary>
    [JsonPropertyName("scheme2")]
    public CheckoutBrandingColorSchemeInput? Scheme2 { get; init; }

    /// <summary>
    /// An extra scheme available to customize more surfaces, components or specific states of the user interface.
    /// </summary>
    [JsonPropertyName("scheme3")]
    public CheckoutBrandingColorSchemeInput? Scheme3 { get; init; }

    /// <summary>
    /// An extra scheme available to customize more surfaces, components or specific states of the user interface.
    /// </summary>
    [JsonPropertyName("scheme4")]
    public CheckoutBrandingColorSchemeInput? Scheme4 { get; init; }

}
