// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields used to update the order summary container customizations.
/// </summary>
public sealed partial class CheckoutBrandingOrderSummaryInput
{
    /// <summary>
    /// The selected color scheme for the order summary container of the checkout.
    /// </summary>
    [JsonPropertyName("colorScheme")]
    public CheckoutBrandingColorSchemeSelection? ColorScheme { get; init; }

    /// <summary>
    /// The background image of the order summary container (must not be of SVG format).
    /// </summary>
    [JsonPropertyName("backgroundImage")]
    public CheckoutBrandingImageInput? BackgroundImage { get; init; }

    /// <summary>
    /// Divider style and visibility on the order summary container.
    /// </summary>
    [JsonPropertyName("divider")]
    public CheckoutBrandingContainerDividerInput? Divider { get; init; }

    /// <summary>
    /// The settings for the order summary sections.
    /// </summary>
    [JsonPropertyName("section")]
    public CheckoutBrandingOrderSummarySectionInput? Section { get; init; }

}
