// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a rule to associate with a collection.
/// </summary>
public sealed partial class CollectionRuleInput
{
    /// <summary>
    /// The attribute that the rule focuses on. For example, `title` or `product_type`.
    /// </summary>
    [JsonPropertyName("column")]
    public CollectionRuleColumn Column { get; init; }

    /// <summary>
    /// The type of operator that the rule is based on. For example, `equals`, `contains`, or `not_equals`.
    /// </summary>
    [JsonPropertyName("relation")]
    public CollectionRuleRelation Relation { get; init; }

    /// <summary>
    /// The value that the operator is applied to. For example, `Hats`.
    /// </summary>
    [JsonPropertyName("condition")]
    public string Condition { get; init; } = null!;

    /// <summary>
    /// The object ID that points to additional attributes for the collection rule.
    /// This is only required when using metafield definition rules.
    /// </summary>
    [JsonPropertyName("conditionObjectId")]
    public string? ConditionObjectId { get; init; }

}
