// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for specifying a collection to publish and the sales channels to publish it to.
/// </summary>
public sealed partial class CollectionPublishInput
{
    /// <summary>
    /// The collection to create or update publications for.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The channels where the collection will be published.
    /// </summary>
    [JsonPropertyName("collectionPublications")]
    public List<CollectionPublicationInput> CollectionPublications { get; init; } = [];

}
