// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The context data that determines the publication status of a product.
/// </summary>
public sealed partial class ContextualPublicationContext
{
    /// <summary>
    /// The country code used to fetch country-specific publication.
    /// </summary>
    [JsonPropertyName("country")]
    public CountryCode? Country { get; init; }

    /// <summary>
    /// The company location ID used to fetch company-specific publication.
    /// </summary>
    [JsonPropertyName("companyLocationId")]
    public string? CompanyLocationId { get; init; }

    /// <summary>
    /// The Location ID used to fetch the publication status of a product.
    /// </summary>
    [JsonPropertyName("locationId")]
    public string? LocationId { get; init; }

}
