// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a price-based condition of a delivery method definition.
/// </summary>
public sealed partial class DeliveryPriceConditionInput
{
    /// <summary>
    /// The monetary value to compare the price of an order to.
    /// </summary>
    [JsonPropertyName("criteria")]
    public MoneyInput? Criteria { get; init; }

    /// <summary>
    /// The operator to use for comparison.
    /// </summary>
    [JsonPropertyName("operator")]
    public DeliveryConditionOperator? @Operator { get; init; }

}
