// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a method definition.
/// </summary>
public sealed partial class DeliveryMethodDefinitionInput
{
    /// <summary>
    /// A globally-unique ID of the method definition. Use only when updating a method definition.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The name of the method definition.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// The description of the method definition.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Whether to use this method definition during rate calculation.
    /// </summary>
    [JsonPropertyName("active")]
    public bool? Active { get; init; }

    /// <summary>
    /// A rate definition to apply to the method definition.
    /// </summary>
    [JsonPropertyName("rateDefinition")]
    public DeliveryRateDefinitionInput? RateDefinition { get; init; }

    /// <summary>
    /// A participant to apply to the method definition.
    /// </summary>
    [JsonPropertyName("participant")]
    public DeliveryParticipantInput? Participant { get; init; }

    /// <summary>
    /// A list of weight conditions on the method definition.
    /// </summary>
    [JsonPropertyName("weightConditionsToCreate")]
    public List<DeliveryWeightConditionInput>? WeightConditionsToCreate { get; init; }

    /// <summary>
    /// A list of price conditions on the method definition.
    /// </summary>
    [JsonPropertyName("priceConditionsToCreate")]
    public List<DeliveryPriceConditionInput>? PriceConditionsToCreate { get; init; }

    /// <summary>
    /// A list of conditions to update on the method definition.
    /// </summary>
    [JsonPropertyName("conditionsToUpdate")]
    public List<DeliveryUpdateConditionInput>? ConditionsToUpdate { get; init; }

}
