// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields representing the components of a line item.
/// </summary>
public sealed partial class DraftOrderLineItemComponentInput
{
    /// <summary>
    /// The ID of the product variant corresponding to the component.
    /// </summary>
    [JsonPropertyName("variantId")]
    public string? VariantId { get; init; }

    /// <summary>
    /// The quantity of the component.
    /// </summary>
    [JsonPropertyName("quantity")]
    public int Quantity { get; init; }

    /// <summary>
    /// The UUID of the component. Must be unique and consistent across requests.
    /// This field is mandatory in order to manipulate drafts with parent line items.
    /// </summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; init; }

}
