// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for marking fulfillment order line items as ready for pickup.
/// </summary>
public sealed partial class FulfillmentOrderLineItemsPreparedForPickupInput
{
    /// <summary>
    /// The fulfillment orders associated with the line items which are ready to be picked up by a customer.
    /// </summary>
    [JsonPropertyName("lineItemsByFulfillmentOrder")]
    public List<PreparedFulfillmentOrderLineItemsInput> LineItemsByFulfillmentOrder { get; init; } = [];

}
