// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a gift card credit transaction.
/// </summary>
public sealed partial class GiftCardCreditInput
{
    /// <summary>
    /// The amount to credit the gift card.
    /// </summary>
    [JsonPropertyName("creditAmount")]
    public MoneyInput CreditAmount { get; init; } = null!;

    /// <summary>
    /// A note about the credit.
    /// </summary>
    [JsonPropertyName("note")]
    public string? Note { get; init; }

    /// <summary>
    /// The date and time the credit was processed. Defaults to current date and time.
    /// </summary>
    [JsonPropertyName("processedAt")]
    public DateTimeOffset? ProcessedAt { get; init; }

}
