// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields to receive an item on an inventory shipment.
/// </summary>
public sealed partial class InventoryShipmentReceiveItemInput
{
    /// <summary>
    /// The shipment line item ID to be received.
    /// </summary>
    [JsonPropertyName("shipmentLineItemId")]
    public string ShipmentLineItemId { get; init; } = null!;

    /// <summary>
    /// The quantity for the item to be received.
    /// </summary>
    [JsonPropertyName("quantity")]
    public int Quantity { get; init; }

    /// <summary>
    /// The reason for received item.
    /// </summary>
    [JsonPropertyName("reason")]
    public InventoryShipmentReceiveLineItemReason Reason { get; init; }

}
