// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields used to update a market.
/// </summary>
public sealed partial class MarketUpdateInput
{
    /// <summary>
    /// The name of the market. Not shown to customers.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// A unique identifier for the market. For example `"ca"`.
    /// </summary>
    [JsonPropertyName("handle")]
    public string? Handle { get; init; }

    /// <summary>
    /// Whether the market is enabled to receive visitors and sales. **Note**: Regions in
    /// inactive markets cannot be selected on the storefront or in checkout.
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }

    /// <summary>
    /// The conditions to update.
    /// </summary>
    [JsonPropertyName("conditions")]
    public MarketConditionsUpdateInput? Conditions { get; init; }

    /// <summary>
    /// Catalog IDs to include in the market.
    /// </summary>
    [JsonPropertyName("catalogsToAdd")]
    public List<string>? CatalogsToAdd { get; init; }

    /// <summary>
    /// Catalog IDs to remove from the market.
    /// </summary>
    [JsonPropertyName("catalogsToDelete")]
    public List<string>? CatalogsToDelete { get; init; }

    /// <summary>
    /// The web presences to add to the market.
    /// </summary>
    [JsonPropertyName("webPresencesToAdd")]
    public List<string>? WebPresencesToAdd { get; init; }

    /// <summary>
    /// The web presences to remove from the market.
    /// </summary>
    [JsonPropertyName("webPresencesToDelete")]
    public List<string>? WebPresencesToDelete { get; init; }

    /// <summary>
    /// Whether to update duplicate market's status to draft.
    /// </summary>
    [JsonPropertyName("makeDuplicateRegionMarketsDraft")]
    public bool? MakeDuplicateRegionMarketsDraft { get; init; }

    /// <summary>
    /// Whether to update duplicate region or wildcard markets' status to draft.
    /// </summary>
    [JsonPropertyName("makeDuplicateUniqueMarketsDraft")]
    public bool? MakeDuplicateUniqueMarketsDraft { get; init; }

    /// <summary>
    /// The status of the market.
    /// </summary>
    [JsonPropertyName("status")]
    public MarketStatus? Status { get; init; }

    /// <summary>
    /// Currency settings for the market.
    /// </summary>
    [JsonPropertyName("currencySettings")]
    public MarketCurrencySettingsUpdateInput? CurrencySettings { get; init; }

    /// <summary>
    /// Remove any currency settings that are defined for the market.
    /// </summary>
    [JsonPropertyName("removeCurrencySettings")]
    public bool? RemoveCurrencySettings { get; init; }

    /// <summary>
    /// The price inclusions to remove from the market.
    /// </summary>
    [JsonPropertyName("removePriceInclusions")]
    public bool? RemovePriceInclusions { get; init; }

    /// <summary>
    /// The strategy used to determine how prices are displayed to the customer.
    /// </summary>
    [JsonPropertyName("priceInclusions")]
    public MarketPriceInclusionsInput? PriceInclusions { get; init; }

}
