// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields and values for creating or updating a market localization.
/// </summary>
public sealed partial class MarketLocalizationRegisterInput
{
    /// <summary>
    /// The ID of the market that the localization is specific to.
    /// </summary>
    [JsonPropertyName("marketId")]
    public string MarketId { get; init; } = null!;

    /// <summary>
    /// A reference to the value being localized on the resource that this market localization belongs to.
    /// </summary>
    [JsonPropertyName("key")]
    public string Key { get; init; } = null!;

    /// <summary>
    /// The value of the market localization.
    /// </summary>
    [JsonPropertyName("value")]
    public string Value { get; init; } = null!;

    /// <summary>
    /// A hash digest representation of the content being localized.
    /// </summary>
    [JsonPropertyName("marketLocalizableContentDigest")]
    public string MarketLocalizableContentDigest { get; init; } = null!;

}
