// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for publishable capability to adjust visibility on channels.
/// </summary>
public sealed partial class MetaobjectCapabilityDataPublishableInput
{
    /// <summary>
    /// The visibility status of this metaobject across all channels.
    /// </summary>
    [JsonPropertyName("status")]
    public MetaobjectStatus Status { get; init; }

}
