// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for enabling and disabling the admin filterable capability.
/// </summary>
public sealed partial class MetafieldCapabilityAdminFilterableInput
{
    /// <summary>
    /// Indicates whether the capability should be enabled or disabled.
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

}
