// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for creating capabilities on a metaobject field definition.
/// </summary>
public sealed partial class MetaobjectFieldDefinitionCapabilityCreateInput
{
    /// <summary>
    /// The input for configuring the admin filterable capability.
    /// </summary>
    [JsonPropertyName("adminFilterable")]
    public MetaobjectFieldCapabilityAdminFilterableInput? AdminFilterable { get; init; }

}
