// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for dimensions of an object.
/// </summary>
public sealed partial class ObjectDimensionsInput
{
    /// <summary>
    /// The length in `unit`s.
    /// </summary>
    [JsonPropertyName("length")]
    public double Length { get; init; }

    /// <summary>
    /// The width in `unit`s.
    /// </summary>
    [JsonPropertyName("width")]
    public double Width { get; init; }

    /// <summary>
    /// The height in `unit`s.
    /// </summary>
    [JsonPropertyName("height")]
    public double Height { get; init; }

    /// <summary>
    /// Unit of measurement for `length`, `width`, and `height`.
    /// </summary>
    [JsonPropertyName("unit")]
    public LengthUnit Unit { get; init; }

}
