// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for reordering a product option and/or its values.
/// </summary>
public sealed partial class OptionReorderInput
{
    /// <summary>
    /// Specifies the product option to reorder by ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Specifies the product option to reorder by name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Values associated with the option.
    /// </summary>
    [JsonPropertyName("values")]
    public List<OptionValueReorderInput>? Values { get; init; }

}
