// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for reordering a product option value.
/// </summary>
public sealed partial class OptionValueReorderInput
{
    /// <summary>
    /// Specifies the product option value by ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Specifies the product option value by name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

}
