// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for updating a product option.
/// </summary>
public sealed partial class OptionUpdateInput
{
    /// <summary>
    /// Specifies the product option to update.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// Name of the option.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Position of the option.
    /// </summary>
    [JsonPropertyName("position")]
    public int? Position { get; init; }

    /// <summary>
    /// Specifies the metafield the option is linked to.
    /// </summary>
    [JsonPropertyName("linkedMetafield")]
    public LinkedMetafieldUpdateInput? LinkedMetafield { get; init; }

}
