// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to create a product option value.
/// </summary>
public sealed partial class OptionValueCreateInput
{
    /// <summary>
    /// Value associated with an option.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Metafield value associated with an option.
    /// </summary>
    [JsonPropertyName("linkedMetafieldValue")]
    public string? LinkedMetafieldValue { get; init; }

}
