// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for creating or updating a product option.
/// </summary>
public sealed partial class OptionSetInput
{
    /// <summary>
    /// Specifies the product option to update.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Name of the option.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Position of the option.
    /// </summary>
    [JsonPropertyName("position")]
    public int? Position { get; init; }

    /// <summary>
    /// Value associated with an option.
    /// </summary>
    [JsonPropertyName("values")]
    public List<OptionValueSetInput>? Values { get; init; }

    /// <summary>
    /// Specifies the metafield the option is linked to.
    /// </summary>
    [JsonPropertyName("linkedMetafield")]
    public LinkedMetafieldCreateInput? LinkedMetafield { get; init; }

}
