// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for specifying the order to mark as paid.
/// </summary>
public sealed partial class OrderMarkAsPaidInput
{
    /// <summary>
    /// The ID of the order to mark as paid.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

}
