// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields used to add a discount during an order edit.
/// </summary>
public sealed partial class OrderEditAppliedDiscountInput
{
    /// <summary>
    /// The description of the discount.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// The value of the discount as a fixed amount.
    /// </summary>
    [JsonPropertyName("fixedValue")]
    public MoneyInput? FixedValue { get; init; }

    /// <summary>
    /// The value of the discount as a percentage.
    /// </summary>
    [JsonPropertyName("percentValue")]
    public double? PercentValue { get; init; }

}
