// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a discount code to apply to an order. Only one type of discount can be applied to an order.
/// </summary>
public sealed partial class OrderCreateDiscountCodeInput
{
    /// <summary>
    /// A percentage discount code applied to the line items on the order.
    /// </summary>
    [JsonPropertyName("itemPercentageDiscountCode")]
    public OrderCreatePercentageDiscountCodeAttributesInput? ItemPercentageDiscountCode { get; init; }

    /// <summary>
    /// A fixed amount discount code applied to the line items on the order.
    /// </summary>
    [JsonPropertyName("itemFixedDiscountCode")]
    public OrderCreateFixedDiscountCodeAttributesInput? ItemFixedDiscountCode { get; init; }

    /// <summary>
    /// A free shipping discount code applied to the shipping on an order.
    /// </summary>
    [JsonPropertyName("freeShippingDiscountCode")]
    public OrderCreateFreeShippingDiscountCodeAttributesInput? FreeShippingDiscountCode { get; init; }

}
