// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a risk assessment fact.
/// </summary>
public sealed partial class OrderRiskAssessmentFactInput
{
    /// <summary>
    /// Indicates whether the fact contributes negatively, neutrally, or positively to risk.
    /// </summary>
    [JsonPropertyName("sentiment")]
    public RiskFactSentiment Sentiment { get; init; }

    /// <summary>
    /// Descriptions longer than 256 characters are truncated.
    /// </summary>
    [JsonPropertyName("description")]
    public string Description { get; init; } = null!;

}
