// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a note attribute for an order.
/// </summary>
public sealed partial class OrderCreateCustomAttributeInput
{
    /// <summary>
    /// The key or name of the custom attribute.
    /// </summary>
    [JsonPropertyName("key")]
    public string Key { get; init; } = null!;

    /// <summary>
    /// The value of the custom attribute.
    /// </summary>
    [JsonPropertyName("value")]
    public string Value { get; init; } = null!;

}
