// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields used to create a payment terms.
/// </summary>
public sealed partial class PaymentTermsCreateInput
{
    /// <summary>
    /// Specifies the payment terms template ID used to generate payment terms.
    /// </summary>
    [JsonPropertyName("paymentTermsTemplateId")]
    public string PaymentTermsTemplateId { get; init; } = null!;

    /// <summary>
    /// Specifies the payment schedules for the payment terms.
    /// </summary>
    [JsonPropertyName("paymentSchedules")]
    public List<PaymentScheduleInput>? PaymentSchedules { get; init; }

}
