// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for providing the fields and values to use when creating or updating a fixed price list price.
/// </summary>
public sealed partial class PriceListPriceInput
{
    /// <summary>
    /// The product variant ID associated with the price list price.
    /// </summary>
    [JsonPropertyName("variantId")]
    public string VariantId { get; init; } = null!;

    /// <summary>
    /// The price of the product variant on this price list.
    /// </summary>
    [JsonPropertyName("price")]
    public MoneyInput Price { get; init; } = null!;

    /// <summary>
    /// The compare-at price of the product variant on this price list.
    /// </summary>
    [JsonPropertyName("compareAtPrice")]
    public MoneyInput? CompareAtPrice { get; init; }

}
