// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to set inventory quantities using `productSet` mutation.
/// </summary>
public sealed partial class ProductSetInventoryInput
{
    /// <summary>
    /// The ID of the location of the inventory quantity being set.
    /// </summary>
    [JsonPropertyName("locationId")]
    public string LocationId { get; init; } = null!;

    /// <summary>
    /// The name of the inventory quantity being set. Must be one of `available` or `on_hand`.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The values to which each quantities will be set.
    /// </summary>
    [JsonPropertyName("quantity")]
    public int Quantity { get; init; }

}
