// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for specifying a product to publish and the channels to publish it to.
/// </summary>
public sealed partial class ProductPublishInput
{
    /// <summary>
    /// The product to create or update publications for.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The publication that the product is published to.
    /// </summary>
    [JsonPropertyName("productPublications")]
    public List<ProductPublicationInput> ProductPublications { get; init; } = [];

}
