// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to create or update a product via ProductSet mutation.
/// </summary>
public sealed partial class ProductSetInput
{
    /// <summary>
    /// The description of the product, with HTML tags.
    /// For example, the description might include bold `&lt;strong&gt;&lt;/strong&gt;` and italic `&lt;i&gt;&lt;/i&gt;` text.
    /// </summary>
    [JsonPropertyName("descriptionHtml")]
    public string? DescriptionHtml { get; init; }

    /// <summary>
    /// A unique, human-readable string that's used to identify the product in URLs. A handle can contain letters, hyphens (`-`), and numbers, but no spaces.
    /// If no handle is explicitly provided, then the title is used to construct the product's handle.
    /// For example, if a product is titled "Black Sunglasses" and no handle is provided, then the handle `black-sunglasses` is generated (unless that handle
    /// is already taken, in which case a suffix is added to make the handle unique).
    /// </summary>
    [JsonPropertyName("handle")]
    public string? Handle { get; init; }

    /// <summary>
    /// The [SEO title and description](https://help.shopify.com/manual/promoting-marketing/seo/adding-keywords)
    /// that are associated with a product.
    /// </summary>
    [JsonPropertyName("seo")]
    public SEOInput? Seo { get; init; }

    /// <summary>
    /// The [product type](https://help.shopify.com/manual/products/details/product-type)
    /// that merchants define.
    /// </summary>
    [JsonPropertyName("productType")]
    public string? ProductType { get; init; }

    /// <summary>
    /// A list of searchable keywords that are
    /// associated with the product. For example, a merchant might apply the `sports`
    /// and `summer` tags to products that are associated with sportwear for summer.
    /// 
    /// Updating `tags` overwrites any existing tags that were previously added to the product.
    /// To add new tags without overwriting existing tags, use the
    /// [`tagsAdd`](https://shopify.dev/api/admin-graphql/latest/mutations/tagsadd)
    /// mutation.
    /// </summary>
    [JsonPropertyName("tags")]
    public List<string>? Tags { get; init; }

    /// <summary>
    /// The [theme template](https://shopify.dev/docs/storefronts/themes/architecture/templates) that's used when customers view a product in a store.
    /// </summary>
    [JsonPropertyName("templateSuffix")]
    public string? TemplateSuffix { get; init; }

    /// <summary>
    /// The [theme template](https://shopify.dev/docs/storefronts/themes/architecture/templates) that's used when customers view a gift card in a store.
    /// </summary>
    [JsonPropertyName("giftCardTemplateSuffix")]
    public string? GiftCardTemplateSuffix { get; init; }

    /// <summary>
    /// The name for the product that displays to customers. If no handle is explicitly provided, then the title is used to construct the product's handle.
    /// For example, if a product is titled "Black Sunglasses" and no handle is provided, then the handle `black-sunglasses` is generated.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// The name of the product's vendor.
    /// </summary>
    [JsonPropertyName("vendor")]
    public string? Vendor { get; init; }

    /// <summary>
    /// The ID of the [category](https://shopify.github.io/product-taxonomy/releases/unstable/?categoryId=sg-4-17-2-17)
    /// that's associated with the product.
    /// </summary>
    [JsonPropertyName("category")]
    public string? Category { get; init; }

    /// <summary>
    /// Whether the product is a gift card.
    /// </summary>
    [JsonPropertyName("giftCard")]
    public bool? GiftCard { get; init; }

    /// <summary>
    /// Whether a redirect is required after a new handle has been provided.
    /// If `true`, then the old handle is redirected to the new one automatically.
    /// </summary>
    [JsonPropertyName("redirectNewHandle")]
    public bool? RedirectNewHandle { get; init; }

    /// <summary>
    /// The status of the product.
    /// </summary>
    [JsonPropertyName("status")]
    public ProductStatus? Status { get; init; }

    /// <summary>
    /// The IDs of collections that this product will be a member of.
    /// </summary>
    [JsonPropertyName("collections")]
    public List<string>? Collections { get; init; }

    /// <summary>
    /// The metafields to associate with this product.
    /// 
    /// Complexity cost: 0.4 per metafield.
    /// </summary>
    [JsonPropertyName("metafields")]
    public List<MetafieldInput>? Metafields { get; init; }

    /// <summary>
    /// The files to associate with the product.
    /// 
    /// Complexity cost: 1.9 per file.
    /// </summary>
    [JsonPropertyName("files")]
    public List<FileSetInput>? Files { get; init; }

    /// <summary>
    /// List of custom product options and option values (maximum of 3 per product).
    /// </summary>
    [JsonPropertyName("productOptions")]
    public List<OptionSetInput>? ProductOptions { get; init; }

    /// <summary>
    /// The product's ID.
    /// 
    /// If you're creating a product, then you don't need to pass the `id` as input to the
    /// [`productCreate`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/productCreate) mutation.
    /// If you're updating a product, then you do need to pass the `id` as input to the
    /// [`productUpdate`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/productUpdate) mutation
    /// to identify which product you want to update.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// A list of variants associated with the product.
    /// 
    /// Complexity cost: 0.2 per variant.
    /// </summary>
    [JsonPropertyName("variants")]
    public List<ProductVariantSetInput>? Variants { get; init; }

    /// <summary>
    /// Whether the product can only be purchased with a selling plan (subscription). Products that are sold exclusively on subscription can only be created on online stores. If set to `true` on an already existing product, then the product will be marked unavailable on channels that don't support subscriptions.
    /// </summary>
    [JsonPropertyName("requiresSellingPlan")]
    public bool? RequiresSellingPlan { get; init; }

    /// <summary>
    /// The input field to enable an app to provide additional product features.
    /// For example, you can specify
    /// [`bundles: true`](https://shopify.dev/docs/api/admin-graphql/latest/input-objects/ProductClaimOwnershipInput#field-bundles)
    /// in the `claimOwnership` field to let an app add a
    /// [product configuration extension](https://shopify.dev/docs/apps/build/product-merchandising/bundles/product-configuration-extension/add-merchant-config-ui).
    /// </summary>
    [JsonPropertyName("claimOwnership")]
    public ProductClaimOwnershipInput? ClaimOwnership { get; init; }

    /// <summary>
    /// The role of the product in a product grouping. It can only be set during creation.
    /// </summary>
    [JsonPropertyName("combinedListingRole")]
    public CombinedListingsRole? CombinedListingRole { get; init; }

}
