// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to publish a resource.
/// </summary>
public sealed partial class PublicationInput
{
    /// <summary>
    /// ID of the channel.
    /// </summary>
    [JsonPropertyName("channelId")]
    public string? ChannelId { get; init; }

    /// <summary>
    /// ID of the publication.
    /// </summary>
    [JsonPropertyName("publicationId")]
    public string? PublicationId { get; init; }

    /// <summary>
    /// The date and time that the resource was published. Setting this to a date in the future will schedule the resource to be published. Only online store channels support future publishing. This field has no effect if you include it in the `publishableUnpublish` mutation.
    /// </summary>
    [JsonPropertyName("publishDate")]
    public DateTimeOffset? PublishDate { get; init; }

}
