// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a purchasing company, which is a combination of company, company contact, and company location.
/// </summary>
public sealed partial class PurchasingCompanyInput
{
    /// <summary>
    /// ID of the company.
    /// </summary>
    [JsonPropertyName("companyId")]
    public string CompanyId { get; init; } = null!;

    /// <summary>
    /// ID of the company contact.
    /// </summary>
    [JsonPropertyName("companyContactId")]
    public string CompanyContactId { get; init; } = null!;

    /// <summary>
    /// ID of the company location.
    /// </summary>
    [JsonPropertyName("companyLocationId")]
    public string CompanyLocationId { get; init; } = null!;

}
