// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for the shipping cost to refund.
/// </summary>
public sealed partial class RefundShippingInput
{
    /// <summary>
    /// The input fields required to refund shipping cost, in the presentment currency of the order.
    /// This overrides the `fullRefund` argument.
    /// This field defaults to 0.00 when not provided and when the `fullRefund` argument is false.
    /// </summary>
    [JsonPropertyName("shippingRefundAmount")]
    public MoneyInput? ShippingRefundAmount { get; init; }

    /// <summary>
    /// Whether to refund the full shipping amount.
    /// </summary>
    [JsonPropertyName("fullRefund")]
    public bool? FullRefund { get; init; }

}
