// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a remote Braintree customer payment profile.
/// </summary>
public sealed partial class RemoteBraintreePaymentMethodInput
{
    /// <summary>
    /// The `customer_id` value from the Braintree API.
    /// </summary>
    [JsonPropertyName("customerId")]
    public string CustomerId { get; init; } = null!;

    /// <summary>
    /// The `payment_method_token` value from the Braintree API. Starting on 2025,
    /// payment_method_token will become mandatory for all API versions.
    /// </summary>
    [JsonPropertyName("paymentMethodToken")]
    public string? PaymentMethodToken { get; init; }

}
