// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields to create a saved search.
/// </summary>
public sealed partial class SavedSearchCreateInput
{
    /// <summary>
    /// The type of resource this saved search is searching in.
    /// </summary>
    [JsonPropertyName("resourceType")]
    public SearchResultType ResourceType { get; init; }

    /// <summary>
    /// A descriptive name of the saved search.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// The query string of a saved search. This includes search terms and filters.
    /// </summary>
    [JsonPropertyName("query")]
    public string Query { get; init; } = null!;

}
