// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to create or update an inventory policy.
/// </summary>
public sealed partial class SellingPlanInventoryPolicyInput
{
    /// <summary>
    /// When to reserve inventory for the order. The value must be ON_FULFILLMENT or ON_SALE.
    /// </summary>
    [JsonPropertyName("reserve")]
    public SellingPlanReserve? Reserve { get; init; }

}
