// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for a storefront access token.
/// </summary>
public sealed partial class StorefrontAccessTokenInput
{
    /// <summary>
    /// A title for the storefront access token.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = null!;

}
