// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields to select SubscriptionBillingCycle by either date or index. Both past and future billing cycles can be selected.
/// </summary>
public sealed partial class SubscriptionBillingCycleSelector
{
    /// <summary>
    /// Returns a billing cycle by index.
    /// </summary>
    [JsonPropertyName("index")]
    public int? Index { get; init; }

    /// <summary>
    /// Returns a billing cycle by date.
    /// </summary>
    [JsonPropertyName("date")]
    public DateTimeOffset? Date { get; init; }

}
