// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to create a Subscription Contract.
/// </summary>
public sealed partial class SubscriptionContractAtomicCreateInput
{
    /// <summary>
    /// The ID of the customer to associate with the subscription contract.
    /// </summary>
    [JsonPropertyName("customerId")]
    public string CustomerId { get; init; } = null!;

    /// <summary>
    /// The next billing date for the subscription contract.This field is independent of billing cycles.It stores metadata set by the apps, and thus not managed by Shopify.It can be queried from subscriptionContract.nextBillingDate.
    /// </summary>
    [JsonPropertyName("nextBillingDate")]
    public DateTimeOffset NextBillingDate { get; init; }

    /// <summary>
    /// The currency used for the subscription contract.
    /// </summary>
    [JsonPropertyName("currencyCode")]
    public CurrencyCode CurrencyCode { get; init; }

    /// <summary>
    /// The attributes used as input for the Subscription Draft.
    /// </summary>
    [JsonPropertyName("contract")]
    public SubscriptionDraftInput Contract { get; init; } = null!;

    /// <summary>
    /// A list of new Subscription Lines.
    /// </summary>
    [JsonPropertyName("lines")]
    public List<SubscriptionAtomicLineInput> Lines { get; init; } = [];

    /// <summary>
    /// A list of discount redeem codes to apply to the subscription contract.
    /// </summary>
    [JsonPropertyName("discountCodes")]
    public List<string>? DiscountCodes { get; init; }

}
