// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for specifying the subscription contract and selecting the associated billing cycle.
/// </summary>
public sealed partial class SubscriptionBillingCycleInput
{
    /// <summary>
    /// The ID of the subscription contract associated with the billing cycle.
    /// </summary>
    [JsonPropertyName("contractId")]
    public string ContractId { get; init; } = null!;

    /// <summary>
    /// Selects the billing cycle by date or index.
    /// </summary>
    [JsonPropertyName("selector")]
    public SubscriptionBillingCycleSelector Selector { get; init; } = null!;

}
