// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for parameters to modify the schedule of a specific billing cycle.
/// </summary>
public sealed partial class SubscriptionBillingCycleScheduleEditInput
{
    /// <summary>
    /// Sets the skip status for the billing cycle.
    /// </summary>
    [JsonPropertyName("skip")]
    public bool? Skip { get; init; }

    /// <summary>
    /// Sets the expected billing date for the billing cycle.
    /// </summary>
    [JsonPropertyName("billingDate")]
    public DateTimeOffset? BillingDate { get; init; }

    /// <summary>
    /// The reason for editing.
    /// </summary>
    [JsonPropertyName("reason")]
    public SubscriptionBillingCycleScheduleEditInputScheduleEditReason Reason { get; init; }

}
