// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for the subscription lines the discount applies on.
/// </summary>
public sealed partial class SubscriptionManualDiscountEntitledLinesInput
{
    /// <summary>
    /// Specify whether the subscription discount will apply on all subscription lines.
    /// </summary>
    [JsonPropertyName("all")]
    public bool? All { get; init; }

    /// <summary>
    /// The ID of the lines to add to or remove from the subscription discount.
    /// </summary>
    [JsonPropertyName("lines")]
    public SubscriptionManualDiscountLinesInput? Lines { get; init; }

}
