// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for an exchange line item.
/// </summary>
public sealed partial class SuggestedOutcomeExchangeLineItemInput
{
    /// <summary>
    /// The ID of the exchange line item.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    /// <summary>
    /// The quantity of the exchange line item.
    /// </summary>
    [JsonPropertyName("quantity")]
    public int Quantity { get; init; }

}
