// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields for the file copy.
/// </summary>
public sealed partial class ThemeFilesCopyFileInput
{
    /// <summary>
    /// The new file where the content is copied to.
    /// </summary>
    [JsonPropertyName("dstFilename")]
    public string DstFilename { get; init; } = null!;

    /// <summary>
    /// The source file to copy from.
    /// </summary>
    [JsonPropertyName("srcFilename")]
    public string SrcFilename { get; init; } = null!;

}
