// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The input fields required to create or modify a product variant's option value.
/// </summary>
public sealed partial class VariantOptionValueInput
{
    /// <summary>
    /// Specifies the product option value by ID.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Specifies the product option value by name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// Metafield value associated with an option.
    /// </summary>
    [JsonPropertyName("linkedMetafieldValue")]
    public string? LinkedMetafieldValue { get; init; }

    /// <summary>
    /// Specifies the product option by ID.
    /// </summary>
    [JsonPropertyName("optionId")]
    public string? OptionId { get; init; }

    /// <summary>
    /// Specifies the product option by name.
    /// </summary>
    [JsonPropertyName("optionName")]
    public string? OptionName { get; init; }

}
