// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'marketingActivityCreate' GraphQL operation.
/// </summary>
public sealed partial class MarketingActivityCreateData
{
    /// <summary>
    /// Create new marketing activity. Marketing activity app extensions are deprecated and will be removed in the near future.
    /// </summary>
    [JsonPropertyName("marketingActivityCreate")]
    public MarketingActivityCreatePayload? MarketingActivityCreate { get; init; }
}
