// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'fulfillmentOrderReschedule' GraphQL operation.
/// </summary>
public sealed class FulfillmentOrderRescheduleVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

    [JsonPropertyName("fulfillAt")]
    public DateTimeOffset FulfillAt { get; init; }

}
