// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'discountAutomaticFreeShippingUpdate' GraphQL mutation.
/// </summary>
public sealed partial class DiscountAutomaticFreeShippingUpdateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public DiscountAutomaticFreeShippingUpdateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'discountAutomaticFreeShippingUpdate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<DiscountAutomaticFreeShippingUpdateData>> Execute(DiscountAutomaticFreeShippingUpdateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation DiscountAutomaticFreeShippingUpdate($id: ID!, $freeShippingAutomaticDiscount: DiscountAutomaticFreeShippingInput!) { discountAutomaticFreeShippingUpdate(id: $id, freeShippingAutomaticDiscount: $freeShippingAutomaticDiscount) { automaticDiscountNode { id } userErrors { code extraInfo field message } } }";
        return _graphQlClient.Execute<DiscountAutomaticFreeShippingUpdateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'discountAutomaticFreeShippingUpdate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<DiscountAutomaticFreeShippingUpdatePayload?> GetValue(DiscountAutomaticFreeShippingUpdateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<DiscountAutomaticFreeShippingUpdateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.DiscountAutomaticFreeShippingUpdate;
    }
}
