// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The possible categories of an app installation, based on their purpose
/// or the environment they can run in.
/// </summary>
public enum AppInstallationCategory
{
    /// <summary>
    /// Apps that serve as channels through which sales are made, such as the online store.
    /// </summary>
    CHANNEL,

    /// <summary>
    /// Apps that can be used in the POS mobile client.
    /// </summary>
    POSEMBEDDED

}
