// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The status of the app subscription.
/// </summary>
public enum AppSubscriptionStatus
{
    /// <summary>
    /// The app subscription is pending approval by the merchant.
    /// </summary>
    PENDING,

    /// <summary>
    /// The app subscription has been approved by the merchant and is ready to be activated by the app.
    /// </summary>
    ACCEPTED,

    /// <summary>
    /// The app subscription has been approved by the merchant. Active app subscriptions are billed to the shop. After payment, partners receive payouts.
    /// </summary>
    ACTIVE,

    /// <summary>
    /// The app subscription was declined by the merchant. This is a terminal state.
    /// </summary>
    DECLINED,

    /// <summary>
    /// The app subscription wasn't approved by the merchant within two days of being created. This is a terminal state.
    /// </summary>
    EXPIRED,

    /// <summary>
    /// The app subscription is on hold due to non-payment. The subscription re-activates after payments resume.
    /// </summary>
    FROZEN,

    /// <summary>
    /// The app subscription was cancelled by the app. This could be caused by the app being uninstalled, a new app subscription being activated, or a direct cancellation by the app. This is a terminal state.
    /// </summary>
    CANCELLED

}
