// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The set of valid sort keys for the AppUsageRecord query.
/// </summary>
public enum AppUsageRecordSortKeys
{
    /// <summary>
    /// Sort by the `created_at` value.
    /// </summary>
    CREATEDAT,

    /// <summary>
    /// Sort by the `id` value.
    /// </summary>
    ID

}
