// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `ArticleDeleteUserError`.
/// </summary>
public enum ArticleDeleteUserErrorCode
{
    /// <summary>
    /// The record with the ID used as the input value couldn't be found.
    /// </summary>
    NOTFOUND

}
