// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `BillingAttemptUserError`.
/// </summary>
public enum BillingAttemptUserErrorCode
{
    /// <summary>
    /// The input value is invalid.
    /// </summary>
    INVALID,

    /// <summary>
    /// The input value is blank.
    /// </summary>
    BLANK,

    /// <summary>
    /// Subscription contract does not exist.
    /// </summary>
    CONTRACTNOTFOUND,

    /// <summary>
    /// Origin time cannot be before the contract creation time.
    /// </summary>
    ORIGINTIMEBEFORECONTRACTCREATION,

    /// <summary>
    /// Billing cycle selector cannot select upcoming billing cycle past limit.
    /// </summary>
    UPCOMINGCYCLELIMITEXCEEDED,

    /// <summary>
    /// Billing cycle selector cannot select billing cycle outside of index range.
    /// </summary>
    CYCLEINDEXOUTOFRANGE,

    /// <summary>
    /// Billing cycle selector cannot select billing cycle outside of start date range.
    /// </summary>
    CYCLESTARTDATEOUTOFRANGE,

    /// <summary>
    /// Origin time needs to be within the selected billing cycle's start and end at date.
    /// </summary>
    ORIGINTIMEOUTOFRANGE,

    /// <summary>
    /// Billing cycle charge attempt made more than 24 hours before the billing cycle `billingAttemptExpectedDate`.
    /// </summary>
    BILLINGCYCLECHARGEBEFOREEXPECTEDDATE,

    /// <summary>
    /// Billing cycle must not be skipped.
    /// </summary>
    BILLINGCYCLESKIPPED,

    /// <summary>
    /// Subscription contract is under review, origin order is high risk and unfulfilled.
    /// </summary>
    CONTRACTUNDERREVIEW,

    /// <summary>
    /// Subscription contract cannot be billed once terminated.
    /// </summary>
    CONTRACTTERMINATED,

    /// <summary>
    /// Subscription contract cannot be billed if paused.
    /// </summary>
    CONTRACTPAUSED,

    /// <summary>
    /// Billing attempt rate limit exceeded - try later.
    /// </summary>
    THROTTLED

}
