// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `BlogUpdateUserError`.
/// </summary>
public enum BlogUpdateUserErrorCode
{
    /// <summary>
    /// The record with the ID used as the input value couldn't be found.
    /// </summary>
    NOTFOUND,

    /// <summary>
    /// The input value is invalid.
    /// </summary>
    INVALID,

    /// <summary>
    /// The input value is blank.
    /// </summary>
    BLANK,

    /// <summary>
    /// The input value is too long.
    /// </summary>
    TOOLONG,

    /// <summary>
    /// The input value isn't included in the list.
    /// </summary>
    INCLUSION

}
