// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The set of valid sort keys for the BulkOperations query.
/// </summary>
public enum BulkOperationsSortKeys
{
    /// <summary>
    /// Sort by the `completed_at` value.
    /// </summary>
    COMPLETEDAT,

    /// <summary>
    /// Sort by the `created_at` value.
    /// </summary>
    CREATEDAT

}
