// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents the staged status of a CalculatedShippingLine on a CalculatedOrder.
/// </summary>
public enum CalculatedShippingLineStagedStatus
{
    /// <summary>
    /// The shipping line has no staged changes associated with it.
    /// </summary>
    NONE,

    /// <summary>
    /// The shipping line was added as part of the current order edit.
    /// </summary>
    ADDED,

    /// <summary>
    /// The shipping line was removed as part of the current order edit.
    /// </summary>
    REMOVED

}
