// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `CatalogUserError`.
/// </summary>
public enum CatalogUserErrorCode
{
    /// <summary>
    /// An app catalog cannot be assigned to a price list.
    /// </summary>
    APPCATALOGPRICELISTASSIGNMENT,

    /// <summary>
    /// Catalog failed to save.
    /// </summary>
    CATALOGFAILEDTOSAVE,

    /// <summary>
    /// The catalog wasn't found.
    /// </summary>
    CATALOGNOTFOUND,

    /// <summary>
    /// A price list cannot be assigned to the primary market.
    /// </summary>
    PRICELISTNOTALLOWEDFORPRIMARYMARKET,

    /// <summary>
    /// Quantity rules can be associated only with company location catalogs or catalogs associated with compatible markets.
    /// </summary>
    CATALOGCONTEXTDOESNOTSUPPORTQUANTITYRULES,

    /// <summary>
    /// Quantity price breaks can be associated only with company location catalogs or catalogs associated with compatible markets.
    /// </summary>
    CATALOGCONTEXTDOESNOTSUPPORTQUANTITYPRICEBREAKS,

    /// <summary>
    /// The catalog can't be associated with more than one market.
    /// </summary>
    CANNOTADDMORETHANONEMARKET,

    /// <summary>
    /// A company location catalog outside of a supported plan can only have an archived status.
    /// </summary>
    COMPANYLOCATIONCATALOGSTATUSPLAN,

    /// <summary>
    /// Context driver already assigned to this catalog.
    /// </summary>
    CONTEXTALREADYASSIGNEDTOCATALOG,

    /// <summary>
    /// Cannot save the catalog because the catalog limit for the context was reached.
    /// </summary>
    CONTEXTCATALOGLIMITREACHED,

    /// <summary>
    /// The company location could not be found.
    /// </summary>
    COMPANYLOCATIONNOTFOUND,

    /// <summary>
    /// The arguments `contextsToAdd` and `contextsToRemove` must match existing catalog context type.
    /// </summary>
    CONTEXTDRIVERMISMATCH,

    /// <summary>
    /// A country catalog cannot be assigned to a price list.
    /// </summary>
    COUNTRYCATALOGPRICELISTASSIGNMENT,

    /// <summary>
    /// A country price list cannot be assigned to a catalog.
    /// </summary>
    COUNTRYPRICELISTASSIGNMENT,

    /// <summary>
    /// The catalog context type is invalid.
    /// </summary>
    INVALIDCATALOGCONTEXTTYPE,

    /// <summary>
    /// A market catalog must have an active status.
    /// </summary>
    MARKETCATALOGSTATUS,

    /// <summary>
    /// Market not found.
    /// </summary>
    MARKETNOTFOUND,

    /// <summary>
    /// The catalog's market and price list currencies do not match.
    /// </summary>
    MARKETANDPRICELISTCURRENCYMISMATCH,

    /// <summary>
    /// Market already belongs to another catalog.
    /// </summary>
    MARKETTAKEN,

    /// <summary>
    /// The managed country belongs to another catalog.
    /// </summary>
    MANAGEDCOUNTRYBELONGSTOANOTHERCATALOG,

    /// <summary>
    /// Must provide exactly one context type.
    /// </summary>
    MUSTPROVIDEEXACTLYONECONTEXTTYPE,

    /// <summary>
    /// Price list failed to save.
    /// </summary>
    PRICELISTFAILEDTOSAVE,

    /// <summary>
    /// Price list not found.
    /// </summary>
    PRICELISTNOTFOUND,

    /// <summary>
    /// The price list is currently being modified. Please try again later.
    /// </summary>
    PRICELISTLOCKED,

    /// <summary>
    /// The catalog context is currently being modified. Please try again later.
    /// </summary>
    CATALOGCONTEXTLOCKED,

    /// <summary>
    /// Publication not found.
    /// </summary>
    PUBLICATIONNOTFOUND,

    /// <summary>
    /// Must have `contexts_to_add` or `contexts_to_remove` argument.
    /// </summary>
    REQUIRESCONTEXTSTOADDORREMOVE,

    /// <summary>
    /// Can't perform this action on a catalog of this type.
    /// </summary>
    UNSUPPORTEDCATALOGACTION,

    /// <summary>
    /// Cannot create a catalog for an app.
    /// </summary>
    CANNOTCREATEAPPCATALOG,

    /// <summary>
    /// Cannot modify a catalog for an app.
    /// </summary>
    CANNOTMODIFYAPPCATALOG,

    /// <summary>
    /// Cannot delete a catalog for an app.
    /// </summary>
    CANNOTDELETEAPPCATALOG,

    /// <summary>
    /// Cannot create a catalog for a market.
    /// </summary>
    CANNOTCREATEMARKETCATALOG,

    /// <summary>
    /// Cannot modify a catalog for a market.
    /// </summary>
    CANNOTMODIFYMARKETCATALOG,

    /// <summary>
    /// Cannot delete a catalog for a market.
    /// </summary>
    CANNOTDELETEMARKETCATALOG,

    /// <summary>
    /// Managing this catalog is not supported by your plan.
    /// </summary>
    UNPERMITTEDENTITLEMENTSMARKETCATALOGS,

    /// <summary>
    /// The input value is invalid.
    /// </summary>
    INVALID,

    /// <summary>
    /// The input value is already taken.
    /// </summary>
    TAKEN,

    /// <summary>
    /// The input value is too long.
    /// </summary>
    TOOLONG,

    /// <summary>
    /// The input value is too short.
    /// </summary>
    TOOSHORT,

    /// <summary>
    /// The input value is blank.
    /// </summary>
    BLANK,

    /// <summary>
    /// Cannot change context to specified type.
    /// </summary>
    INVALIDCONTEXTCHANGE

}
