// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible values for the typography kerning.
/// </summary>
public enum CheckoutBrandingTypographyKerning
{
    /// <summary>
    /// Base or default kerning.
    /// </summary>
    BASE,

    /// <summary>
    /// Loose kerning, leaving more space than the default in between characters.
    /// </summary>
    LOOSE,

    /// <summary>
    /// Extra loose kerning, leaving even more space in between characters.
    /// </summary>
    EXTRALOOSE

}
