// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible values for the spacing.
/// </summary>
public enum CheckoutBrandingSpacing
{
    /// <summary>
    /// The None spacing.
    /// </summary>
    NONE,

    /// <summary>
    /// The Extra Tight spacing.
    /// </summary>
    EXTRATIGHT,

    /// <summary>
    /// The Tight spacing.
    /// </summary>
    TIGHT,

    /// <summary>
    /// The Base spacing.
    /// </summary>
    BASE,

    /// <summary>
    /// The Loose spacing.
    /// </summary>
    LOOSE,

    /// <summary>
    /// The Extra Loose spacing.
    /// </summary>
    EXTRALOOSE

}
