// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The possible header alignments.
/// </summary>
public enum CheckoutBrandingHeaderAlignment
{
    /// <summary>
    /// Start alignment.
    /// </summary>
    START,

    /// <summary>
    /// Center alignment.
    /// </summary>
    CENTER,

    /// <summary>
    /// End alignment.
    /// </summary>
    END

}
