// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The currency codes that represent the world currencies throughout the Admin API. Currency codes include
/// [standard ISO 4217 codes](https://en.wikipedia.org/wiki/ISO_4217), legacy codes, non-standard codes,
/// digital currency codes.
/// </summary>
public enum CurrencyCode
{
    /// <summary>
    /// United States Dollars (USD).
    /// </summary>
    USD,

    /// <summary>
    /// Euro (EUR).
    /// </summary>
    EUR,

    /// <summary>
    /// United Kingdom Pounds (GBP).
    /// </summary>
    GBP,

    /// <summary>
    /// Canadian Dollars (CAD).
    /// </summary>
    CAD,

    /// <summary>
    /// Afghan Afghani (AFN).
    /// </summary>
    AFN,

    /// <summary>
    /// Albanian Lek (ALL).
    /// </summary>
    ALL,

    /// <summary>
    /// Algerian Dinar (DZD).
    /// </summary>
    DZD,

    /// <summary>
    /// Angolan Kwanza (AOA).
    /// </summary>
    AOA,

    /// <summary>
    /// Argentine Pesos (ARS).
    /// </summary>
    ARS,

    /// <summary>
    /// Armenian Dram (AMD).
    /// </summary>
    AMD,

    /// <summary>
    /// Aruban Florin (AWG).
    /// </summary>
    AWG,

    /// <summary>
    /// Australian Dollars (AUD).
    /// </summary>
    AUD,

    /// <summary>
    /// Barbadian Dollar (BBD).
    /// </summary>
    BBD,

    /// <summary>
    /// Azerbaijani Manat (AZN).
    /// </summary>
    AZN,

    /// <summary>
    /// Bangladesh Taka (BDT).
    /// </summary>
    BDT,

    /// <summary>
    /// Bahamian Dollar (BSD).
    /// </summary>
    BSD,

    /// <summary>
    /// Bahraini Dinar (BHD).
    /// </summary>
    BHD,

    /// <summary>
    /// Burundian Franc (BIF).
    /// </summary>
    BIF,

    /// <summary>
    /// Belarusian Ruble (BYN).
    /// </summary>
    BYN,

    /// <summary>
    /// Belize Dollar (BZD).
    /// </summary>
    BZD,

    /// <summary>
    /// Bermudian Dollar (BMD).
    /// </summary>
    BMD,

    /// <summary>
    /// Bhutanese Ngultrum (BTN).
    /// </summary>
    BTN,

    /// <summary>
    /// Bosnia and Herzegovina Convertible Mark (BAM).
    /// </summary>
    BAM,

    /// <summary>
    /// Brazilian Real (BRL).
    /// </summary>
    BRL,

    /// <summary>
    /// Bolivian Boliviano (BOB).
    /// </summary>
    BOB,

    /// <summary>
    /// Botswana Pula (BWP).
    /// </summary>
    BWP,

    /// <summary>
    /// Brunei Dollar (BND).
    /// </summary>
    BND,

    /// <summary>
    /// Bulgarian Lev (BGN).
    /// </summary>
    BGN,

    /// <summary>
    /// Burmese Kyat (MMK).
    /// </summary>
    MMK,

    /// <summary>
    /// Cambodian Riel.
    /// </summary>
    KHR,

    /// <summary>
    /// Cape Verdean escudo (CVE).
    /// </summary>
    CVE,

    /// <summary>
    /// Cayman Dollars (KYD).
    /// </summary>
    KYD,

    /// <summary>
    /// Central African CFA Franc (XAF).
    /// </summary>
    XAF,

    /// <summary>
    /// Chilean Peso (CLP).
    /// </summary>
    CLP,

    /// <summary>
    /// Chinese Yuan Renminbi (CNY).
    /// </summary>
    CNY,

    /// <summary>
    /// Colombian Peso (COP).
    /// </summary>
    COP,

    /// <summary>
    /// Comorian Franc (KMF).
    /// </summary>
    KMF,

    /// <summary>
    /// Congolese franc (CDF).
    /// </summary>
    CDF,

    /// <summary>
    /// Costa Rican Colones (CRC).
    /// </summary>
    CRC,

    /// <summary>
    /// Croatian Kuna (HRK).
    /// </summary>
    HRK,

    /// <summary>
    /// Czech Koruny (CZK).
    /// </summary>
    CZK,

    /// <summary>
    /// Danish Kroner (DKK).
    /// </summary>
    DKK,

    /// <summary>
    /// Djiboutian Franc (DJF).
    /// </summary>
    DJF,

    /// <summary>
    /// Dominican Peso (DOP).
    /// </summary>
    DOP,

    /// <summary>
    /// East Caribbean Dollar (XCD).
    /// </summary>
    XCD,

    /// <summary>
    /// Egyptian Pound (EGP).
    /// </summary>
    EGP,

    /// <summary>
    /// Eritrean Nakfa (ERN).
    /// </summary>
    ERN,

    /// <summary>
    /// Ethiopian Birr (ETB).
    /// </summary>
    ETB,

    /// <summary>
    /// Falkland Islands Pounds (FKP).
    /// </summary>
    FKP,

    /// <summary>
    /// CFP Franc (XPF).
    /// </summary>
    XPF,

    /// <summary>
    /// Fijian Dollars (FJD).
    /// </summary>
    FJD,

    /// <summary>
    /// Gibraltar Pounds (GIP).
    /// </summary>
    GIP,

    /// <summary>
    /// Gambian Dalasi (GMD).
    /// </summary>
    GMD,

    /// <summary>
    /// Ghanaian Cedi (GHS).
    /// </summary>
    GHS,

    /// <summary>
    /// Guatemalan Quetzal (GTQ).
    /// </summary>
    GTQ,

    /// <summary>
    /// Guyanese Dollar (GYD).
    /// </summary>
    GYD,

    /// <summary>
    /// Georgian Lari (GEL).
    /// </summary>
    GEL,

    /// <summary>
    /// Guinean Franc (GNF).
    /// </summary>
    GNF,

    /// <summary>
    /// Haitian Gourde (HTG).
    /// </summary>
    HTG,

    /// <summary>
    /// Honduran Lempira (HNL).
    /// </summary>
    HNL,

    /// <summary>
    /// Hong Kong Dollars (HKD).
    /// </summary>
    HKD,

    /// <summary>
    /// Hungarian Forint (HUF).
    /// </summary>
    HUF,

    /// <summary>
    /// Icelandic Kronur (ISK).
    /// </summary>
    ISK,

    /// <summary>
    /// Indian Rupees (INR).
    /// </summary>
    INR,

    /// <summary>
    /// Indonesian Rupiah (IDR).
    /// </summary>
    IDR,

    /// <summary>
    /// Israeli New Shekel (NIS).
    /// </summary>
    ILS,

    /// <summary>
    /// Iranian Rial (IRR).
    /// </summary>
    IRR,

    /// <summary>
    /// Iraqi Dinar (IQD).
    /// </summary>
    IQD,

    /// <summary>
    /// Jamaican Dollars (JMD).
    /// </summary>
    JMD,

    /// <summary>
    /// Japanese Yen (JPY).
    /// </summary>
    JPY,

    /// <summary>
    /// Jersey Pound.
    /// </summary>
    JEP,

    /// <summary>
    /// Jordanian Dinar (JOD).
    /// </summary>
    JOD,

    /// <summary>
    /// Kazakhstani Tenge (KZT).
    /// </summary>
    KZT,

    /// <summary>
    /// Kenyan Shilling (KES).
    /// </summary>
    KES,

    /// <summary>
    /// Kiribati Dollar (KID).
    /// </summary>
    KID,

    /// <summary>
    /// Kuwaiti Dinar (KWD).
    /// </summary>
    KWD,

    /// <summary>
    /// Kyrgyzstani Som (KGS).
    /// </summary>
    KGS,

    /// <summary>
    /// Laotian Kip (LAK).
    /// </summary>
    LAK,

    /// <summary>
    /// Latvian Lati (LVL).
    /// </summary>
    LVL,

    /// <summary>
    /// Lebanese Pounds (LBP).
    /// </summary>
    LBP,

    /// <summary>
    /// Lesotho Loti (LSL).
    /// </summary>
    LSL,

    /// <summary>
    /// Liberian Dollar (LRD).
    /// </summary>
    LRD,

    /// <summary>
    /// Libyan Dinar (LYD).
    /// </summary>
    LYD,

    /// <summary>
    /// Lithuanian Litai (LTL).
    /// </summary>
    LTL,

    /// <summary>
    /// Malagasy Ariary (MGA).
    /// </summary>
    MGA,

    /// <summary>
    /// Macedonia Denar (MKD).
    /// </summary>
    MKD,

    /// <summary>
    /// Macanese Pataca (MOP).
    /// </summary>
    MOP,

    /// <summary>
    /// Malawian Kwacha (MWK).
    /// </summary>
    MWK,

    /// <summary>
    /// Maldivian Rufiyaa (MVR).
    /// </summary>
    MVR,

    /// <summary>
    /// Mauritanian Ouguiya (MRU).
    /// </summary>
    MRU,

    /// <summary>
    /// Mexican Pesos (MXN).
    /// </summary>
    MXN,

    /// <summary>
    /// Malaysian Ringgits (MYR).
    /// </summary>
    MYR,

    /// <summary>
    /// Mauritian Rupee (MUR).
    /// </summary>
    MUR,

    /// <summary>
    /// Moldovan Leu (MDL).
    /// </summary>
    MDL,

    /// <summary>
    /// Moroccan Dirham.
    /// </summary>
    MAD,

    /// <summary>
    /// Mongolian Tugrik.
    /// </summary>
    MNT,

    /// <summary>
    /// Mozambican Metical.
    /// </summary>
    MZN,

    /// <summary>
    /// Namibian Dollar.
    /// </summary>
    NAD,

    /// <summary>
    /// Nepalese Rupee (NPR).
    /// </summary>
    NPR,

    /// <summary>
    /// Netherlands Antillean Guilder.
    /// </summary>
    ANG,

    /// <summary>
    /// New Zealand Dollars (NZD).
    /// </summary>
    NZD,

    /// <summary>
    /// Nicaraguan Córdoba (NIO).
    /// </summary>
    NIO,

    /// <summary>
    /// Nigerian Naira (NGN).
    /// </summary>
    NGN,

    /// <summary>
    /// Norwegian Kroner (NOK).
    /// </summary>
    NOK,

    /// <summary>
    /// Omani Rial (OMR).
    /// </summary>
    OMR,

    /// <summary>
    /// Panamian Balboa (PAB).
    /// </summary>
    PAB,

    /// <summary>
    /// Pakistani Rupee (PKR).
    /// </summary>
    PKR,

    /// <summary>
    /// Papua New Guinean Kina (PGK).
    /// </summary>
    PGK,

    /// <summary>
    /// Paraguayan Guarani (PYG).
    /// </summary>
    PYG,

    /// <summary>
    /// Peruvian Nuevo Sol (PEN).
    /// </summary>
    PEN,

    /// <summary>
    /// Philippine Peso (PHP).
    /// </summary>
    PHP,

    /// <summary>
    /// Polish Zlotych (PLN).
    /// </summary>
    PLN,

    /// <summary>
    /// Qatari Rial (QAR).
    /// </summary>
    QAR,

    /// <summary>
    /// Romanian Lei (RON).
    /// </summary>
    RON,

    /// <summary>
    /// Russian Rubles (RUB).
    /// </summary>
    RUB,

    /// <summary>
    /// Rwandan Franc (RWF).
    /// </summary>
    RWF,

    /// <summary>
    /// Samoan Tala (WST).
    /// </summary>
    WST,

    /// <summary>
    /// Saint Helena Pounds (SHP).
    /// </summary>
    SHP,

    /// <summary>
    /// Saudi Riyal (SAR).
    /// </summary>
    SAR,

    /// <summary>
    /// Serbian dinar (RSD).
    /// </summary>
    RSD,

    /// <summary>
    /// Seychellois Rupee (SCR).
    /// </summary>
    SCR,

    /// <summary>
    /// Sierra Leonean Leone (SLL).
    /// </summary>
    SLL,

    /// <summary>
    /// Singapore Dollars (SGD).
    /// </summary>
    SGD,

    /// <summary>
    /// Sudanese Pound (SDG).
    /// </summary>
    SDG,

    /// <summary>
    /// Somali Shilling (SOS).
    /// </summary>
    SOS,

    /// <summary>
    /// Syrian Pound (SYP).
    /// </summary>
    SYP,

    /// <summary>
    /// South African Rand (ZAR).
    /// </summary>
    ZAR,

    /// <summary>
    /// South Korean Won (KRW).
    /// </summary>
    KRW,

    /// <summary>
    /// South Sudanese Pound (SSP).
    /// </summary>
    SSP,

    /// <summary>
    /// Solomon Islands Dollar (SBD).
    /// </summary>
    SBD,

    /// <summary>
    /// Sri Lankan Rupees (LKR).
    /// </summary>
    LKR,

    /// <summary>
    /// Surinamese Dollar (SRD).
    /// </summary>
    SRD,

    /// <summary>
    /// Swazi Lilangeni (SZL).
    /// </summary>
    SZL,

    /// <summary>
    /// Swedish Kronor (SEK).
    /// </summary>
    SEK,

    /// <summary>
    /// Swiss Francs (CHF).
    /// </summary>
    CHF,

    /// <summary>
    /// Taiwan Dollars (TWD).
    /// </summary>
    TWD,

    /// <summary>
    /// Thai baht (THB).
    /// </summary>
    THB,

    /// <summary>
    /// Tajikistani Somoni (TJS).
    /// </summary>
    TJS,

    /// <summary>
    /// Tanzanian Shilling (TZS).
    /// </summary>
    TZS,

    /// <summary>
    /// Tongan Pa'anga (TOP).
    /// </summary>
    TOP,

    /// <summary>
    /// Trinidad and Tobago Dollars (TTD).
    /// </summary>
    TTD,

    /// <summary>
    /// Tunisian Dinar (TND).
    /// </summary>
    TND,

    /// <summary>
    /// Turkish Lira (TRY).
    /// </summary>
    TRY,

    /// <summary>
    /// Turkmenistani Manat (TMT).
    /// </summary>
    TMT,

    /// <summary>
    /// Ugandan Shilling (UGX).
    /// </summary>
    UGX,

    /// <summary>
    /// Ukrainian Hryvnia (UAH).
    /// </summary>
    UAH,

    /// <summary>
    /// United Arab Emirates Dirham (AED).
    /// </summary>
    AED,

    /// <summary>
    /// Uruguayan Pesos (UYU).
    /// </summary>
    UYU,

    /// <summary>
    /// Uzbekistan som (UZS).
    /// </summary>
    UZS,

    /// <summary>
    /// Vanuatu Vatu (VUV).
    /// </summary>
    VUV,

    /// <summary>
    /// Venezuelan Bolivares Soberanos (VES).
    /// </summary>
    VES,

    /// <summary>
    /// Vietnamese đồng (VND).
    /// </summary>
    VND,

    /// <summary>
    /// West African CFA franc (XOF).
    /// </summary>
    XOF,

    /// <summary>
    /// Yemeni Rial (YER).
    /// </summary>
    YER,

    /// <summary>
    /// Zambian Kwacha (ZMW).
    /// </summary>
    ZMW,

    /// <summary>
    /// United States Dollars Coin (USDC).
    /// </summary>
    USDC,

    /// <summary>
    /// Belarusian Ruble (BYR).
    /// </summary>
    BYR,

    /// <summary>
    /// Sao Tome And Principe Dobra (STD).
    /// </summary>
    STD,

    /// <summary>
    /// Sao Tome And Principe Dobra (STN).
    /// </summary>
    STN,

    /// <summary>
    /// Venezuelan Bolivares (VED).
    /// </summary>
    VED,

    /// <summary>
    /// Venezuelan Bolivares (VEF).
    /// </summary>
    VEF,

    /// <summary>
    /// Unrecognized currency.
    /// </summary>
    XXX

}
