// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `CustomerRequestDataErasureUserError`.
/// </summary>
public enum CustomerRequestDataErasureErrorCode
{
    /// <summary>
    /// Customer does not exist.
    /// </summary>
    DOESNOTEXIST,

    /// <summary>
    /// Failed to request customer data erasure.
    /// </summary>
    FAILEDTOREQUEST

}
