// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `DelegateAccessTokenCreateUserError`.
/// </summary>
public enum DelegateAccessTokenCreateUserErrorCode
{
    /// <summary>
    /// The access scope can't be empty.
    /// </summary>
    EMPTYACCESSSCOPE,

    /// <summary>
    /// The parent access token can't be a delegate token.
    /// </summary>
    DELEGATEACCESSTOKEN,

    /// <summary>
    /// The expires_in value must be greater than 0.
    /// </summary>
    NEGATIVEEXPIRESIN,

    /// <summary>
    /// The delegate token can't expire after the parent token.
    /// </summary>
    EXPIRESAFTERPARENT,

    /// <summary>
    /// The parent access token can't have a refresh token.
    /// </summary>
    REFRESHTOKEN,

    /// <summary>
    /// Persistence failed.
    /// </summary>
    PERSISTENCEFAILED,

    /// <summary>
    /// Unknown scopes.
    /// </summary>
    UNKNOWNSCOPES

}
