// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The type of object that the participant is attached to.
/// </summary>
public enum DeliveryPromiseParticipantOwnerType
{
    /// <summary>
    /// A product variant.
    /// </summary>
    PRODUCTVARIANT

}
