// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The different types of method definitions to filter by.
/// </summary>
public enum DeliveryMethodDefinitionType
{
    /// <summary>
    /// A static merchant-defined rate.
    /// </summary>
    MERCHANT,

    /// <summary>
    /// A dynamic participant rate.
    /// </summary>
    PARTICIPANT

}
