// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `DeliveryPromiseProviderUpsertUserError`.
/// </summary>
public enum DeliveryPromiseProviderUpsertUserErrorCode
{
    /// <summary>
    /// The record with the ID used as the input value couldn't be found.
    /// </summary>
    NOTFOUND,

    /// <summary>
    /// The input value is too long.
    /// </summary>
    TOOLONG,

    /// <summary>
    /// The location doesn't belong to the app.
    /// </summary>
    MUSTBELONGTOAPP,

    /// <summary>
    /// The time zone is invalid.
    /// </summary>
    INVALIDTIMEZONE

}
