// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The status of the discount that describes its availability,
/// expiration, or pending activation.
/// </summary>
public enum DiscountStatus
{
    /// <summary>
    /// The discount is currently available for use.
    /// </summary>
    ACTIVE,

    /// <summary>
    /// The discount has reached its end date and is no longer valid.
    /// </summary>
    EXPIRED,

    /// <summary>
    /// The discount is set to become active at a future date.
    /// </summary>
    SCHEDULED

}
