// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The possible statuses of a dispute.
/// </summary>
public enum DisputeStatus
{
    ACCEPTED,

    LOST,

    NEEDSRESPONSE,

    UNDERREVIEW,

    WON,

    /// <summary>
    /// Status previously used by Stripe to indicate that a dispute led to a refund.
    /// </summary>
    CHARGEREFUNDED

}
