// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The status of a fulfillment.
/// </summary>
public enum FulfillmentStatus
{
    /// <summary>
    /// Shopify has created the fulfillment and is waiting for the third-party fulfillment service to transition it to `open` or `success`.
    /// </summary>
    PENDING,

    /// <summary>
    /// The third-party fulfillment service has acknowledged the fulfillment and is processing it.
    /// </summary>
    OPEN,

    /// <summary>
    /// The fulfillment was completed successfully.
    /// </summary>
    SUCCESS,

    /// <summary>
    /// The fulfillment was canceled.
    /// </summary>
    CANCELLED,

    /// <summary>
    /// There was an error with the fulfillment request.
    /// </summary>
    ERROR,

    /// <summary>
    /// The fulfillment request failed.
    /// </summary>
    FAILURE

}
