// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `FulfillmentOrderHoldUserError`.
/// </summary>
public enum FulfillmentOrderHoldUserErrorCode
{
    /// <summary>
    /// The fulfillment order could not be found.
    /// </summary>
    FULFILLMENTORDERNOTFOUND,

    /// <summary>
    /// The input value is already taken.
    /// </summary>
    TAKEN,

    /// <summary>
    /// The fulfillment order line item quantity must be greater than 0.
    /// </summary>
    GREATERTHANZERO,

    /// <summary>
    /// The maximum number of fulfillment holds for this fulfillment order has been reached for this app. An app can only have up to 10 holds on a single fulfillment order at any one time.
    /// </summary>
    FULFILLMENTORDERHOLDLIMITREACHED,

    /// <summary>
    /// The handle provided for the fulfillment hold is already in use by this app for another hold on this fulfillment order.
    /// </summary>
    DUPLICATEFULFILLMENTHOLDHANDLE,

    /// <summary>
    /// The fulfillment order line item quantity is invalid.
    /// </summary>
    INVALIDLINEITEMQUANTITY,

    /// <summary>
    /// The fulfillment order is not in a splittable state.
    /// </summary>
    FULFILLMENTORDERNOTSPLITTABLE,

    /// <summary>
    /// The fulfillment order line items are not unique.
    /// </summary>
    DUPLICATEDFULFILLMENTORDERLINEITEMS

}
