// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `FulfillmentOrderReleaseHoldUserError`.
/// </summary>
public enum FulfillmentOrderReleaseHoldUserErrorCode
{
    /// <summary>
    /// The fulfillment order wasn't found.
    /// </summary>
    FULFILLMENTORDERNOTFOUND,

    /// <summary>
    /// The app doesn't have access to release the fulfillment hold.
    /// </summary>
    INVALIDACCESS

}
