// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The kinds of request merchants can make to a fulfillment service.
/// </summary>
public enum FulfillmentOrderMerchantRequestKind
{
    /// <summary>
    /// The merchant requests fulfillment for an `OPEN` fulfillment order.
    /// </summary>
    FULFILLMENTREQUEST,

    /// <summary>
    /// The merchant requests cancellation of an `IN_PROGRESS` fulfillment order.
    /// </summary>
    CANCELLATIONREQUEST

}
