// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The reason for receiving a line item on an inventory shipment.
/// </summary>
public enum InventoryShipmentReceiveLineItemReason
{
    /// <summary>
    /// The line item was accepted.
    /// </summary>
    ACCEPTED,

    /// <summary>
    /// The line item was rejected.
    /// </summary>
    REJECTED

}
