// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The type of resources that are market localizable.
/// </summary>
public enum MarketLocalizableResourceType
{
    /// <summary>
    /// A metafield. Market localizable fields: `value`.
    /// </summary>
    METAFIELD,

    /// <summary>
    /// A Metaobject. Market Localizable fields are determined by the Metaobject type.
    /// </summary>
    METAOBJECT

}
