// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The available types of tactics for a marketing activity.
/// </summary>
public enum MarketingTactic
{
    /// <summary>
    /// An abandoned cart recovery email.
    /// </summary>
    ABANDONEDCART,

    /// <summary>
    /// An ad, such as a Facebook ad.
    /// </summary>
    AD,

    /// <summary>
    /// An affiliate link.
    /// </summary>
    AFFILIATE,

    /// <summary>
    /// A link.
    /// </summary>
    LINK,

    /// <summary>
    /// A loyalty program.
    /// </summary>
    LOYALTY,

    /// <summary>
    /// A messaging app, such as Facebook Messenger.
    /// </summary>
    MESSAGE,

    /// <summary>
    /// A newsletter.
    /// </summary>
    NEWSLETTER,

    /// <summary>
    /// A notification in the Shopify admin.
    /// </summary>
    NOTIFICATION,

    /// <summary>
    /// A blog post.
    /// </summary>
    POST,

    /// <summary>
    /// A retargeting ad.
    /// </summary>
    RETARGETING,

    /// <summary>
    /// A transactional email.
    /// </summary>
    TRANSACTIONAL,

    /// <summary>
    /// A popup on the online store.
    /// </summary>
    STOREFRONTAPP,

    /// <summary>
    /// Search engine optimization.
    /// </summary>
    SEO

}
