// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `MenuUpdateUserError`.
/// </summary>
public enum MenuUpdateUserErrorCode
{
    /// <summary>
    /// The record with the ID used as the input value couldn't be found.
    /// </summary>
    NOTFOUND,

    /// <summary>
    /// The menu cannot be nested more than 3 level deep.
    /// </summary>
    NESTINGTOODEEP

}
