// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible metafield validation statuses.
/// </summary>
public enum MetafieldValidationStatus
{
    /// <summary>
    /// Any validation status (valid or invalid).
    /// </summary>
    ANY,

    /// <summary>
    /// Valid (according to definition).
    /// </summary>
    VALID,

    /// <summary>
    /// Invalid (according to definition).
    /// </summary>
    INVALID

}
