// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Metafield access permissions for the Customer Account API.
/// </summary>
public enum MetafieldCustomerAccountAccess
{
    /// <summary>
    /// Read and write access.
    /// </summary>
    READWRITE,

    /// <summary>
    /// Read-only access.
    /// </summary>
    READ,

    /// <summary>
    /// No access.
    /// </summary>
    NONE

}
