// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `MetafieldDefinitionUnpinUserError`.
/// </summary>
public enum MetafieldDefinitionUnpinUserErrorCode
{
    /// <summary>
    /// The metafield definition was not found.
    /// </summary>
    NOTFOUND,

    /// <summary>
    /// The metafield definition isn't pinned.
    /// </summary>
    NOTPINNED,

    /// <summary>
    /// An internal error occurred.
    /// </summary>
    INTERNALERROR,

    /// <summary>
    /// Definition is managed by app configuration and cannot be modified through the API.
    /// </summary>
    APPCONFIGMANAGED,

    /// <summary>
    /// Owner type can't be used in this mutation.
    /// </summary>
    DISALLOWEDOWNERTYPE

}
