// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Metafield access permissions for the Admin API.
/// </summary>
public enum MetafieldAdminAccessInput
{
    /// <summary>
    /// The merchant has read-only access. No other apps have access.
    /// </summary>
    MERCHANTREAD,

    /// <summary>
    /// The merchant has read and write access. No other apps have access.
    /// </summary>
    MERCHANTREADWRITE

}
