// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Type of a theme file operation result.
/// </summary>
public enum OnlineStoreThemeFileResultType
{
    /// <summary>
    /// Operation was successful.
    /// </summary>
    SUCCESS,

    /// <summary>
    /// Operation encountered an error.
    /// </summary>
    ERROR,

    /// <summary>
    /// Operation faced a conflict with the current state of the file.
    /// </summary>
    CONFLICT,

    /// <summary>
    /// Operation could not be processed due to issues with input data.
    /// </summary>
    UNPROCESSABLEENTITY,

    /// <summary>
    /// Operation was malformed or invalid.
    /// </summary>
    BADREQUEST,

    /// <summary>
    /// Operation timed out.
    /// </summary>
    TIMEOUT,

    /// <summary>
    /// Operation file could not be found.
    /// </summary>
    NOTFOUND

}
