// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The set of valid sort keys for the Order query.
/// </summary>
public enum OrderSortKeys
{
    /// <summary>
    /// Sorts by the date and time the order was created.
    /// </summary>
    CREATEDAT,

    /// <summary>
    /// Sorts by the current total price of an order in the shop currency, including any returns/refunds/removals.
    /// </summary>
    CURRENTTOTALPRICE,

    /// <summary>
    /// Sorts by the customer's name.
    /// </summary>
    CUSTOMERNAME,

    /// <summary>
    /// Sort by shipping address to analyze regional sales patterns or plan logistics.
    /// </summary>
    DESTINATION,

    /// <summary>
    /// Sorts by the financial status of the order.
    /// </summary>
    FINANCIALSTATUS,

    /// <summary>
    /// Sorts by the order's fulfillment status.
    /// </summary>
    FULFILLMENTSTATUS,

    /// <summary>
    /// Sort by the `id` value.
    /// </summary>
    ID,

    /// <summary>
    /// Sorts by the order number.
    /// </summary>
    ORDERNUMBER,

    /// <summary>
    /// Sort by the purchase order number to match external procurement systems or track recent orders.
    /// </summary>
    PONUMBER,

    /// <summary>
    /// Sorts by the date and time the order was processed.
    /// </summary>
    PROCESSEDAT,

    /// <summary>
    /// Sort by relevance to the search terms when the `query` parameter is specified on the connection.
    /// Don't use this sort key when no search query is specified.
    /// </summary>
    RELEVANCE,

    /// <summary>
    /// Sort by the total quantity of all line items to identify large purchases or analyze inventory demand patterns.
    /// </summary>
    TOTALITEMSQUANTITY,

    /// <summary>
    /// Sorts by the total sold price of an order in the shop currency, excluding any returns/refunds/removals.
    /// </summary>
    TOTALPRICE,

    /// <summary>
    /// Sorts by the date and time the order was last updated.
    /// </summary>
    UPDATEDAT

}
