// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The order's status in terms of fulfilled line items.
/// </summary>
public enum OrderCreateFulfillmentStatus
{
    /// <summary>
    /// Every line item in the order has been fulfilled.
    /// </summary>
    FULFILLED,

    /// <summary>
    /// At least one line item in the order has been fulfilled.
    /// </summary>
    PARTIAL,

    /// <summary>
    /// Every line item in the order has been restocked and the order canceled.
    /// </summary>
    RESTOCKED

}
