// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents how the compare at price will be determined for a price list.
/// </summary>
public enum PriceListCompareAtMode
{
    /// <summary>
    /// The compare at price is adjusted based on percentage specified in price list.
    /// </summary>
    ADJUSTED,

    /// <summary>
    /// The compare at prices are set to `null` unless explicitly defined by a fixed price value.
    /// </summary>
    NULLIFY

}
