// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `PriceListPriceUserError`.
/// </summary>
public enum PriceListPriceUserErrorCode
{
    /// <summary>
    /// The input value is blank.
    /// </summary>
    BLANK,

    /// <summary>
    /// The price list doesn't exist.
    /// </summary>
    PRICELISTNOTFOUND,

    /// <summary>
    /// The specified currency doesn't match the price list's currency.
    /// </summary>
    PRICELISTCURRENCYMISMATCH,

    /// <summary>
    /// The issuance currency of a local currency gift card must match the price list currency.
    /// </summary>
    LOCALCURRENCYGIFTCARDISSUANCECURRENCYMISMATCH,

    /// <summary>
    /// The price of a local currency gift card cannot exceed the maximum gift card purchase limit.
    /// </summary>
    LOCALCURRENCYGIFTCARDLIMITEXCEEDED,

    /// <summary>
    /// A fixed price for the specified product variant doesn't exist.
    /// </summary>
    VARIANTNOTFOUND,

    /// <summary>
    /// Only fixed prices can be deleted.
    /// </summary>
    PRICENOTFIXED

}
