// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents the origin of a price, either fixed (defined on the price list) or relative (calculated using a price list adjustment configuration). For examples, refer to [PriceList](https://shopify.dev/api/admin-graphql/latest/queries/priceList#section-examples).
/// </summary>
public enum PriceListPriceOriginType
{
    /// <summary>
    /// The price is defined on the price list.
    /// </summary>
    FIXED,

    /// <summary>
    /// The price is relative to the adjustment type and value.
    /// </summary>
    RELATIVE

}
