// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The set of valid sort keys for products belonging to a collection.
/// </summary>
public enum ProductCollectionSortKeys
{
    /// <summary>
    /// Sort by best selling.
    /// </summary>
    BESTSELLING,

    /// <summary>
    /// Sort by collection default order.
    /// </summary>
    COLLECTIONDEFAULT,

    /// <summary>
    /// Sort by creation time.
    /// </summary>
    CREATED,

    /// <summary>
    /// Sort by id.
    /// </summary>
    ID,

    /// <summary>
    /// Sort by manual order.
    /// </summary>
    MANUAL,

    /// <summary>
    /// Sort by price.
    /// </summary>
    PRICE,

    /// <summary>
    /// Sort by relevance.
    /// </summary>
    RELEVANCE,

    /// <summary>
    /// Sort by title.
    /// </summary>
    TITLE

}
