// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The valid values for the status of product feed.
/// </summary>
public enum ProductFeedStatus
{
    /// <summary>
    /// The product feed is active.
    /// </summary>
    ACTIVE,

    /// <summary>
    /// The product feed is inactive.
    /// </summary>
    INACTIVE

}
