// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `PubSubWebhookSubscriptionCreateUserError`.
/// </summary>
public enum PubSubWebhookSubscriptionCreateUserErrorCode
{
    /// <summary>
    /// Invalid parameters provided.
    /// </summary>
    INVALIDPARAMETERS,

    /// <summary>
    /// Address for this topic has already been taken.
    /// </summary>
    TAKEN

}
