// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The possible severity levels for a resource alert.
/// </summary>
public enum ResourceAlertSeverity
{
    /// <summary>
    /// Indicates a neutral alert. For example, an accepted dispute.
    /// </summary>
    DEFAULT,

    /// <summary>
    /// Indicates an informative alert. For example, an escalated dispute.
    /// </summary>
    INFO,

    /// <summary>
    /// Indicates an informative alert. For example, a new dispute.
    /// </summary>
    WARNING,

    /// <summary>
    /// Indicates a success alert. For example, a winning a dispute.
    /// </summary>
    SUCCESS,

    /// <summary>
    /// Indicates a critical alert. For example, a blocked app.
    /// </summary>
    CRITICAL,

    ERROR

}
