// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The final arrangement of an item from a reverse fulfillment order.
/// </summary>
public enum ReverseFulfillmentOrderDispositionType
{
    /// <summary>
    /// An item that was restocked.
    /// </summary>
    RESTOCKED,

    /// <summary>
    /// An item that requires further processing before being restocked or discarded.
    /// </summary>
    PROCESSINGREQUIRED,

    /// <summary>
    /// An item that wasn't restocked.
    /// </summary>
    NOTRESTOCKED,

    /// <summary>
    /// An item that was expected but absent.
    /// </summary>
    MISSING

}
