// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// When to reserve inventory for a selling plan.
/// </summary>
public enum SellingPlanReserve
{
    /// <summary>
    /// Reserve inventory when order is fulfilled.
    /// </summary>
    ONFULFILLMENT,

    /// <summary>
    /// Reserve inventory at time of sale.
    /// </summary>
    ONSALE

}
