// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The transfer status of the payout.
/// </summary>
public enum ShopifyPaymentsPayoutStatus
{
    /// <summary>
    /// The payout has been created and had transactions assigned to it, but
    /// it has not yet been submitted to the bank.
    /// </summary>
    SCHEDULED,

    /// <summary>
    /// The payout has been submitted to the bank.
    /// </summary>
    INTRANSIT,

    /// <summary>
    /// The payout has been successfully deposited into the bank.
    /// </summary>
    PAID,

    /// <summary>
    /// The payout has been declined by the bank.
    /// </summary>
    FAILED,

    /// <summary>
    /// The payout has been canceled by Shopify.
    /// </summary>
    CANCELED

}
