// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The status of an order's eligibility for protection against fraudulent chargebacks by Shopify Protect.
/// </summary>
public enum ShopifyProtectEligibilityStatus
{
    /// <summary>
    /// The eligibility of the order is pending and has not yet been determined.
    /// </summary>
    PENDING,

    /// <summary>
    /// The order is eligible for protection against fraudulent chargebacks.
    /// If an order is updated, the order's eligibility may change and protection could be removed.
    /// </summary>
    ELIGIBLE,

    /// <summary>
    /// The order isn't eligible for protection against fraudulent chargebacks.
    /// </summary>
    NOTELIGIBLE

}
