// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `ShopifyPaymentsPayoutAlternateCurrencyCreateUserError`.
/// </summary>
public enum ShopifyPaymentsPayoutAlternateCurrencyCreateUserErrorCode
{
    /// <summary>
    /// No Stripe provider account was found.
    /// </summary>
    MISSINGPROVIDERACCOUNT,

    /// <summary>
    /// Failed to create payout due to an error from Stripe.
    /// </summary>
    ALTERNATECURRENCYPAYOUTFAILEDSTRIPEERROR,

    /// <summary>
    /// Failed to create payout due to an error from Shopify Core.
    /// </summary>
    UNKNOWNCOREERROR,

    /// <summary>
    /// Failed to create payout, there is no eligible balance in this currency.
    /// </summary>
    ALTERNATECURRENCYPAYOUTFAILEDNOELIGIBLEBALANCE

}
