// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Represents the shop's customer account requirement preference.
/// </summary>
public enum ShopCustomerAccountsSetting
{
    REQUIRED,

    OPTIONAL,

    DISABLED

}
