// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible sort of tags.
/// </summary>
public enum ShopTagSort
{
    /// <summary>
    /// Alphabetical sort.
    /// </summary>
    ALPHABETICAL,

    /// <summary>
    /// Popularity sort.
    /// </summary>
    POPULAR

}
