// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The possible status values of a subscription billing cycle.
/// </summary>
public enum SubscriptionBillingCycleBillingCycleStatus
{
    /// <summary>
    /// The billing cycle is billed.
    /// </summary>
    BILLED,

    /// <summary>
    /// The billing cycle hasn't been billed.
    /// </summary>
    UNBILLED

}
