// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `SubscriptionDraftUserError`.
/// </summary>
public enum SubscriptionDraftErrorCode
{
    /// <summary>
    /// This line has already been removed.
    /// </summary>
    ALREADYREMOVED,

    /// <summary>
    /// Input value is not present.
    /// </summary>
    PRESENCE,

    /// <summary>
    /// Subscription draft has been already committed.
    /// </summary>
    COMMITTED,

    /// <summary>
    /// Value is not in range.
    /// </summary>
    NOTINRANGE,

    /// <summary>
    /// The value is not an integer.
    /// </summary>
    NOTANINTEGER,

    /// <summary>
    /// The maximum number of cycles must be greater than the minimum.
    /// </summary>
    SELLINGPLANMAXCYCLESMUSTBEGREATERTHANMINCYCLES,

    /// <summary>
    /// The delivery policy interval must be a multiple of the billing policy interval.
    /// </summary>
    DELIVERYMUSTBEMULTIPLEOFBILLING,

    /// <summary>
    /// Next billing date is invalid.
    /// </summary>
    INVALIDBILLINGDATE,

    /// <summary>
    /// Note length is too long.
    /// </summary>
    INVALIDNOTELENGTH,

    /// <summary>
    /// Must have at least one line.
    /// </summary>
    INVALIDLINES,

    /// <summary>
    /// Discount must have at least one entitled line.
    /// </summary>
    NOENTITLEDLINES,

    /// <summary>
    /// The customer doesn't exist.
    /// </summary>
    CUSTOMERDOESNOTEXIST,

    /// <summary>
    /// The payment method customer must be the same as the contract customer.
    /// </summary>
    CUSTOMERMISMATCH,

    /// <summary>
    /// The delivery method can't be blank if any lines require shipping.
    /// </summary>
    DELIVERYMETHODREQUIRED,

    /// <summary>
    /// The local delivery options must be set for local delivery.
    /// </summary>
    MISSINGLOCALDELIVERYOPTIONS,

    /// <summary>
    /// The after cycle attribute must be unique between cycle discounts.
    /// </summary>
    CYCLEDISCOUNTSUNIQUEAFTERCYCLE,

    /// <summary>
    /// The adjustment value must the same type as the adjustment type.
    /// </summary>
    INVALIDADJUSTMENTTYPE,

    /// <summary>
    /// The adjustment value must be either fixed_value or percentage.
    /// </summary>
    INVALIDADJUSTMENTVALUE,

    /// <summary>
    /// Another operation updated the contract concurrently as the commit was in progress.
    /// </summary>
    STALECONTRACT,

    /// <summary>
    /// Currency is not enabled.
    /// </summary>
    CURRENCYNOTENABLED,

    /// <summary>
    /// Cannot update a subscription contract with a current or upcoming billing cycle contract edit.
    /// </summary>
    HASFUTUREEDITS,

    /// <summary>
    /// Cannot commit a billing cycle contract draft with this mutation. Please use SubscriptionBillingCycleContractDraftCommit.
    /// </summary>
    BILLINGCYCLEPRESENT,

    /// <summary>
    /// Cannot commit a contract draft with this mutation. Please use SubscriptionDraftCommit.
    /// </summary>
    BILLINGCYCLEABSENT,

    /// <summary>
    /// Delivery policy cannot be updated for billing cycle contract drafts.
    /// </summary>
    BILLINGCYCLECONTRACTDRAFTDELIVERYPOLICYINVALID,

    /// <summary>
    /// Billing policy cannot be updated for billing cycle contract drafts.
    /// </summary>
    BILLINGCYCLECONTRACTDRAFTBILLINGPOLICYINVALID,

    /// <summary>
    /// Contract draft must be a billing cycle contract draft for contract concatenation.
    /// </summary>
    CONCATENATIONBILLINGCYCLECONTRACTDRAFTREQUIRED,

    /// <summary>
    /// Cannot concatenate a contract draft from subscriptionContractCreate mutation.
    /// </summary>
    CONCATENATIONUNCOMMITTEDCONTRACTDRAFT,

    /// <summary>
    /// Concatenated contracts cannot contain duplicate subscription contracts.
    /// </summary>
    DUPLICATECONCATENATEDCONTRACTS,

    /// <summary>
    /// Billing cycle selector cannot select upcoming billing cycle past limit.
    /// </summary>
    UPCOMINGCYCLELIMITEXCEEDED,

    /// <summary>
    /// Billing cycle selector cannot select billing cycle outside of index range.
    /// </summary>
    CYCLEINDEXOUTOFRANGE,

    /// <summary>
    /// Billing cycle selector cannot select billing cycle outside of start date range.
    /// </summary>
    CYCLESTARTDATEOUTOFRANGE,

    /// <summary>
    /// Billing cycle selector requires exactly one of index or date to be provided.
    /// </summary>
    CYCLESELECTORVALIDATEONEOF,

    /// <summary>
    /// Maximum number of concatenated contracts on a billing cycle contract draft exceeded.
    /// </summary>
    EXCEEDEDMAXCONCATENATEDCONTRACTS,

    /// <summary>
    /// Customer is scheduled for redaction or has been redacted.
    /// </summary>
    CUSTOMERREDACTED,

    /// <summary>
    /// Customer payment method is required.
    /// </summary>
    MISSINGCUSTOMERPAYMENTMETHOD,

    /// <summary>
    /// The input value is invalid.
    /// </summary>
    INVALID,

    /// <summary>
    /// The input value is blank.
    /// </summary>
    BLANK,

    /// <summary>
    /// The input value should be greater than the minimum allowed value.
    /// </summary>
    GREATERTHAN,

    /// <summary>
    /// The input value should be greater than or equal to the minimum value allowed.
    /// </summary>
    GREATERTHANOREQUALTO,

    /// <summary>
    /// The input value should be less than the maximum value allowed.
    /// </summary>
    LESSTHAN,

    /// <summary>
    /// The input value should be less than or equal to the maximum value allowed.
    /// </summary>
    LESSTHANOREQUALTO,

    /// <summary>
    /// The input value is too long.
    /// </summary>
    TOOLONG,

    /// <summary>
    /// The input value is too short.
    /// </summary>
    TOOSHORT

}
