// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Possible error codes that can be returned by `TransactionVoidUserError`.
/// </summary>
public enum TransactionVoidUserErrorCode
{
    /// <summary>
    /// Transaction does not exist.
    /// </summary>
    TRANSACTIONNOTFOUND,

    /// <summary>
    /// Transaction must be a successful authorization.
    /// </summary>
    AUTHNOTSUCCESSFUL,

    /// <summary>
    /// Transaction must be voidable.
    /// </summary>
    AUTHNOTVOIDABLE,

    /// <summary>
    /// A generic error occurred while attempting to void the transaction.
    /// </summary>
    GENERICERROR

}
