// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The accepted types of unit of measurement.
/// </summary>
public enum UnitPriceMeasurementMeasuredType
{
    /// <summary>
    /// Unit of measurements representing volumes.
    /// </summary>
    VOLUME,

    /// <summary>
    /// Unit of measurements representing weights.
    /// </summary>
    WEIGHT,

    /// <summary>
    /// Unit of measurements representing lengths.
    /// </summary>
    LENGTH,

    /// <summary>
    /// Unit of measurements representing areas.
    /// </summary>
    AREA,

    /// <summary>
    /// Unit of measurements representing counts.
    /// </summary>
    COUNT,

    /// <summary>
    /// The type of measurement is unknown. Upgrade to the latest version of the API to resolve this type.
    /// </summary>
    UNKNOWN

}
