// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// The set of valid sort keys for the UrlRedirect query.
/// </summary>
public enum UrlRedirectSortKeys
{
    /// <summary>
    /// Sort by the `id` value.
    /// </summary>
    ID,

    /// <summary>
    /// Sort by the `path` value.
    /// </summary>
    PATH,

    /// <summary>
    /// Sort by relevance to the search terms when the `query` parameter is specified on the connection.
    /// Don't use this sort key when no search query is specified.
    /// </summary>
    RELEVANCE

}
