// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'marketingActivityUpsertExternal' GraphQL operation.
/// </summary>
public sealed class MarketingActivityUpsertExternalVariables
{
    [JsonPropertyName("input")]
    public MarketingActivityUpsertExternalInput Input { get; init; } = null!;

}
