// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'fulfillmentTrackingInfo' resource.
/// </summary>
public sealed partial class FulfillmentTrackingInfoBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public FulfillmentTrackingInfoBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'fulfillmentTrackingInfoUpdate' mutation.</summary>
    public FulfillmentTrackingInfoUpdateRequestBuilder Update => new FulfillmentTrackingInfoUpdateRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'fulfillmentTrackingInfoUpdateV2' mutation.</summary>
    public FulfillmentTrackingInfoUpdateV2RequestBuilder UpdateV2 => new FulfillmentTrackingInfoUpdateV2RequestBuilder(_graphQlClient);

}
