// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'delegateAccessTokenDestroy' GraphQL operation.
/// </summary>
public sealed partial class DelegateAccessTokenDestroyData
{
    /// <summary>
    /// Destroys a delegate access token.
    /// </summary>
    [JsonPropertyName("delegateAccessTokenDestroy")]
    public DelegateAccessTokenDestroyPayload? DelegateAccessTokenDestroy { get; init; }
}
