// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'draftOrderDuplicate' GraphQL operation.
/// </summary>
public sealed partial class DraftOrderDuplicateData
{
    /// <summary>
    /// Duplicates a draft order.
    /// </summary>
    [JsonPropertyName("draftOrderDuplicate")]
    public DraftOrderDuplicatePayload? DraftOrderDuplicate { get; init; }
}
