// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'discountCodeFreeShippingCreate' GraphQL operation.
/// </summary>
public sealed partial class DiscountCodeFreeShippingCreateData
{
    /// <summary>
    /// Creates an [free shipping discount](https://help.shopify.com/manual/discounts/discount-types/free-shipping) that's applied on a cart and at checkout when a customer enters a code.
    /// 
    /// &gt; Note:
    /// &gt; To create discounts that are automatically applied on a cart and at checkout, use the [`discountAutomaticFreeShippingCreate`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/discountAutomaticFreeShippingCreate) mutation.
    /// </summary>
    [JsonPropertyName("discountCodeFreeShippingCreate")]
    public DiscountCodeFreeShippingCreatePayload? DiscountCodeFreeShippingCreate { get; init; }
}
