// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'flowTriggerReceive' GraphQL operation.
/// </summary>
public sealed partial class FlowTriggerReceiveData
{
    /// <summary>
    /// Triggers any workflows that begin with the trigger specified in the request body. To learn more, refer to [_Create Shopify Flow triggers_](https://shopify.dev/apps/flow/triggers).
    /// </summary>
    [JsonPropertyName("flowTriggerReceive")]
    public FlowTriggerReceivePayload? FlowTriggerReceive { get; init; }
}
