// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'companyContactCreate' GraphQL mutation.
/// </summary>
public sealed partial class CompanyContactCreateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public CompanyContactCreateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'companyContactCreate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<CompanyContactCreateData>> Execute(CompanyContactCreateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation CompanyContactCreate($companyId: ID!, $input: CompanyContactInput!) { companyContactCreate(companyId: $companyId, input: $input) { companyContact { company { contactCount createdAt customerSince defaultCursor externalId hasTimelineComment id lifetimeDuration name note updatedAt } createdAt customer { canDelete createdAt dataSaleOptOut displayName email firstName hasTimelineComment id lastName legacyResourceId lifetimeDuration locale multipassIdentifier note numberOfOrders phone productSubscriberStatus state tags taxExempt taxExemptions unsubscribeUrl updatedAt validEmailAddress verifiedEmail } id isMainContact lifetimeDuration locale title updatedAt } userErrors { code field message } } }";
        return _graphQlClient.Execute<CompanyContactCreateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'companyContactCreate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<CompanyContactCreatePayload?> GetValue(CompanyContactCreateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<CompanyContactCreateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.CompanyContactCreate;
    }
}
