// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'inventorySetOnHandQuantities' GraphQL operation.
/// </summary>
public sealed partial class InventorySetOnHandQuantitiesData
{
    /// <summary>
    /// Sets an inventory item's on-hand quantities to specific absolute values at designated locations. The mutation takes a reason for tracking purposes and a reference document URI for audit trails.
    /// 
    /// Returns an [`InventoryAdjustmentGroup`](https://shopify.dev/docs/api/admin-graphql/latest/objects/InventoryAdjustmentGroup) that tracks all changes made in this operation, including the delta values calculated from the previous quantities.
    /// 
    /// &gt; Caution:
    /// &gt; As of 2026-01, this mutation supports an optional idempotency key using the `@idempotent` directive.
    /// &gt; As of 2026-04, the idempotency key is required and must be provided using the `@idempotent` directive.
    /// &gt; For more information, see the [idempotency documentation](https://shopify.dev/docs/api/usage/idempotent-requests).
    /// </summary>
    [JsonPropertyName("inventorySetOnHandQuantities")]
    public InventorySetOnHandQuantitiesPayload? InventorySetOnHandQuantities { get; init; }
}
