// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'mobilePlatformApplicationCreate' GraphQL operation.
/// </summary>
public sealed class MobilePlatformApplicationCreateVariables
{
    [JsonPropertyName("input")]
    public MobilePlatformApplicationCreateInput Input { get; init; } = null!;

}
