// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'giftCardSendNotificationToCustomer' GraphQL operation.
/// </summary>
public sealed class GiftCardSendNotificationToCustomerVariables
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = null!;

}
