// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'giftCardSendNotificationToCustomer' GraphQL mutation.
/// </summary>
public sealed partial class GiftCardSendNotificationToCustomerRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public GiftCardSendNotificationToCustomerRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'giftCardSendNotificationToCustomer' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<GiftCardSendNotificationToCustomerData>> Execute(GiftCardSendNotificationToCustomerVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation GiftCardSendNotificationToCustomer($id: ID!) { giftCardSendNotificationToCustomer(id: $id) { giftCard { balance { amount currencyCode } createdAt customer { canDelete createdAt dataSaleOptOut displayName email firstName hasTimelineComment id lastName legacyResourceId lifetimeDuration locale multipassIdentifier note numberOfOrders phone productSubscriberStatus state tags taxExempt taxExemptions unsubscribeUrl updatedAt validEmailAddress verifiedEmail } deactivatedAt enabled expiresOn id initialValue { amount currencyCode } lastCharacters maskedCode note order { billingAddressMatchesShippingAddress canMarkAsPaid canNotifyCustomer cancelReason cancelledAt capturable cartDiscountAmount clientIp closed closedAt confirmationNumber confirmed createdAt currencyCode currentSubtotalLineItemsQuantity currentTotalWeight customerAcceptsMarketing customerLocale discountCode discountCodes displayFinancialStatus displayFulfillmentStatus dutiesIncluded edited email estimatedTaxes fulfillable fullyPaid hasTimelineComment id landingPageDisplayText landingPageUrl legacyResourceId merchantEditable merchantEditableErrors name netPayment note number paymentGatewayNames phone poNumber presentmentCurrencyCode processedAt productNetwork referralCode referrerDisplayText referrerUrl refundable registeredSourceUrl requiresShipping restockable returnStatus riskLevel sourceIdentifier sourceName subtotalLineItemsQuantity subtotalPrice tags taxExempt taxesIncluded test totalCapturable totalDiscounts totalPrice totalReceived totalRefunded totalShippingPrice totalTax totalWeight unpaid updatedAt } recipientAttributes { message preferredName sendNotificationAt } templateSuffix updatedAt } userErrors { code field message } } }";
        return _graphQlClient.Execute<GiftCardSendNotificationToCustomerData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'giftCardSendNotificationToCustomer' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<GiftCardSendNotificationToCustomerPayload?> GetValue(GiftCardSendNotificationToCustomerVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<GiftCardSendNotificationToCustomerData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.GiftCardSendNotificationToCustomer;
    }
}
