// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'appSubscription' resource.
/// </summary>
public sealed partial class AppSubscriptionBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public AppSubscriptionBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes requests for the 'appSubscriptionCancel' mutation.</summary>
    public AppSubscriptionCancelRequestBuilder Cancel => new AppSubscriptionCancelRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'appSubscriptionCreate' mutation.</summary>
    public AppSubscriptionCreateRequestBuilder Create => new AppSubscriptionCreateRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'appSubscriptionLineItemUpdate' mutation.</summary>
    public AppSubscriptionLineItemUpdateRequestBuilder LineItemUpdate => new AppSubscriptionLineItemUpdateRequestBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'appSubscriptionTrialExtend' mutation.</summary>
    public AppSubscriptionTrialExtendRequestBuilder TrialExtend => new AppSubscriptionTrialExtendRequestBuilder(_graphQlClient);

}
