// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'urlRedirectDelete' GraphQL operation.
/// </summary>
public sealed partial class UrlRedirectDeleteData
{
    /// <summary>
    /// Deletes a [`UrlRedirect`](https://shopify.dev/api/admin-graphql/latest/objects/UrlRedirect) object.
    /// </summary>
    [JsonPropertyName("urlRedirectDelete")]
    public UrlRedirectDeletePayload? UrlRedirectDelete { get; init; }
}
