// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'discountAutomaticActivate' GraphQL operation.
/// </summary>
public sealed partial class DiscountAutomaticActivateData
{
    /// <summary>
    /// Activates an automatic discount.
    /// </summary>
    [JsonPropertyName("discountAutomaticActivate")]
    public DiscountAutomaticActivatePayload? DiscountAutomaticActivate { get; init; }
}
