// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'pubSubServerPixelUpdate' GraphQL mutation.
/// </summary>
public sealed partial class PubSubServerPixelUpdateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public PubSubServerPixelUpdateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'pubSubServerPixelUpdate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<PubSubServerPixelUpdateData>> Execute(PubSubServerPixelUpdateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation PubSubServerPixelUpdate($pubSubProject: String!, $pubSubTopic: String!) { pubSubServerPixelUpdate(pubSubProject: $pubSubProject, pubSubTopic: $pubSubTopic) { serverPixel { id status webhookEndpointAddress } userErrors { code field message } } }";
        return _graphQlClient.Execute<PubSubServerPixelUpdateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'pubSubServerPixelUpdate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<PubSubServerPixelUpdatePayload?> GetValue(PubSubServerPixelUpdateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<PubSubServerPixelUpdateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.PubSubServerPixelUpdate;
    }
}
