// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Response data wrapper for the 'collectionCreate' GraphQL operation.
/// </summary>
public sealed partial class CollectionCreateData
{
    /// <summary>
    /// Creates a [collection](https://shopify.dev/docs/api/admin-graphql/latest/objects/Collection)
    /// to group [products](https://shopify.dev/docs/api/admin-graphql/latest/objects/Product) together
    /// in the [online store](https://shopify.dev/docs/apps/build/online-store) and
    /// other [sales channels](https://shopify.dev/docs/apps/build/sales-channels).
    /// For example, an athletics store might create different collections for running attire, shoes, and accessories.
    /// 
    /// There are two types of collections:
    /// 
    /// - **[Custom (manual) collections](https://help.shopify.com/manual/products/collections/manual-shopify-collection)**: You specify the products to include in a collection.
    /// - **[Smart (automated) collections](https://help.shopify.com/manual/products/collections/automated-collections)**: You define rules, and products matching those rules are automatically
    /// included in the collection.
    /// 
    /// Use the `collectionCreate` mutation when you need to:
    /// 
    /// - Create a new collection for a product launch or campaign
    /// - Organize products by category, season, or promotion
    /// - Automate product grouping using rules (for example, by tag, type, or price)
    /// 
    /// &gt; Note:
    /// &gt; The created collection is unpublished by default. To make it available to customers,
    /// use the [`publishablePublish`](https://shopify.dev/docs/api/admin-graphql/latest/mutations/publishablePublish)
    /// mutation after creation.
    /// 
    /// Learn more about [using metafields with smart collections](https://shopify.dev/docs/apps/build/custom-data/metafields/use-metafield-capabilities).
    /// </summary>
    [JsonPropertyName("collectionCreate")]
    public CollectionCreatePayload? CollectionCreate { get; init; }
}
