// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Request parameters for the 'customerSegmentMembersQueryCreate' GraphQL operation.
/// </summary>
public sealed class CustomerSegmentMembersQueryCreateVariables
{
    [JsonPropertyName("input")]
    public CustomerSegmentMembersQueryInput Input { get; init; } = null!;

}
