// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'abandonmentEmailStateUpdate' GraphQL mutation.
/// </summary>
public sealed partial class AbandonmentEmailStateUpdateRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public AbandonmentEmailStateUpdateRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'abandonmentEmailStateUpdate' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<AbandonmentEmailStateUpdateData>> Execute(AbandonmentEmailStateUpdateVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation AbandonmentEmailStateUpdate($id: ID!, $emailState: AbandonmentEmailState!, $emailSentAt: DateTime, $emailStateChangeReason: String) { abandonmentEmailStateUpdate(id: $id, emailState: $emailState, emailSentAt: $emailSentAt, emailStateChangeReason: $emailStateChangeReason) { abandonment { abandonedCheckoutPayload { abandonedCheckoutUrl completedAt createdAt defaultCursor discountCodes id lineItemsQuantity name note taxesIncluded updatedAt } abandonmentType app { apiKey appStoreAppUrl appStoreDeveloperUrl description developerName developerType developerUrl embedded features handle id installUrl isPostPurchaseAppInUse launchUrl previouslyInstalled pricingDetails pricingDetailsSummary privacyPolicyUrl publicCategory published shopifyDeveloped title uninstallMessage uninstallUrl webhookApiVersion } cartUrl createdAt customer { canDelete createdAt dataSaleOptOut displayName email firstName hasTimelineComment id lastName legacyResourceId lifetimeDuration locale multipassIdentifier note numberOfOrders phone productSubscriberStatus state tags taxExempt taxExemptions unsubscribeUrl updatedAt validEmailAddress verifiedEmail } customerHasNoDraftOrderSinceAbandonment customerHasNoOrderSinceAbandonment daysSinceLastAbandonmentEmail emailSentAt emailState hoursSinceLastAbandonedCheckout id inventoryAvailable isFromCustomStorefront isFromOnlineStore isFromShopApp isFromShopPay isMostSignificantAbandonment lastBrowseAbandonmentDate lastCartAbandonmentDate lastCheckoutAbandonmentDate mostRecentStep visitStartedAt } userErrors { code field message } } }";
        return _graphQlClient.Execute<AbandonmentEmailStateUpdateData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'abandonmentEmailStateUpdate' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<AbandonmentEmailStateUpdatePayload?> GetValue(AbandonmentEmailStateUpdateVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<AbandonmentEmailStateUpdateData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.AbandonmentEmailStateUpdate;
    }
}
