// <auto-generated />
#nullable enable
using Soenneker.Extensions.ValueTask;
using System.Threading;
using System.Threading.Tasks;

namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Builds and executes requests for the 'fulfillmentOrderLineItemsPreparedForPickup' GraphQL mutation.
/// </summary>
public sealed partial class FulfillmentOrderLineItemsPreparedForPickupRequestBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public FulfillmentOrderLineItemsPreparedForPickupRequestBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Executes the GraphQL mutation 'fulfillmentOrderLineItemsPreparedForPickup' with the given request parameters.
    /// </summary>
    public ValueTask<GraphQlResponse<FulfillmentOrderLineItemsPreparedForPickupData>> Execute(FulfillmentOrderLineItemsPreparedForPickupVariables request, CancellationToken cancellationToken = default)
    {
        const string gqlQuery = @"mutation FulfillmentOrderLineItemsPreparedForPickup($input: FulfillmentOrderLineItemsPreparedForPickupInput!) { fulfillmentOrderLineItemsPreparedForPickup(input: $input) { userErrors { code field message } } }";
        return _graphQlClient.Execute<FulfillmentOrderLineItemsPreparedForPickupData>(gqlQuery, request, cancellationToken);
    }

    /// <summary>
    /// Executes the operation and returns only the 'fulfillmentOrderLineItemsPreparedForPickup' value from the GraphQL data envelope.
    /// </summary>
    public async ValueTask<FulfillmentOrderLineItemsPreparedForPickupPayload?> GetValue(FulfillmentOrderLineItemsPreparedForPickupVariables request, CancellationToken cancellationToken = default)
    {
        GraphQlResponse<FulfillmentOrderLineItemsPreparedForPickupData> response = await Execute(request, cancellationToken).NoSync();
        return response.Data?.FulfillmentOrderLineItemsPreparedForPickup;
    }
}
