// <auto-generated />
#nullable enable
namespace Soenneker.Shopify.GraphQlClient;

/// <summary>
/// Groups GraphQL request builders for the 'reverse' resource.
/// </summary>
public sealed partial class ReverseBuilder
{
    private readonly IGraphQlClient _graphQlClient;

    public ReverseBuilder(IGraphQlClient graphQlClient)
    {
        _graphQlClient = graphQlClient;
    }

    /// <summary>
    /// Builds and executes grouped requests for the 'reverseDelivery' resource.</summary>
    public ReverseDeliveryBuilder Delivery => new ReverseDeliveryBuilder(_graphQlClient);

    /// <summary>
    /// Builds and executes requests for the 'reverseFulfillmentOrderDispose' mutation.</summary>
    public ReverseFulfillmentOrderDisposeRequestBuilder FulfillmentOrderDispose => new ReverseFulfillmentOrderDisposeRequestBuilder(_graphQlClient);

}
